### ISSUE TITLE
Adding labels  and titles to nested plots

### ISSUE THREAD

**Issue by llrs** [thomasp85/patchwork#1]
Nice package!! Easy to use and powerful! I almost started using when I found it. 

I know that it is still under development and perhaps it is already on your TODO list (and too early to jump in), but I have seen the recent addition of nested plots and I would like to know if it will be possible to name each nested plot or each plot (besides giving a title when creating it). 

Something like this plot:
 [![][2]][2]

Many thanks for your efforts!

  [2]: http://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-016-1037-6/MediaObjects/13059_2016_1037_Fig2_HTML.gif

**Comment by thomasp85** [comment]
This is on my radar and will probably be added at some point...

**Comment by odeleongt** [comment]
Definitely useful, but can't think of a way that does not result in a very monolithic (_i.e._ complex function addressing a very specific issue) or very low level (e.g. `gridExtra::` add several grobs as can already be done) approach.

I just love how it works now, since you just keep doing whatever you did with `ggplot2` and somehow group the ggplot objects:

```r
library(package = "ggplot2")
library(package = "patchwork")

# Setup common theme elements for all the plots
theme_set(
  theme_bw() +
    theme(
      plot.subtitle = element_text(face = "bold")
    )
)

#------------------------------------------------------------------------------*
# Plot 1
#------------------------------------------------------------------------------*
ggplot(mtcars) +
  geom_point( aes(disp, mpg, color = factor(cyl)), show.legend = FALSE ) +
  # Individual plot annotations
  labs(
    title = paste(
      "Figure 1: Relations between fuel displacement,",
      "horsepower and fuel efficiency."
    ),
    subtitle = "A", caption = "Some inconspicuous text."
  ) +
  theme(plot.caption = element_text(hjust = 0)) +
  { # <--- nested plots
    #--------------------------------------------------------------------------*
    # Plot 2
    #--------------------------------------------------------------------------*
    ggplot(mtcars) +
      geom_point(aes(disp, hp, color = factor(cyl))) +
      # Individual plot annotations
      labs(subtitle = "B") +
      # Spacing
      patchwork::plot_spacer() +
      { # <--- nested plots
        #----------------------------------------------------------------------*
        # Plot 3
        #----------------------------------------------------------------------*
        ggplot(mtcars) +
          geom_point( aes(hp, mpg, color = factor(cyl)), show.legend = FALSE ) +
          # Individual plot annotations
          labs(subtitle = "C")
      } +
      patchwork::plot_layout(ncol = 1)
  } +
  patchwork::plot_layout(ncol = 2, widths = c(2.2, 1))
```

![image](https://user-images.githubusercontent.com/1044835/33638410-ba5cd9d8-d9eb-11e7-92e1-ddd657f72e02.png)

**Comment by thomasp85** [comment]
I've come to agree with @odeleongt in that labelling is probably best taken care of by what ggplot2 already has to offer in terms of titles, subtitles and captions
