### ISSUE TITLE
Support for ggmatrix

### ISSUE THREAD

**Issue by tvatter** [thomasp85/patchwork#100]
Hi,

Currently, GGally provides the useful function ggpairs, which has no equivalent directly in ggplot. Its output is a ggmatrix, similar to the output of GGally's functin ggmatrix.

Would it be possible to have some kind of support this kind of object?

Otherwise, any suggestions to integrate something that behaves similarly to base R's pairs function?

**Comment by thomasp85** [comment]
If GGally provides a way to turn this object into a grob (equivalent to `ggplot2::ggplotGrob()`) then you could simply call that prior to using patchwork.

I'm reluctant to add support for strange objects beyond what ggplot2 offers, as the maintenance burden would be too high, and adding support for constructing a pairs plot is also outside of the scope of patchwork. It should be pretty easy to build on top of it, though...

**Comment by stemangiola** [comment]
This is now a solution.

```r
wrap_elements(ggmatrix_gtable(ggpairs_plot_1)) + wrap_elements(ggmatrix_gtable(ggpairs_plot_2))

```
