### ISSUE TITLE
Great package - when are you getting it on CRAN?

### ISSUE THREAD

**Issue by talgalili** [thomasp85/patchwork#101]
(sorry for the nudge, but it feels a shame to not have it there)

Cheers,
T

**Comment by kuriwaki** [comment]
Agree, I'd like to use this as the recommended ggplot-combination package for my  students in introduction to stats/R this summer, but that's a hard sell unless the package is on CRAN.

**Comment by thomasp85** [comment]
I have many projects to keep on top of. Patchwork will of course end on CRAN, hopefully within the year, but I have a few other things to take care of first
