### ISSUE TITLE
Quick ice-cream related suggestion

### ISSUE THREAD

**Issue by hlynurhallgrims** [thomasp85/patchwork#103]
As it is 'ferietid' I wanted to give a friendly suggestion. I think patchwork would greatly benefit from @thomasp85 having a nice, leisurely bicycle ride to the nearest ice-cream parlour and enjoying some refreshments 😄🍦

**Comment by dtelad11** [comment]
Speaking of which, @thomasp85, do you have any plans to continue working on `patchwork` in the near/far future? If I recall correctly you focused on for gganimate for a while.

**Comment by llrs** [comment]
Now he is focused on [ggraph](https://twitter.com/thomasp85/status/1160106273330929665).

**Comment by thomasp85** [comment]
Patchwork will get attention after ggraph and hopefully within the year
