### ISSUE TITLE
Title gets lost when adding 2 patchwork-ggplot objects

### ISSUE THREAD

**Issue by efratushava** [thomasp85/patchwork#104]
Hello,

My code looks like this:
`plots <- lapply(c("RNF2","EMX1"),function(x) {
  plot_grna <- lapply(c("rep1","rep2","rep3"), function(rep){
    sample <-rep_num[grep(rep,rep_num[grep(x,rep_num$Group),c("Group")]),c("Sample")]
    path <- all_files_G2A[grep(paste0(sample,".ES.bed_files"),all_files_G2A)]
    ggplot() + geom_logo(as.character(data$motif),method = 'p') + theme_logo() + 
      ylab(paste("Rep.",stringi::stri_sub(rep,-1,-1)))+
      theme(legend.position="none",
            axis.title.y = element_text(angle = 0,  vjust=0.5,size=20))
  })
  
-----here I plot the inner loop plot, with its own title
  **plot_grna[[1]]+plot_grna[[2]]+plot_grna[[3]]+plot_layout(ncol = 1)+ plot_annotation(title = paste(x,"gRNA"))** 
})

---- plots[[1]]+plots[[2]]+plot_layout(ncol = 2)-didn't work somehow
plots[[1]] | plots[[2]]`

plots[[1]] looks like this:
![image](https://user-images.githubusercontent.com/26773189/62839054-a8ce1700-bc8d-11e9-9f93-e81d251826a6.png)

and plot[[1]] | plot[[2]] looks:

**Comment by efratushava** [comment]
![plot_zoom_png](https://user-images.githubusercontent.com/26773189/62839088-0f533500-bc8e-11e9-865a-27bb14c1ccff.png)

**Comment by steveharoz** [comment]
Hi @efratushava 

It'd be helpful if you could format your code. 

If you type this:

\`\`\`
Your code here
\`\`\`

You'll see this:

```
Your code here
```
