### ISSUE TITLE
RStudio project files

### ISSUE THREAD

**Issue by steveharoz** [thomasp85/patchwork#105]
I cloned the project to try making some edits, but there doesn't appear to be an RStudio project. If you could add it to git, I (and probably many more capable people) would be happy to add some features. Building packages is much easier if it's already set up.

**Comment by thomasp85** [comment]
I really do not like having this as part of version control. If you intend to contribute (which I welcome) isn’t it easier to simply *create project from version control* which sets up everything you need

**Comment by steveharoz** [comment]
I understand, and generally I agree. But keep in mind that packages are mysterious and intimidating, even to people who have a lot of experience with R. I spent some time googling what I'd need to do to get it to work until I realized that if I just make a project in the directory, RStudio would handle the rest.

So while the user files should definitely stay ignored, including the .Rproj file might help lower a barrier to people contributing or just trying to figure out how it works.
