### ISSUE TITLE
Select the position of the tag

### ISSUE THREAD

**Issue by llrs** [thomasp85/patchwork#108]
With the new option of ggplot2 to place titles above the grid region, maybe it can be tuned the position of the tag too here on patchwork

```r 
library("ggplot2")
library("patchwork")

p1 <- ggplot(mtcars) + 
   geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + 
   geom_boxplot(aes(gear, disp, group = gear)) + 
   theme(axis.text.y = element_blank(),
         axis.ticks.y = element_blank(),
         axis.title.y = element_blank())

p1 + p2 + plot_annotation(tag_levels = "A")
```
![patchwork](https://user-images.githubusercontent.com/6818218/69139315-8f284100-0ac0-11ea-9fa3-bf0e5085f645.png)

It would be nice to have both tags on the same position relative to their plot (have A like B, above the axis.ticks).

**Comment by thomasp85** [comment]
patchwork is using the tag labelling in ggplot2 and will not provide any other positioning scheme than that

**Comment by llrs** [comment]
Ok, thanks again for this amazing package
