### ISSUE TITLE
The nested layouts can't be put in the beginning

### ISSUE THREAD

**Issue by Cainefm** [thomasp85/patchwork#109]
I have been struggling in deploying the plots recently. It's so great that patchwork by Thomas provides a good solution. During the plotting, I found that the nested layouts can't be the first element which may mess up the plot. Fortunately, I figure out that an empty plot_spacer() can set as a placeholder. I wish my finding may help.

**Comment by llrs** [comment]
I have a hard time imaging this. Could you please provide some code to reproduce this issue (mabye using the same plots as from the README?). You can use the [reprex](https://github.com/tidyverse/reprex) package

**Comment by steveharoz** [comment]
It seems to work for this example. Feel free to reopen with a reproducible example of the issue.

```r
library(tidyverse)
library(patchwork)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_point(aes(cyl, hp))

(p1 | p2) / p3
```
![image](https://user-images.githubusercontent.com/2257540/65255678-9baf0e00-dafe-11e9-966f-3c06d8ae4099.png)

**Comment by Cainefm** [comment]
I am a rookie in coding and Github. Thanks for your help. 

I have to plot a complex combination of multiple figures so I did my plot with parentheses. 

Here is the target plot with its codes:
![TestforGithub](https://user-images.githubusercontent.com/20833144/65297957-432e4e00-db9c-11e9-9fdf-f4e33b7da201.png)
```r
library(tidyverse)
library(patchwork)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))

plot_spacer()+{
    {
        {p1 + p1 + p1 + p1 +plot_layout(ncol=2)} + 
            {p2 + p2 + p2 + p2 + p2 + p2 + plot_layout(ncol=3)} 
    } + plot_layout(ncol=1)
} + p3 + plot_layout(ncol=3,widths = c(0,1,1))
```

In the beginning, I used the coding like this: 
```r
{
   {
        {p1 + p1 + p1 + p1 +plot_layout(ncol=2)} + 
            {p2 + p2 + p2 + p2 + p2 + p2 + plot_layout(ncol=3)} 
    } + plot_layout(ncol=1)
} + p3 + plot_layout(ncol=2,widths = c(1,1))
```

The picture looks like this:

![TestForGithub2](https://user-images.githubusercontent.com/20833144/65298404-f8add100-db9d-11e9-89cf-7a72cd5d6824.png)

Maybe I made a wrong use of the patchwork in the beginning. Thanks again.


> I have a hard time imaging this. Could you please provide some code to reproduce this issue (maybe using the same plots as from the README?). You can use the [reprex](https://github.com/tidyverse/reprex) package
