### ISSUE TITLE
axis panel size should be determind by its own axis label size

### ISSUE THREAD

**Issue by yiluheihei** [thomasp85/patchwork#110]
Thanks for your great work **patchwork**.

While vertical align two ggplots, the two axis panels of the two plots keep in the same size. It will generate unnecessary space in the axis panel, while the axis label of a plot is much longer then the other, e.g.

``` r
library(patchwork)
library(ggplot2)

p1 <- ggplot(diamonds, aes(clarity, price)) + 
  geom_boxplot() +
  coord_flip()

lev <- levels(diamonds$cut)
long_label <- paste("Very Very Very Very", lev)
names(long_label) <- lev
p2 <- ggplot(diamonds, aes(cut, price)) + 
  geom_boxplot() +
  scale_x_discrete(labels = long_label) + 
  coord_flip()

p1 + p2 + plot_layout(ncol = 1)
```

![](https://i.imgur.com/EznlfYZ.png)

<sup>Created on 2019-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The figure I want to is shown as below

``` r
cowplot::plot_grid(p1, p2, ncol = 1)
```

![](https://i.imgur.com/NfHKO0E.png)

<sup>Created on 2019-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks.

**Comment by thomasp85** [comment]
This is really not what patchwork is about... the whole goal is to align plot areas.

That being said, you can achieve this using `wrap_elements()`, but the cowplot code is likely more readable 🤷‍♂️

```r
wrap_elements(full = p1) + wrap_elements(full = p2) + plot_layout(ncol = 1)
```
![image](https://user-images.githubusercontent.com/1775316/69145044-0794ff00-0acd-11ea-948b-8e87982a81a7.png)

**Comment by kendonB** [comment]
@thomasp85 I have a related issue to that here. How does one move the y-axis title close to the panel in patchwork? I still want the panels aligned but not the y-axis titles.

**Comment by thomasp85** [comment]
That is not possible and I’m not sure it ever will be

**Comment by LDSamson** [comment]
> @thomasp85 I have a related issue to that here. How does one move the y-axis title close to the panel in patchwork? I still want the panels aligned but not the y-axis titles.

@kendonB You can edit the patchwork manually if you want with some trial and error, this worked for me: https://stackoverflow.com/a/62328273/11856430
In your, case, you should probably change the 'ylab-l' layout values (value 'l' (=left))

**Comment by joey711** [comment]
@thomasp85 @kendonB I think adding a negative margin `theme` spec works, provided you're willing to trial-and-error the margin needed to make it work. I added an example solution here: https://stackoverflow.com/questions/62304750/ignore-x-label-alignment-with-multiple-plots-in-patchwork-is-this-possible/62328273

**Comment by elong0527** [comment]
How about using `inset_element`? 

```
library(ggplot2)
library(patchwork)
library(patchwork)
library(ggplot2)

p1 <- ggplot(diamonds, aes(clarity, price)) + 
  geom_boxplot() +
  coord_flip()

lev <- levels(diamonds$cut)
long_label <- paste("Very Very Very Very", lev)
names(long_label) <- lev
p2 <- ggplot(diamonds, aes(cut, price)) + 
  geom_boxplot() +
  scale_x_discrete(labels = long_label) + 
  coord_flip()

p1 + p2 + plot_layout(ncol = 1)

text <- ggplot() + ylab("update label") +
  theme_bw(base_rect_size = 0) + 
  theme(
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent") # get rid of legend panel bg
  )
  
# 0.53 can be replaced to other font height and width ratio.
n_line <- max(nchar(as.character(p1$data$clarity))) * 0.53 + 1
p1 + inset_element(text, - unit(n_line, "line"), 0, 1, 1) + 
  p2 + 
  plot_layout(ncol = 1)
```

![image](https://user-images.githubusercontent.com/465246/140629501-a7d7c7ec-5393-4b20-97d9-260b126b5756.png)

**Comment by TylerSagendorf** [comment]
@elong0527 You can also just modify `p1` with `annotation_custom` as shown below

```
p1 <- ggplot(diamonds, aes(clarity, price)) + 
  geom_boxplot() +
  annotation_custom(grob = textGrob(
    label = "clarity",
    rot = 90, 
    gp = gpar(fontsize = 11),
    x = -40, default.units = "pt")
  ) +
  coord_flip(clip = "off") +
  theme(axis.title.y = element_blank())
```

This will place 11 point text 40 points below the x-axis before flipping the axes (must include `clip = "off"` or the text outside of the plot area won't be visible). No need for `inset_element`.

<img src="https://user-images.githubusercontent.com/57922480/170775087-691ae1ca-b1ba-4a2b-96e0-2551592de23e.png" width = "600" height = "400">
