### ISSUE TITLE
Error when last plot should span whole width (single column) with nested plots above.

### ISSUE THREAD

**Issue by romanhaa** [thomasp85/patchwork#111]
Hi,

Basically, what I'm trying to do is one of the examples shown in the main readme of this repo, however in a different order. The example is:

```r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec))
p4 <- ggplot(mtcars) + geom_bar(aes(carb))

p4 +
{
  p1 +
  {
    p2 + p3 + plot_layout(ncol = 1)
  }
} +
plot_layout(ncol = 1)
```

![](https://github.com/thomasp85/patchwork/raw/master/man/figures/README-unnamed-chunk-5-1.png)

In my case, I need the `p4` to be at the bottom, the rest would be the same (or at least similar enough). I tried as shown below but it returns all plots in a single column (overwriting the previous layout):

```r
{
  p1 +
  {
    p2 + p3 + plot_layout(ncol = 1)
  }
} +
p4 + plot_layout(ncol = 1)
```

![test](https://user-images.githubusercontent.com/18103560/65949739-0df7ea80-e43d-11e9-8a47-243d462a36a0.png)

Am I missing something obvious?

Thanks,
Roman

**Comment by llrs** [comment]
If I understood well what you mean, you are trying to have one plot on the top, one on the bottom and two on the middle on the same row/space?

If so you can use this:

```r
{
    p1 +
        {
            p2 + p3 + plot_layout(nrow = 1)
        }
} +
    p4 +plot_layout(ncol = 1)
```

The trick is to tell the inner plots to merge them in a single row.

**Comment by romanhaa** [comment]
Actually, I'm just trying to move the top panel (`p4`) to the bottom and the rest be the same (`p1` next to `p2` and `p3` in the same row). No panel at the top which spans the whole width.

```r
{ p1 + { p2 + p3 + plot_layout(nrow = 1) } + plot_layout(nrow = 1) } + p4 + plot_layout(ncol = 1)
# Error in wrap_dims(length(x$plots), nrow = x$layout$nrow, ncol = x$layout$ncol) : 
#   nrow * ncol >= n is not TRUE
```

I probably just don't get the syntax right.

**Comment by llrs** [comment]
Oh, then you need the `/` to place a plot below others

```r
{p1 + { p2 + p3} }/ p4
```

**Comment by romanhaa** [comment]
Right, that's how the layout is supposed to be. But then I also needed to use different widths for the two columns in the top row 😅 But with your help I made it work! Thanks a lot!
