### ISSUE TITLE
Allow users to provide custom character vector of tag names

### ISSUE THREAD

**Issue by mattwarkentin** [thomasp85/patchwork#115]
Hi,

Is it possible to modify the `tag_levels` argument for `plot_annotation` (or just add a `tags` arg) so that in addition to accepting `'A'`, `'a'`, `'1'`, `'i'`, and `'I'` it can also accept a character vector of the same length as the number of plots being combined? This would allow full custom panel labels.

For example:
```r
p1 <- ggplot(iris, aes(Sepal.Width)) + geom_density()
p2 <- ggplot(iris, aes(Sepal.Width)) + geom_histogram()

p1 + p2 + plot_annotation(tag_levels = c('Density', 'Histogram'))
```

**Comment by thomasp85** [comment]
I don’t really think this fits into the “tag” category. Why not give the plots specific titles?

**Comment by mattwarkentin** [comment]
I guess thats fair. My example case isn't very compelling.

I still think there is a use-case for offering user customizability of tags. Perhaps it makes more sense if the tags are:
```r
p1 <- p3 <- ggplot(iris, aes(Sepal.Width)) + geom_density()
p2 <- p4 <- ggplot(iris, aes(Sepal.Width)) + geom_histogram()

{p1 + p2} / {p3 + p4} + plot_annotation(tag_levels = c('A1', 'A2',
                                                       'B1', 'B2'))
```

**Comment by thomasp85** [comment]
I think you are misunderstanding the intent of the `tag_levels` argument. It is setting an automatic tagging scheme, with the potential for nested tagging - not giving the exact tag string... What you requested above can be had with:

```r
{p1 + p2 + plot_layout(tag_level = 'new')} / 
{p3 + p4 + plot_layout(tag_level = 'new')} +
  plot_annotation(tag_levels = c('A', '1'))
```
![image](https://user-images.githubusercontent.com/1775316/69082355-37e28c00-0a40-11ea-8de5-1a2a0587162c.png)

**Comment by thomasp85** [comment]
If you wan't to give a specific tag name, just set it on the plot with `p + labs(tag = '...')`

**Comment by mattwarkentin** [comment]
It was not a misunderstanding of the intent, but rather a misunderstanding of the capabilities. I did not know you could combine `tag_levels` with `c()`. This is what I thought needed to be implemented with more customization. Glad to see it is natively supported.
