### ISSUE TITLE
theme property (axis.ticks) get lost

### ISSUE THREAD

**Issue by dleutnant** [thomasp85/patchwork#12]
Hi Thomas,

I don't know if it's too early to open an issue, but I just encountered an issue and thought you should be notified:

In some of my plots, I shift the axis.ticks to the inside, e.g.

``` r
library(ggplot2)
library(patchwork)

my_theme <- function() {
    theme(
      axis.ticks = element_line(colour = "black"),
      axis.ticks.length = grid::unit(-0.2, "cm"),
      axis.text.x = element_text(margin = grid::unit(c(0.4,0.4,0.2,0.4), "cm")),  
      axis.text.y = element_text(margin = grid::unit(c(0.4,0.4,0.4,0.2), "cm")))
}
```
If I then apply this function to a ggplot2 plot, the axis ticks are shifted as expected: 
``` r
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp)) + my_theme()
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear)) + my_theme()
p1
```
![rplot](https://user-images.githubusercontent.com/13165811/34158179-b0773af6-e4c4-11e7-9f31-079106899edd.png)

However, composing with {patchwork} removes axis.ticks:
``` r
p1 + p2
```

![rplot01](https://user-images.githubusercontent.com/13165811/34158234-da35c024-e4c4-11e7-96cf-11ca0acf9b30.png)

``` r
packageVersion("patchwork")
#> [1] '0.0.1'
packageVersion("ggplot2")
#> [1] '2.2.1.9000'
```

**Comment by thomasp85** [comment]
Nothing premature about it. Thanks for reporting it - I'll look into it

**Comment by dleutnant** [comment]
Thanks, @thomasp85! Well, this indeed resolves the issue reported.

But I also observed, an unexpected behavior with `geom_density` and different assembling operators:
(If `geom_point(aes(mpg, disp))` is used, the behavior is as expected...)
``` r
p1 <- ggplot(mtcars) + geom_density(aes(x = disp)) + my_theme()
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear)) + my_theme()
```

`p1 + p2` correctly yields to

![rplot04](https://user-images.githubusercontent.com/13165811/34203090-2ecf820e-e57a-11e7-98fd-0c922a94df21.png)

while `p1 + p2 + plot_layout(ncol = 1)` gets me (axis.ticks on the bottom plot are back to its roots)

![rplot05](https://user-images.githubusercontent.com/13165811/34203109-35d4c6f4-e57a-11e7-8dfb-3002e7316a46.png)

**Comment by thomasp85** [comment]
Looks like I have some more work to do:-)

Thanks

**Comment by stephhazlitt** [comment]
Hi @thomasp85. Loving your new `patchwork` package! Thank you for making this functionality available to the rstats community.

I have also encountered a small inconsistency with axis tick placement when combining 2 bar charts with `patchwork`. I am sharing a reprex version here in case it is useful or related to this issue.

```
library(dplyr) #v0.7.4 from CRAN
library(ggplot2) #v2.2.1.9000 from GitHub
library(patchwork) #v0.0.1 from GitHub

chart1 <- starwars %>%
  select(name, mass) %>%
  filter(mass < 200 & mass > 100) %>%
  ggplot(aes(x = name, y = mass)) +
  geom_bar(stat = "identity",
           fill = "#ececec",
           colour = "grey30") +
  labs(xlab("")) +
  labs(ylab("")) +
  coord_flip() +
  scale_x_discrete(expand = c(.1, .1)) +
  scale_y_continuous(
    expand = c(0, 0),
    breaks = seq(0, 200, 20),
    limits = c(0, 200)
  ) +
  theme_grey() +
  theme(plot.margin = unit(c(5, 5, 5, 5), "mm"))
plot(chart1)
```
![chart1](https://user-images.githubusercontent.com/7143861/34580451-ee602164-f141-11e7-8770-9abd33c45d97.png)

```
chart2 <- starwars %>%
  select(name, mass) %>%
  filter(name == "Jabba Desilijic Tiure") %>%
  ggplot(aes(x = name, y = mass)) +
  geom_bar(stat = "identity",
           fill = "#767676",
           colour = "grey30") +
  labs(xlab("")) +
  labs(ylab("Mass")) +
  coord_flip() +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_continuous(
    expand = c(0, 0),
    breaks = seq(0, 1400, 200),
    limits = c(0, 1400)
  ) +
  theme_grey() +
  theme(plot.margin = unit(c(5, 5, 5, 5), "mm"))
plot(chart2)
```
![chart2](https://user-images.githubusercontent.com/7143861/34580466-01cf2826-f142-11e7-8a0b-f946d597ce60.png)

When the charts are combined the axis tick placement for the first plot is shifted:
```
chart1 + chart2 + plot_layout(ncol = 1, heights = c(4, 1))
```
![charts](https://user-images.githubusercontent.com/7143861/34580483-109d82ee-f142-11e7-8547-f6c83b5e2ed7.png)

**Comment by thomasp85** [comment]
Thanks - same issue

**Comment by teng-gao** [comment]
I have the same issue of shifted axis when aligning a facet_grid with a facet_wrap
![image](https://user-images.githubusercontent.com/13375875/61977058-646b2780-afbb-11e9-8080-84cb5eda9f59.png)
