### ISSUE TITLE
Unexpected plot widths on hierarchical assembly

### ISSUE THREAD

**Issue by mschubert** [thomasp85/patchwork#128]
I'd like to assemble my plots in multiple steps. However, this changes the widths of the panels in an (for me) unexpected way [using current github HEAD]:

```r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))

p = p1 | p2
p | p + plot_layout(widths=c(1,1))
# same behavior with { p1 | p2 } | { p1 | p2 }

# p1 | p2 | p1 | p2 produces desired widths
# { p1 + p2 } | { p1 + p2 } works too
```

I would expect the following:

![image](https://user-images.githubusercontent.com/442360/69622028-78de3000-1040-11ea-857e-d1d1e7bc3b3b.png)

However, I get this:

![image](https://user-images.githubusercontent.com/442360/69622055-84c9f200-1040-11ea-9ad9-b2f70aef1aa9.png)

Is it intentional that the widths assigned to the panels are 1/1/0.5/0.5?

**Comment by thomasp85** [comment]
I agree that this is somewhat unexpected behaviour. What is happening is that plots will always be added to the current patchwork. As p is a patchwork, doing `p | p` will nest p besides the the other panels in p. In the end you have a patchwork with 3 columns, and the rightmost column is occupied by a nested patchwork.

This is the exact use case for `-`, which will put the left and right side on the same nesting level:

```r
p - p
```
![image](https://user-images.githubusercontent.com/1775316/69623171-a7f5a100-1042-11ea-821a-6e1e6bf75db8.png)

**Comment by llrs** [comment]
@thomasp85 Perhaps this could be mentioned in the Getting Started vignette (but I found it clearly explained on the `-` [help page](https://patchwork.data-imaginist.com/reference/plot_arithmetic.html))

**Comment by thomasp85** [comment]
I think this is a bit too niche for the getting started guide, but I forgot about it in the assembly guide and will add it there

**Comment by thomasp85** [comment]
https://patchwork.data-imaginist.com/articles/guides/assembly.html#nesting-the-left-hand-side
