### ISSUE TITLE
Possible regression: invalid 'layout.pos.row'

### ISSUE THREAD

**Issue by lindeloev** [thomasp85/patchwork#132]
I am using patchwork to arrange `bayesplot` plots. I'm attaching one such plot, [plot1.zip](https://github.com/thomasp85/patchwork/files/3908812/plot1.zip), which is a `facet_wrap`'ed plot using `ncol = 1`. Use `load("plot1.RData")` to load it.

In the "old" `patchwork` GitHub version (unsure how old, unfortunately, but between two months and a year), this would make two columns as expected:

```r
    plot1 + plot1 
```

However, with the CRAN version 1.0.0, it yields the following error:

```r
Error in grid.Call.graphics(C_setviewport, vp, TRUE) : 
  invalid 'layout.pos.row'
```

I'm just including one plot here, but the issue exists with different `bayesplot` plots as well. `patchwork` 1.0.0 works just fine with "home-made" faceted plots, so it's possible that this is `bayesplot` not conforming to standards. The `grid` package seems to be the origin of the `layout.pos.row` variable.

I don't know if it's of any use, but the following does not raise an error for `nrow >= 2`. Unfortunately, the resulting plot is "stacked" and the y-axis is inverted:

```r
plot1 + plot1 + plot_layout(ncol = 2, nrow = 7)
```

![image](https://user-images.githubusercontent.com/1439417/69921061-2a40f380-148f-11ea-822a-6a28f12dfc6a.png)

**Comment by thomasp85** [comment]
Can you share the code used to generate the plot? Somehow the structure of the plot doesn't conform with the expectations...

**Comment by lindeloev** [comment]
Absolutely. I attach the data, [plot_data.zip](https://github.com/thomasp85/patchwork/files/3910453/plot_data.zip) which is an `mcmc.list`. You can make the plot using

    plot1 = bayesplot::mcmc_dens_overlay(plot_data, facet_args = list(ncol = 1))

The issue seems to be general for many (all?)

    bayesplot::mcmc_[[type]](plot_data)

i.e., without `facet_args` too. E.g., `mcmc_trace()`, `mcmc_dens()`, etc.

**Comment by thomasp85** [comment]
weirdly this is an issue with the bayesplot theme...

```r
plot1 + plot1 & theme_gray()
```

works

**Comment by lindeloev** [comment]
Confirmed! This is good enough for me to get on. I considered making some changes to that theme anyway, so this is a good excuse.

**Comment by thomasp85** [comment]
I've identified this to be due to `strip.placement = 'outside'` — no idea when that started to not work

**Comment by lindeloev** [comment]
Great. For future googlers, this is a simple fix/workaround for now:

    plot1 + plot1 & theme(strip.placement = NULL)

**Comment by mdozmorov** [comment]
Googling for `Error in grid.Call.graphics(C_setviewport, vp, TRUE) : invalid 'layout.pos.col'` brought me to this issue. `p1 + p2 & theme(strip.placement = NULL)` doesn't eliminate it. Versions of `grid` 4.1.0, `gridExtra` 2.3, `patchwork` 1.1.
