### ISSUE TITLE
wrap_elements with dendrogram

### ISSUE THREAD

**Issue by vnijs** [thomasp85/patchwork#134]
patchwork looks amazing. Great work! I also just noticed the option to combine base plots in a grid of plots. Having some trouble however. See example below 

Not sure if this is related, but inside a shiny app I'm getting an error about an object to be plotted that it can't find for some reason.

```
hc <- as.dendrogram(x$hc_out)
plot_list[["dendro"]] <- patchwork::wrap_elements(~ plot(hc))
patchwork::wrap_plots(plot_list, ncol = 1)

Error: object 'hc' not found
```

```
library(ggplot2)
library(patchwork)

hc <- hclust(dist(USArrests), "ave")
plot(hc)

plot_list <- list()
plot_list[[1]] <- ggplot(mtcars) +  geom_point(aes(mpg, disp)) 
plot_list[[2]] <- wrap_elements(~ plot(hc), clip = FALSE)
patchwork::wrap_plots(plot_list, ncol = 1)

Warning messages:
1: In FUN(X[[i]], ...) :
  unsupported operation on the graphics display list
2: In FUN(X[[i]], ...) :
  unsupported operation on the graphics display lisr
```

**Comment by thomasp85** [comment]
does it work outside shiny?

**Comment by thomasp85** [comment]
This seems to be a bug in [gridGraphics ](https://github.com/pmur002/gridgraphics) package which powers the base graphic support. Can I get you to open an issue there?

**Comment by vnijs** [comment]
Sure ... but what would be the message? If I report the issue above I assume they will push it back to patchwork.

**Comment by thomasp85** [comment]
something like (but verify that it leads to the same issue):

```r
hc <- hclust(dist(USArrests), "ave")
gridGraphics::grid.echo(function() plot(hc))
```

**Comment by vnijs** [comment]
@pmur002 fixed the issue in the development version of gridGraphics (0.5.0). Thanks for the direction to get this resolved @thomasp85 !
