### ISSUE TITLE
unexpected behavior when collecting legends/guides

### ISSUE THREAD

**Issue by zoowalk** [thomasp85/patchwork#135]
First of all, many thanks for all the efforts you put into this. Tremendously helpful package.

In the example below, I would expect the legends to be merged. Or is it the case, that legends have to be identical in order to be merged/collected? Many thanks! 

I ignore here the possibility of a simple facet_wrap.

``` r
library(tidyverse)
library(patchwork)


my_plots <- mtcars %>% 
  mutate(large_cars=ifelse(disp>110, "large", "small")) %>% 
  mutate(cyl=as.factor(cyl)) %>% 
  group_split(large_cars) %>% 
  map(~ggplot(.)+
        geom_point(
          aes(x=wt,
              y=qsec,
              color=cyl))+
        labs(title=unique(.x$large_cars)))


patchwork::wrap_plots(my_plots)+
  plot_layout(guides="collect")
```

![](https://i.imgur.com/0e3qYYc.png)

<sup>Created on 2019-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
Yes - for now (and possibly forever, due to technical reasons) the guides have to be identical in their graphical representation in order to be merged
