### ISSUE TITLE
collect guides when legend.position="bottom"

### ISSUE THREAD

**Issue by schochastics** [thomasp85/patchwork#136]
I'd like to center a common legend below two plots (see reprex below). 
This does not seem to work atm (at least not how I thought it could work), and I somehow expect/fear that this is technically not possible?!?

``` r
library(tidyverse)
library(patchwork)

set.seed(17)
dat1 <- tibble(x = rep(1:5,2),
              y = sample(1:10,10,replace = T),
              grp = rep(c("A","B"),each=5))

dat2 <- tibble(x = rep(1:5,2),
              y = sample(1:10,10,replace = T),
              grp = rep(c("A","B"),each=5))


p1 <- ggplot(dat1,aes(x,y)) + geom_line(aes(col=grp))
p2 <- ggplot(dat2,aes(x,y)) + geom_line(aes(col=grp))

p1 + p2 + plot_layout(guides = "collect")
```

![](https://i.imgur.com/HoZkBDH.png)

``` r

p3 <- ggplot(dat1,aes(x,y)) + 
   geom_line(aes(col=grp)) + 
   theme(legend.position = "bottom")

p4 <- ggplot(dat2,aes(x,y)) + 
   geom_line(aes(col=grp)) + 
   theme(legend.position = "bottom")

p3 + p4 + plot_layout(guides = "collect")
```

![](https://i.imgur.com/iP7IqeL.png)

**Comment by thomasp85** [comment]
You just need to make sure that the theming of the patchwork has `legend.position = 'bottom'` as well. This can be done using either the `theme` argument in `plot_annotation()`, or by `&` a theme object to it which will apply the theme to both the patchwork as well as to all subplots:

```r
p1 + p2 + plot_layout(guides = "collect") & theme(legend.position = 'bottom')
```

**Comment by melissagwolf** [comment]
This helped so much.  If you write it as + theme instead of & theme, the legend position will not go where it is specified.

**Comment by MatthieuStigler** [comment]
Awesome! Might be worth emphasizing this point in the (great) online manual on `plot_layout`. As a newcomer, I came into the exact same issue. 

Thanks!

**Comment by valybionda** [comment]
is the manual position of the legend still not possible?

**Comment by melissagwolf** [comment]
Hi Thomas,

It seems like `guides=collect` might not be working anymore? I'm re-running the reprex from the first post and I'm getting the same legend twice.  However, the position is still working.

Thanks!

Melissa

**Comment by llrs** [comment]
Hi Melissa @melissagwolf,

Are you using R 4.0.0 ? This is a know bug #170 (Unless your session Information says something different)

Lluís

**Comment by melissagwolf** [comment]
Yep, using 4.0.0.  Thank you for the quick response!

**Comment by nahorp** [comment]
> This helped so much. If you write the code as `+ theme` instead of `& theme`, the legend position will not go where it is specified. The `&` is key.

Thank. you. so. much. *you are a godsend*

**Comment by valybionda** [comment]
> You just need to make sure that the theming of the patchwork has `legend.position = 'bottom'` as well. This can be done using either the `theme` argument in `plot_annotation()`, or by `&` a theme object to it which will apply the theme to both the patchwork as well as to all subplots:
> 
> ```r
> p1 + p2 + plot_layout(guides = "collect") & theme(legend.position = 'bottom')
> ```

What if I don't want to apply the theme to all the subplots?
In other words, I want to have the "collected" legend at the centre bottom of the first two plots, but not for the third one in the first line:
(((p1|p2) + plot_layout(guides = "collect") & theme(legend.position = "bottom"))|p2  + plot_layout(guides = "keep"))/(p1|p2) 

I cannot manage to have this working. any solution?

**Comment by krassowski** [comment]
> I cannot manage to have this working. any solution?

yup, this is pretty bad when including ggraph or circular visualisation which greatly benefit from `theme_void()` while other panels are using non-void themes. One thing I tried was manually specifying `guide_area()` but this did not work because the legend box was in always in vertical orientation (ignoring `legend.box='horizontal'`).

**Comment by OlivaresLD** [comment]
> What if I don't want to apply the theme to all the subplots? In other words, I want to have the "collected" legend at the centre bottom of the first two plots, but not for the third one in the first line: `(((p1|p2) + plot_layout(guides = "collect") & theme(legend.position = "bottom"))|p2 + plot_layout(guides = "keep"))/(p1|p2) `
> 
> I cannot manage to have this working. any solution?

@costavale In my case, I found two options, one not very fancy, but working and also a downgrading option. So, you can 

1) use **`plot_annotation()`** like this:

`p1 + p2 + plot_layout(ncol = 2, guides = "collect") +`
    `plot_annotation(theme = theme_minimal() +`
                      `theme(legend.position = "bottom"))`

or 

2) downgrade **ggplot2** from 4.x.x to __3.5.2__ and run again, this seems to fix the conflict with **patchwork**
