### ISSUE TITLE
creating a matrix of plots when the number is unknown in advance

### ISSUE THREAD

**Issue by vnijs** [thomasp85/patchwork#139]
I'm using patchwork to create a plot similar to the first screenshot shown below. It is working ok  so far (see second screenshot) but there are two issues: 

1. How to create the set of areas to plot programmatically

Starting with the diagonal elements I had hoped to create layout specs using something like the below:

```
design <- sapply(seq_along(mtcars), function(x) area(x, x))
```

However, this creates a vector, rather than the list of class "patch_area" that I need. Any suggestions? I tried the number-string alternative but I'm not sure if that works when numbers go above 9.

2. How to speed up rendering?

The Base-R version using `pairs` is quite a bit faster. Any suggestions on how render speed could be improved?  

Base-R version using `pairs`:

![image](https://user-images.githubusercontent.com/2998956/70207394-84d08e80-16df-11ea-9f0a-81fe83c77ec1.png)

ggplot + patchwork version: 

![image](https://user-images.githubusercontent.com/2998956/70212681-9b311700-16ec-11ea-822b-5bba578f70fb.png)

FYI: Correlations will calculated using polycor::hetcor in the final version. Here I just converted all columns to numeric however.

**Comment by thomasp85** [comment]
1) Never ever use sappy for anything ever
2) Speed is an issue, due to all the gymnastics patchwork has to do to align plots. If you are going to wrap this into a function I'd suggest looking into [`geforce::facet_matrix()`](https://ggforce.data-imaginist.com/reference/facet_matrix.html) instead

**Comment by thomasp85** [comment]
1. you can either use `do.call(c, lapply(...))` or simply pass in vectors to `area()`, e.g. `area(c(1,2), c(1,1))` is valid but undocumented

**Comment by vnijs** [comment]
Thanks @thomasp85. You make some seriously cool stuff! :)
