### ISSUE TITLE
Better layouts with 'ggraph'

### ISSUE THREAD

**Issue by jhrcook** [thomasp85/patchwork#142]
Hello,

The alignment of 'ggraph' objects works as designed, but perhaps there could be an option for the `ggraph` object to not align with the panels of the other plots? Below is an example that shows how a lot of space remains empty that I would like to have the network fill.

```r
require(schrute )
library(tidygraph)
library(ggraph)
library(patchwork)
library(tidyverse)

set.seed(123)

gr <- tidygraph::play_forestfire(10, 0.5)
gr_plot <- ggraph(gr) +
    geom_edge_link() +
    geom_node_point() +
    theme_graph() +
    labs(tag = "A")

bar_plot <- tibble(
        x = str_sub(sample(schrute::theoffice$text_w_direction, 5), 1, 100),
        y = runif(5)
    ) %>% 
    ggplot(aes(x = x, y = y)) +
    geom_col() +
    coord_flip() +
    theme_bw() +
    labs(tag = "B")

gr_plot / bar_plot
```
![patchwork_issue_plot1](https://user-images.githubusercontent.com/39419448/71329319-77d1de80-24d8-11ea-8305-fa7b0b2cc415.jpeg)
My current work around is to add an empty spacer and make its width very small. The problem is then that the tags are mis-aligned. An example is shown below.

```r
gr_plot / (plot_spacer() + bar_plot + plot_layout(widths = c(1, 1000)))
```
![patchwork_issue_plot2](https://user-images.githubusercontent.com/39419448/71329320-7b656580-24d8-11ea-8424-7b497f921944.jpeg)

Let me know if you need any further examples or explanation of the problem.

Thank you!

**Comment by thomasp85** [comment]
I don’t find it a compelling argument. There are many situations where you’d want network plots to be aligned, so treating them specially will only lead to frustration. You can put in `wrap_elements()` to turn off alignment if you need to

**Comment by jhrcook** [comment]
I didn't realize that that was an option, so thank you for pointing it out. I implemented it in the above example and the tags were still mis-aligned. Do you know of a way of aligning the tags without manually adjusting the `plot.tag` margin in `theme()`?
