### ISSUE TITLE
Centering `plot_annotation`

### ISSUE THREAD

**Issue by jonspring** [thomasp85/patchwork#143]
Is there a way to center titles created with plot_annotation()?

I expected this to have one title centered on the panel and one centered across the whole plot, but the `hjust` parameter did not seem to be active for `plot_annotation`. Perhaps I should be using different syntax?

(Related to https://github.com/thomasp85/patchwork/issues/43 and https://stackoverflow.com/questions/59482694/center-legend-in-ggplot2-relative-to-image)

```
library(ggplot2)
library(patchwork)
ggplot(midwest, aes(area, poptotal)) +
  geom_point() +
  labs(title = "plot-centered title") +
  theme(plot.title = element_text(hjust = 0.5)) +
  plot_annotation(title = "image-centered title") +
  theme(plot.title = element_text(hjust = 0.5))
```

![image](https://user-images.githubusercontent.com/18709859/71456674-69d9c300-274f-11ea-93ce-40c89520501e.png)

**Comment by dgruenew** [comment]
I believe this can already be accomplished by using the `theme` argument in  `patchwork::plot_annotation()`:

```
library(ggplot2)
library(patchwork)
ggplot(midwest, aes(area, poptotal)) +
  geom_point() +
  labs(title = "plot-centered title") +
  theme(plot.title = element_text(hjust = 0.5)) +
  plot_annotation(
    title = "image-centered title",
    theme = theme(plot.title = element_text(hjust = 0.5))
  )
```
![image](https://user-images.githubusercontent.com/20053023/74268208-19053600-4ccd-11ea-87b5-1fc880740708.png)

**Comment by jonspring** [comment]
Thanks, that looks good.
