### ISSUE TITLE
Error when faceted plot has manually-placed legend

### ISSUE THREAD

**Issue by patrickbarks** [thomasp85/patchwork#144]
I'm getting an error when I try to use patchwork on a faceted ggplot with a manually-placed legend (i.e. `theme(legend.position = ...)`). Here's a reprex.

``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars, aes(mpg, disp, col = as.factor(gear))) +
  geom_point() +
  facet_wrap(~ cyl) +
  theme(legend.position = c(0.1, 0.7))

# plot by itself
p1
```

![](https://i.imgur.com/6OQN9gs.png)

``` r

# plot within patchwork
p1 / p1
#> Error in FUN(X[[i]], ...): subscript out of bounds
wrap_plots(p1, p1)
#> Error in FUN(X[[i]], ...): subscript out of bounds
```
<sup>Created on 2020-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It works fine when I remove the `facet_wrap()`, or the `theme(legend.position = ...)` line. Something about both of them together seems to cause an issue.

**Comment by avigotsky** [comment]
I am having the same issue. Any help or workarounds would be greatly appreciated!
