### ISSUE TITLE
Display layout grid 

### ISSUE THREAD

**Issue by Maschette** [thomasp85/patchwork#152]
When using the design option in plot_layout() it would be awesome if there was an option to display the design grid on the plot to assist in working out the alignment.

```
layout <- c(area(t = 1, l = 1, b = 100, r = 100),
area(t = 79, l = 31, b = 114, r = 69),
area(t = 79, l = 70, b = 114, r = 85))

a + b+ c + plot_layout(design = layout )
```

**Comment by thomasp85** [comment]
There is a plot method for areas as described in the help file https://patchwork.data-imaginist.com/reference/area.html
