### ISSUE TITLE
Plots not aligned

### ISSUE THREAD

**Issue by hbeale** [thomasp85/patchwork#153]
These plots are not aligned correctly. I thought it might be related to #22, but that's fixed. Thanks!
```
p <- ggplot(mtcars,
                    aes(y=mpg, x=1)) + 
  geom_boxplot() +
  coord_flip()

hist_plot <- ggplot(mtcars) + geom_histogram(aes(x=mpg, fill = cyl))

p + hist_plot +  plot_layout(heights = c(1, 6), ncol=1) 
```

**Comment by steveharoz** [comment]
Can you explain what about it isn't aligned? Here's the result I got:
<img width="717" alt="Screen Shot 2020-02-26 at 1 05 29 PM" src="https://user-images.githubusercontent.com/2257540/75343711-52c36880-5899-11ea-8992-8656c5a4705a.png">

**Comment by thomasp85** [comment]
If you are referring to the two plots not sharing the same x-axis, then this is not a feature of patchwork at the moment. It will not modify the scales of two different plots for you.

**Comment by hbeale** [comment]
Yes I was referring to sharing the x-axis. Thanks for the clarification.
