### ISSUE TITLE
plotting tables as tableGrob doesn't recognize object

### ISSUE THREAD

**Issue by rbutleriii** [thomasp85/patchwork#155]
Edit: reproducible issue
I am trying to plot data.tables in my plot as in [this example](https://cmdlinetips.com/2020/01/tips-to-combine-multiple-ggplots-using-patchwork) but there seems to be an issue recognizing the tableGrobs:
```
library(ggplot2)
library(patchwork)
library(gridExtra)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
test <- data.table("index"=rep(letters[1:10],100),"var1"=rnorm(1000,0,1))
tableGrob(head(test)) + p1 + tableGrob(tail(test))
```
delivers the error message `Error in tableGrob(head(test)) + p1 + tableGrob(tail(test)) :
  non-numeric argument to binary operator`

**Comment by rjpat** [comment]
The issue is that patchwork expects the first element to be a ggplot one. `wrap_elements()` can be used in order to convert the table to an appropriate element
`wrap_elements(tableGrob(head(test))) + p1 + tableGrob(tail(test))`

**Comment by thomasp85** [comment]
This is an unfortunate limitation of the S3 dispatch in R. I would love to fix it, or at least provide a better error message, but that is not possible at the moment
