### ISSUE TITLE
aligning ranges in layout

### ISSUE THREAD

**Issue by yonicd** [thomasp85/patchwork#166]
Many times I find that creating the plots independently in different geoms the continuous axes are not aligned. Is there an efficient way to align axis ranges of plots in a layout. There is not a great way to retrieve axes limits/ranges from gg objects given that the plot only renders on print or in `ggplot2::ggplot_build` which basically captures the printed object (see code below).

This solution is very inefficient larger gg objects since you would need to build each plot to ascertain the ranges before actually rendering the layout, so you are rendering the layout multiple times to achieve synchronized axes limits/ranges.

Is there any other way to do this, that would not invoke the whole plot to be rendered? 

ref: https://github.com/mjskay/tidybayes/issues/246

```r
axis_rng <- function(p,axis = c('x','y')) {
  
  g <- ggplot2::ggplot_build(p)
  
  axis <- match.arg(axis,several.ok = TRUE)
  
  names(axis) <- axis
  
  lapply(axis,function(x){
    g$layout[[sprintf('panel_scales_%s',x)]][[1]]$range$range   
  })
  
}
```

**Comment by thomasp85** [comment]
My general approach to this is simply to add a common scale to all plots using `&`. Of course, you'd need to know in advance what range you'd want but that is the best right now

I'll not rule out that something automatic will pop up in the future, but I won't promise it as well
