### ISSUE TITLE
feature request: ncol, nrow rollover

### ISSUE THREAD

**Issue by Maschette** [thomasp85/patchwork#173]
It would be super handy if there was a way when using `a+b+c+plot_layout(nrow=2, ncol=2)` for it to insert an empty plot into the 4th spot. Or just as useful if you had `a+b+c+plot_layout(nrow=2, ncol=1)` for it to return two plots one with a and b and the next with c and blank. 

The main thing we use this for is we may have 35 plots and want to create a pdf with 4 per page it makes it hard to automate currently. 

Thanks!

**Comment by llrs** [comment]
You could use this if you only have three plots but want to use 4 spaces:

```
layout <- "
AB
C#"
p1 + p2 + p3 + 
  plot_layout(design = layout)
```

From the [Controlling the layout vignette](https://patchwork.data-imaginist.com/articles/guides/layout.html#moving-beyond-the-grid)

**Comment by thomasp85** [comment]
Just to understand it correctly, You want to insert an actual plot without any layers in it in the space left?

**Comment by Maschette** [comment]
That would be one option yes, the aim would to be just have white space where there should be a 4th plot or in the case of a+b+c+d+plot_layout(nrow=2, ncol=2) if d was missing it just puts a white space rather than throw an error. Similar to how mfcol/mfrow output in the same situation: 

``` r

library(SOmap)
#> Loading required package: raster
#> Loading required package: sp

par(mfcol=c(2,2))
SOmap()
SOmap()
SOmap()
```

![](https://i.imgur.com/8tJ4zJt.png)

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
But isn’t that the current behaviour?

**Comment by Maschette** [comment]
Sorry that is a bad example as is has less plots than the nrow/ncol combo. You are right, for the first part of the issue that is what is does (I was confused) but the second half about returning multiple images when you have more than the nrow/ncol combo is still true. 
for example using weather data when we wanted to have a 2 x 2 plot image for 7 cities we ended up having to use split and then map which is slow. 

``` r

library(tidyverse)
library(bomrang)
library(patchwork)
Sites <- c("Hobart (ELLERSLIE ROAD)","Geelong","SYDNEY","Brisbane", "Mount Wellington","Adelaide","Melbourne")

AllDat <- suppressWarnings(purrr::map_dfr(Sites,get_current_weather))

plot_Each_site <- function(dat){
    ggplot(dat,mapping = aes(x = local_date_time_full, y = air_temp ))+
        geom_line(size = 1.1)
}

plots <- AllDat %>% select(local_date_time_full, full_name,air_temp) %>% 
    nest(data = c( local_date_time_full,air_temp)) %>% 
    rowwise() %>% 
    mutate(eventplot = list(plot_Each_site(data  )))

plots<- plots %>%  ungroup()%>% mutate(grp =  gl(n = ceiling(n()/4),k = 4, length = n()))

plts_spt <- plots %>% split(.,plots$grp)

wrapped_plots <- map(plts_spt, ~wrap_plots(.x$eventplot, ncol = 2, nrow = 2))
wrapped_plots
#> $`1`
```

![](https://i.imgur.com/YcFdioS.png)

    #> 
    #> $`2`

![](https://i.imgur.com/KMKJVDt.png)

An ideal situation would be ton not have to call split and map and be able to get the same result with just calling: 

``` r
wrap_plots(plots$eventplot, ncol = 2, nrow = 2)
#> Error: The given dimensions cannot hold all panels. Please increase `ncol` or `nrow`
```

![](https://i.imgur.com/mSOiZUt.png)

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
That is not going to happen. I don’t want the return type to be contingent on some combination of the number of plots, brow, and ncol. It is fairly easy to split a list of plot objects and call `wrap_plots()` on it yourself
