### ISSUE TITLE
patchworks for R 4.0.0

### ISSUE THREAD

**Issue by veronicar239** [thomasp85/patchwork#174]
Hello,
I recently updated to R version 4.0.0 (for the necessity of other packages), and have now received a warning/error message:

package ‘patchworks’ is not available (for R version 4.0.0)

I was wondering if there was a plan for patchworks to soon be compatible with the new R version 4.0.0?

Cheers

**Comment by rmflight** [comment]
This seems unlikely. CRAN is showing OK checks on all the current flavors of R, which for release is the current version of 4.0. Are you using a mirror that hasn't updated properly?

https://cran.r-project.org/web/checks/check_results_patchwork.html

**Comment by teng-gao** [comment]
+1 My R is 3.6.1

**Comment by mcanouil** [comment]
Hi,

You should try to install with the right name, i.e., without the “s”.
