### ISSUE TITLE
strange problem under a fixed aspect coordinates

### ISSUE THREAD

**Issue by houyunhuang** [thomasp85/patchwork#175]
Thanks for developing such a nice package. 

There's a very strange problem under a  fixed aspect coordinates,  and here's a simple example to reproduce the problem.

```
df1 <- data.frame(x = 1:10, y = rnorm(10))
df2 <- expand.grid(x = 1:10, y = 1:10)
df2$value <- rnorm(100)
df3 <- data.frame(x = runif(10, 0, 3), y = 1:10)

library(ggplot2)
library(patchwork)
p1 <- ggplot(df1, aes(x, y)) +
  geom_point() +
  scale_x_continuous(limits = c(0.5, 10.5), expand = c(0, 0)) +
  coord_fixed()

p2 <- ggplot(df2, aes(x, y, fill = value)) +
  geom_tile() +
  scale_x_continuous(limits = c(0.5, 10.5), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0.5, 10.5), expand = c(0, 0)) +
  coord_fixed()

p3 <- ggplot(df3, aes(x, y)) +
  geom_col() +
  scale_x_reverse() +
  scale_y_continuous(limits = c(0.5, 10.5), expand = c(0, 0)) +
  coord_fixed()
```

```
plot_spacer() + p1 + p3 + p2 +
  plot_layout(nrow = 2, byrow = TRUE, guides = "collect")
```
![unnamed-chunk-1-1](https://user-images.githubusercontent.com/11271278/81489804-b95afe80-92ac-11ea-967b-c459e0e296e1.png)

```
p1 + plot_spacer() + p2 + p3 +
  plot_layout(nrow = 2, byrow = TRUE, guides = "collect")
```
![unnamed-chunk-1-2](https://user-images.githubusercontent.com/11271278/81489819-d7286380-92ac-11ea-99a1-8a290ed9a25c.png)

```
p3 + p2 + plot_spacer() + p1 +
  plot_layout(nrow = 2, byrow = TRUE, guides = "collect")
```
![unnamed-chunk-1-3](https://user-images.githubusercontent.com/11271278/81489827-f6bf8c00-92ac-11ea-8e32-96c1fb14eb9e.png)

```
p2 + p3 + p1 + plot_spacer() +
  plot_layout(nrow = 2, byrow = TRUE, guides = "collect")
```
![unnamed-chunk-1-4](https://user-images.githubusercontent.com/11271278/81489836-135bc400-92ad-11ea-999f-772da2eebad6.png)

**Comment by thomasp85** [comment]
There is unfortunately quite a lot of heuristics going on to figure out space optimisation with multiple fixed aspect plots, so the order of the plots does have an influence. I don't think I can come up with a reasonable solution since there are quite a number of ill-defined issues when multiple fixed aspect plots share rows and columns simultaneously.

All that being said I think I've fixed this particular inconsistency
