### ISSUE TITLE
More complete "current plot" interface?

### ISSUE THREAD

**Issue by Shians** [thomasp85/patchwork#176]
I think it's a really cool feature to be able to add additional elements to a patchwork and have it be added to one of the plots, this justifies "-" operator to add to the left and make the left plot the "current plot" for adding geoms and such.

However I'm in a situation where I have a marginal plot on the bottom, and would like my top plot to be the "current plot", and as far as I can tell there is no operator for that. I propose that a series of verb functions be added to complete the API that look something like

* `add_top(p1, p2)`
* `add_bottom(p1, p2)`
* `add_left(p1, p2)`
* `add_right(p1, p2)`

possibly with the interface `add_*(p1, p2, focus = TRUE)` to choose whether or not the latest plot is the plot in focus. I don't know how difficult this would be to implement but I imagine you keep a list of ggplots somewhere and it should be possible to keep an index variable tracking which plot is in focus.

**Comment by thomasp85** [comment]
It is already possible to do this using indexing. `p[[1]] <- p[[1]] + theme_bw()` will change the theme of the first plot in the patchwork. Using top, left, etc as qualifiers are not really possible as the layout is not always so simple

**Comment by Shians** [comment]
Am I misunderstanding the point of "-"? It sounds like it exists so a plot can be added to the left and become the plot in focus, so `p1 - p2` isn't just equivalent to `p2 + p1`. There does not appear to be an equivalent operation when the layout is `p1 / p2`, the bottom plot will always hold focus.

It seems like an incomplete interface to allow adding ggplot elements directly to a patchwork, but only allow control of what plot is in focus in a limited way. Perhaps there can be a `set_focus_plot(patchwork, i)` interface? Otherwise I think it would make sense to discourage/disallow adding elements to whole patchworks and make the indexing the canonical method for adding elements.

**Comment by thomasp85** [comment]
The point of `-` is to nest the left hand side before adding the right hand side. It has nothing to do with focus as such
