### ISSUE TITLE
Manual position of collected guides

### ISSUE THREAD

**Issue by valybionda** [thomasp85/patchwork#177]
I would like to be able to manually decide the position of the legend(s).
In the case of collected guides, and with a defined design it will be very useful to be able to manually put the legend in a blank space btw figures.

**Comment by thomasp85** [comment]
Have a look at `guide_area()` 🙂

**Comment by valybionda** [comment]
Thank you! (....and what about the justification of the collected guides? thk)

**Comment by thomasp85** [comment]
These can be set in the patchwork theme

**Comment by MokeEire** [comment]
Is there a way to position the collected guides inside the plot area of one panel?  The following naive attempt did not work:

```
p1 + p2 + 
    inset_element(guide_area(), left = 0.6, bottom = 0.6, right = 1, top = 1) +
    plot_layout(guides = "collect")
```

The way I was able to get the result I wanted was to set `legend.position = "none"` on the left panel and `legend.position = c(.15, .9)` on the right panel.

![image](https://user-images.githubusercontent.com/19700454/100010644-6ac30c80-2d85-11eb-92e8-95e53adf4624.png)

**Comment by jarbet** [comment]
I case anyone else is wondering, `guide_area` can also be used with `wrap_plots`:

```
suppressPackageStartupMessages({
    library(ggplot2)
    library(patchwork)
})
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp, colour = factor(gear)))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_bar(aes(gear)) + facet_wrap(~cyl)

# Using guide_area() you can also designate an empty area for this
p1 + p2 + p3 + guide_area() + plot_layout(guides = 'collect')

### using wrap_plots:
plot_list <- list(
    p1,
    p2,
    p3,
    guide_area()
)
patchwork::wrap_plots(
    plot_list,
    ncol = 2,
    guides = 'collect'
)
```

<img width="1344" height="960" alt="Image" src="https://github.com/user-attachments/assets/775a6a70-fc0d-4208-8009-0d1715ae9b6a" />
