### ISSUE TITLE
Legend Patchwork

### ISSUE THREAD

**Issue by nitrato** [thomasp85/patchwork#179]
Hi Thomas,
I have started using patchwork thanks to your webminar on ggplot2 a few weeks back. I find it very handy and elegant, thanks for that.
I am writing this cause I am getting the attached plot by running the following code:
p1 + p2 + p3 + plot_layout(nrow = 2, guides = "collect") 
Is there a way so that the legend regarding the first two plots stays collected on the first row and then the second and third legends, which concern the third plot, stick to the that plot on the second row?
Thanks for your help.
Best,
David Rengel

[variable.genes_crag.lipm.pdf](https://github.com/thomasp85/patchwork/files/4630126/variable.genes_crag.lipm.pdf)

**Comment by thomasp85** [comment]
I don't think this is currently possible if you want to maintain all the plots in the same nesting level. You may get what you want if you combine two patchworks with each of their guides collected
