### ISSUE TITLE
Black line boxes around plots

### ISSUE THREAD

**Issue by WillEddy** [thomasp85/patchwork#182]
First of all, Thomas, thank you for creating such an elegant solution.

So I've been trying to export a plot matrix to png with a transparent background. For a while, I was just getting a white background, but I found a way to get transparency. Now, it's giving me these weird boxes around the plots, and I can not for the life of me figure out why. Have I accidentally triggered some function in patchwork()? Here's an image of what's happening. I have included reproducible example code at the end; it's a little sloppy but it has what I'm really using in there for the most part.

![matrix_example](https://user-images.githubusercontent.com/38814826/82097886-cc693680-96d1-11ea-8a09-f1f24e80486f.png)

if (!require('tidyverse')) install.packages('tidyverse'); library('tidyr')
if (!require('ggplot2')) install.packages('ggplot2'); library('ggplot2')
if (!require('ggthemes')) install.packages('ggthemes'); library('ggthemes')
if (!require('patchwork')) install.packages('patchwork'); library('patchwork')

#######################################################
# Generate data on a hypothetical individual with means
#######################################################
one_person <- 
  data.frame(Category = c("perf_driven"),
             old_average = sample(800:900, 1, replace = TRUE),                         
             self_eval = sample(700:800, 1, replace = TRUE),
             mgr_eval = sample(700:800, 1, replace = TRUE),
             peer_eval = sample(700:800, 1, replace = TRUE)
  )

################################################
# Horizontal bar plots
################################################

horizontal_bars <- function(data_object,metric) { 
  .e<-pivot_longer(data_object, -Category, names_to = "Survey", values_to = "Score")

  .e <- .e %>%
    subset(Category==metric)
    
  ggplot(.e,aes(Category, Score, fill = Survey)) +
    geom_bar(stat="identity", position = position_dodge2(reverse = TRUE, padding=0), width = .5) +
    coord_flip() +
    geom_text(aes(label=Score), position=position_dodge2(reverse = TRUE, width=.5), hjust=1.1, size = 2.5) +
    #geom_text(aes(label = Score, hjust=0)) +
    theme_minimal() +
    theme(
      panel.border = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks.x = element_blank(),
      axis.ticks.y = element_blank(),
      legend.position = "none",
      panel.background = element_blank(),
      plot.background = element_rect(fill = "transparent",colour = NA)
    )
  
}

################################################
# Theme for transparency
################################################

transparent_bg_theme =
  theme(
    # panel.border = element_blank(),
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent")
    
  )

##################################################
# Create plots and plot matrix (the real version has all different plots)
##################################################

a1 <- horizontal_bars(one_person,"perf_driven")

widths = c(.8,.8)
height = .5
plot_matrix = a1 + a1 + 
  a1 + a1 +
  a1 + a1 +
  a1 + a1 +
  a1 + a1
  
plot_matrix = plot_matrix + plot_layout(ncol = 2, nrow = 5, widths = widths, heights = height)
plot_matrix <- plot_matrix & transparent_bg_theme

##################################################
# Output png file
##################################################

ggsave('matrix_example.png', plot = plot_matrix, height=7, width=2.5, units="in", dpi="print", type="cairo", bg = 'transparent')

**Comment by thomasp85** [comment]
I think you may be missing a `colour = NA` for the `panel.background`

**Comment by WillEddy** [comment]
Thank you Thomas! I had missed this detail. You really saved the day. In case anyone else has this issue in the future, the problem was in this section (fixed below):

################################################
Theme for transparency

################################################

transparent_bg_theme =
theme(
# panel.border = element_blank(),
panel.background = element_rect(fill = "transparent",color = NA), # bg of the panel
plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
legend.background = element_rect(fill = "transparent"), # get rid of legend bg
legend.box.background = element_rect(fill = "transparent")

)

##################################################
