### ISSUE TITLE
Actual plotting size changes after assembly

### ISSUE THREAD

**Issue by jlduan** [thomasp85/patchwork#183]
Hi, thanks for developing this fantastic package. I find it is very useful.

I noticed that the actual plotting size changes after assembly. I really like to control precisely the size of the plots no matter plotting them individually or together.

For example, I have double the width of the assembled plot.
 
Individual plot:
[Rplot_embedding_expr_ENSG00000164736_SOX17.pdf](https://github.com/thomasp85/patchwork/files/4659931/Rplot_embedding_expr_ENSG00000164736_SOX17.pdf)

Assembly plot:
[Rplot_embedding_expr_ENSG00000164736_SOX17_2.pdf](https://github.com/thomasp85/patchwork/files/4659934/Rplot_embedding_expr_ENSG00000164736_SOX17_2.pdf)

There are extra spaces around the assembled plot. Please look at the positions of the color bar in these two plots. They are not at the same location.

Is there a way to keep the assembled plot exactly the same as if they were plotted individually?

Thanks.

**Comment by llrs** [comment]
I don't understand which space you want to remove. To me the color bar seems to be at the same place. 

Or do you mean keeping the final size of the plot? Then this is due when you save it. One is 106 × 38 mm, while the other is a A9, Landscape (53 × 38 mm). When you save it with `ggsave`, set the desired size for both the single plot and the assembly to be the same.

**Comment by jlduan** [comment]
@llrs 

Thanks for the reply. They are clearly different.

Could you take a closer look at the positions of colorbars relative to the two clusters on the left (the heights are different). Maybe you can open them in AI to measure the height of the actual **dots**. They are not the same.

All three plots are the same (same plot command).I saved the first one using ggsave with 53 × 38 mm. I assembled the same plots twice and ggsaved it with 106 × 38 mm. They should be the same. But they are not.

**Comment by thomasp85** [comment]
Patchwork adds an additional margin around everything. Setting this to 0 with the `theme` argument in `plot_annotation()` will probably fix your issue. Otherwise, feel free to reopen and provide a minimal example — then I'll look into it in more detail
