### ISSUE TITLE
ggExtra object type can't be assembly

### ISSUE THREAD

**Issue by camilogarciabotero** [thomasp85/patchwork#184]
Hi all,

I created a couple of marginal plots with the `ggExtra` package and when I was going to use `patchwork`to assembly them I got the following error:

> non-numeric argument to binary operator

So, when looking at the obtect type it says `ggExtraPlot` and I wonder if this is a not supported object type for `patchwork` and if there is any alternative to get through...

Regards
Camilo.

**Comment by thomasp85** [comment]
Short answer: No. I don't plan to support every weird type of plotting output. I don't know enough about the innards of ggExtra but if you can convert it to a gtable then you can work with it in patchwork (but you'll loose the alignment)
