### ISSUE TITLE
Plots Not stretching to fill Plot Layout spec

### ISSUE THREAD

**Issue by bhive01** [thomasp85/patchwork#185]
I have a complex plot that is plotting the qqplot outputs from a model next to a plot with ANOVA/Tukey's output for mean comparisons. When I plot it out with the following spec the qqplots do not stretch properly. The upper plots title and lower plots x-axis title only move. 
![USWS_Soy-15G_V1_SDW](https://user-images.githubusercontent.com/394973/83167349-fdc80600-a0c4-11ea-977e-bbc8d6466c5a.png)

When I do this same idea with 3 identical plots using mtcars and the same layout, it works.
```
library(ggplot2)
library(patchwork)
p1 = ggplot(mtcars, aes(x= disp, y = wt)) + geom_point()
layout <- "
		AAAAAAABB
		AAAAAAABB
		AAAAAAABB
		AAAAAAACC
		AAAAAAACC
		AAAAAAACC
		AAAAAAADD
		AAAAAAADD
		AAAAAAADD
		"
p1 + p1 + p1 + p1 + plot_layout(design = layout)
```
<img width="1059" alt="Screen Shot 2020-05-28 at 9 19 35 AM" src="https://user-images.githubusercontent.com/394973/83167325-f30d7100-a0c4-11ea-8bf5-c0f79bf7f6ac.png">

It appears to be a complication with the caption of the first plot:
```
library(patchwork)
library(ggplot2)

p1 = ggplot(mtcars, aes(x= disp, y = wt)) + geom_point()
p1spec <- p1 + labs(caption = "\nError bars represent the standard error of the mean.\nANOVA model significance *p* < 0.05.\nTreatments with the same letter are not significantly different at *α* = 0.05 according to Tukey's HSD. ")

layout <- "
		AAAAAAABB
		AAAAAAABB
		AAAAAAABB
		AAAAAAACC
		AAAAAAACC
		AAAAAAACC
		AAAAAAADD
		AAAAAAADD
		AAAAAAADD
		"
p1spec + p1 + p1 + p1 + plot_layout(design = layout)
```
<img width="1059" alt="Screen Shot 2020-05-28 at 9 36 40 AM" src="https://user-images.githubusercontent.com/394973/83168734-cce8d080-a0c6-11ea-9637-d372f061defd.png">

**Comment by thomasp85** [comment]
I'm not quite sure I understand the issue... All the plot areas seems well-aligned to me?

**Comment by bhive01** [comment]
My issue is the bottom right corner. With the caption there is a large gap and the 3 right plots are not "stretched" to fill that space. When I do it with my main plot the plots aren't stretched either, they flex out the title and axis.text.x. 
Am I off base here?

**Comment by thomasp85** [comment]
this has nothing to do with the caption, but with the fact that your axis labels on the big plot is so huge. Patchwork will always align the corresponding elements with each other so very tall axis labels will push axis titles down in all plots aligned with that axis...

**Comment by bhive01** [comment]
I guess I want to align the plots on the right to the total height left plot including the caption, not align the plots to the plot area. Is there such an option? I have no need to align the plot areas. 
Also, that's a caption, not an axis label and yes, it's huge, and yes I need all of that information (or some proximity of it) so I'm in a jam.

**Comment by thomasp85** [comment]
You could put the three plots inside `wrap_elements()` to throw away all alignment, but other than that no... patchwork is quite strict about its layout mode.

Your code would be something like this:

```r
(p1 | wrap_elements(full = p2 / p3 / p4)) + plot_layout(widths = c(3, 1))
```

**Comment by bhive01** [comment]
You did think of everything. ;) 
<img width="1170" alt="Screen Shot 2020-05-28 at 11 28 49 AM" src="https://user-images.githubusercontent.com/394973/83179150-708dad00-a0d6-11ea-9591-f30bd67fedf4.png">
Yes, that's exactly what I needed!
