### ISSUE TITLE
  nrow * ncol >= n is not TRUE

### ISSUE THREAD

**Issue by Freya-Cui-2020** [thomasp85/patchwork#187]
I create two objects with pathwork below:
 >t1/((t2/t3)/tlist)
t1,t2,t3 are ggplot objects, tlist are list of ggplot objects.
Then I put each object into list named dlist, and try to put them together in a row, but I get error messages below:
>(dlist[[2]])+(dlist[[3]])+plot_layout(nrow = 1)
Error in wrap_dims(length(x$plots), nrow = x$layout$nrow, ncol = x$layout$ncol) : 
  nrow * ncol >= n is not TRUE

I could not understand why this error occurred, and it seemed like that  other path libraries like cowplot, gridExtra could not work on the objects of pathwork, is there any solutions to this problem?

**Comment by thomasp85** [comment]
It is very difficult to answer this without a reproducible example. One thing though is that there is no support for using lists of ggplot objects like that in patchwork
