### ISSUE TITLE
Making patchwork compatible with pdf creator using downloadHandler in Shiny?

### ISSUE THREAD

**Issue by VictorNautica** [thomasp85/patchwork#188]
I'm interested in using the patchwork package in arranging a set of plots, which the end user can then download using a download button. For simplicity I've only shown one plot in this example.

```
library(shiny)
library(tidyverse)
library(Cairo)
library(grDevices)

ui <- fluidPage(

  mainPanel(
    tabsetPanel(
      tabPanel(
        "PDF this plot with patchwork", 
        plotOutput("diamonds"),
        downloadButton("downloadPlot", "Download Plot")
      )
    )
  )
)

server <- function(input, output, session){

  output$diamonds <- renderPlot({
    ggplot(diamonds, aes(x=carat, y=price, color=cut)) + geom_point() + geom_smooth()
  })

  output$downloadPlot <- downloadHandler(
    filename = "my_plot.pdf",

    content = function(file){
      cairo_pdf(filename = file,
                width = 18, height = 10, pointsize = 12, family = "sans", bg = "transparent",
                antialias = "subpixel",fallback_resolution = 300)
      patchwork::wrap_plots(ggplot(diamonds, aes(x=carat, y=price, color=cut)) + geom_point() + geom_smooth())
      dev.off()
    },

    contentType = "application/pdf"
  )
}

shinyApp(ui=ui, server=server)
```

In this case, the pdf generated is blank. I looked at [this][1] relevant question, and if I replace `patchwork::wrap_plots` with `gridExtra::grid.arrange`, the app now works, however there are a lot of reasons I would prefer to use `patchwork` which I haven't featured (plot naming, subtitles etc). For my real script I'm not interested in using Markdown either.

If I have part of the code in a stand-alone script for creating a pdf:

```
cairo_pdf("test.pdf", family= "Segoe UI", width=16, height=9)
patchwork::wrap_plots(ggplot(diamonds, aes(x=carat, y=price, color=cut)) + geom_point() + geom_smooth())
dev.off()
```

It seems to be ok. So I think it must be something to do with compatibility with downloadHelper/Shiny?

  [1]: https://stackoverflow.com/questions/40272489/export-r-shiny-page-to-pdf

**Comment by thomasp85** [comment]
My guess is that you'll need to actually print the plot before closing the device - this happens automatically in a REPL but probably not in shiny...

Try to see if something like this works:

```r
output$downloadPlot <- downloadHandler(
    filename = "my_plot.pdf",

    content = function(file){
      cairo_pdf(filename = file,
                width = 18, height = 10, pointsize = 12, family = "sans", bg = "transparent",
                antialias = "subpixel",fallback_resolution = 300)
      p <- patchwork::wrap_plots(ggplot(diamonds, aes(x=carat, y=price, color=cut)) + geom_point() + geom_smooth())
      plot(p)
      dev.off()
    },

    contentType = "application/pdf"
  )
```
