### ISSUE TITLE
Interactive multiple plots object (patchwork + plotly)

### ISSUE THREAD

**Issue by laresbernardo** [thomasp85/patchwork#189]
Hi! What would be the best way to convert a `patchwork` plot into an interactive `plotly`-type plot? As a feedback, it'll be great to have the possibility to run `plotly::ggplotly` or similar function to do so, but I know that would depend on the other library. There could also be an argument like `plotly = TRUE` to auto-`plotly::ggplotly` our plots I guess.

I tried running the following line of code, to see if I could trick `patchwork` to achieve what I need but it broke the object as if no interactive plots are permitted:
`patch_plot$patches$plots <- lapply(patch_plot$patches$plots, plotly::ggplotly)`
Which return the following error message:
```
Error in UseMethod("plot_table") : 
  no applicable method for 'plot_table' applied to an object of class "c('plotly', 'htmlwidget')"
```
Any working and elegant solution in any of your minds out here? :)

**Comment by thomasp85** [comment]
Unless the poorly developer intend to implement this there is no chance that it will become possible. Currently you can use ggiraph to add some simple interactivity to patchwork plots such as hover text, selection, brushing, etc

**Comment by baderstine** [comment]
In a similar vein.  I created an interactive ggplot in shiny using the `plotOutput(... dblclick = ..., brush = ...)` functionality.  It seems to mostly work to recognize the raw events (click, double-click, brush, etc.), however, any functionality that depends on plot coordinates breaks as it seems that the entire image is recognized as the plot area.  Is this intended, a bug, or user error?  I can open a new issue with examples if needed.
