### ISSUE TITLE
Plot title

### ISSUE THREAD

**Issue by matteodefelice** [thomasp85/patchwork#19]
Any possibility to add a title to the composite plot? If I add (+) `ggtitle` or `labs` I get the title only on the last subplot,
cheers

**Comment by thomasp85** [comment]
Related to #16

**Comment by thomasp85** [comment]
With the latest update you can do:

```r
p_full <- p1 + p2
wrap_elements(p_full) + ggtitle('A title')
```

Still contemplating on the best way to do this as part of `plot_layout()` or similar
