### ISSUE TITLE
feature request: create list of wrapped plots if more plots provided than nrow * ncol

### ISSUE THREAD

**Issue by Blundys** [thomasp85/patchwork#191]
Hi, 

I have a feature request. I often have a large list of plots and would like to wrap them to a certain number of plots per pages and then save as a multiple page pdfs. 

To do this it would be super handy if I could provide a list of plots to `wrap_plots` and a nrow and ncol for what I'd like the final dimensions to be. Then if ncol * nrow is less than the total number of plots in the list it would return a list with each item having plots wrapped to those dimensions (e.g. my outlist below that I made manually).

Thanks

``` r
    library(ggplot2)
    library(purrr)
    library(patchwork)

mtplots <- mtcars %>% split(.,.$carb) %>% 
    imap(~ggplot(.x, aes(x = disp, y = mpg))+geom_point()+ggtitle(.y))

outlist <- list(wrap_plots(mtplots[1:2], ncol = 2, nrow = 1),
    wrap_plots(mtplots[3:4], ncol = 2, nrow = 1),
    wrap_plots(mtplots[5:6], ncol = 2, nrow = 1))

# Hoping that I can get the same output with just this :) 
# wrap_plots(mtplots, ncol = 2, nrow = 1)
```

<sup>Created on 2020-06-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
Since this is basically the same as calling lapply on the list I don’t really see a need for that, as it would complicate internal code and potentially make the api more unpredictable
