### ISSUE TITLE
aligning of legends and keys on guides = "collect"

### ISSUE THREAD

**Issue by Athanasiamo** [thomasp85/patchwork#192]
The first example I believe is a bug, where the legends are not aligned but should in theory be. 
 The `gear` legend seems to be indented slightly towards the right. 

``` r
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(patchwork)

mtcars2 <- mutate(mtcars, 
                  gear = factor(gear, labels = c("Three gears", "Four gears", "Five gears")),
                  cyl = factor(cyl, labels = c("Four cylinders", "Six cylinders", "Eight cylinders"))
                  )

p1 <- ggplot(mtcars2, aes(mpg, disp, colour = cyl)) + 
  geom_point()


p2 <- ggplot(mtcars2, aes(mpg, disp, colour = gear)) + 
  geom_point()


(p1 + p2) +
  labs(title = "legends are not aligned properly") +
  plot_layout(guides = "collect")
```

![](https://i.imgur.com/1tVSBfR.png)

The second is more of a feature request, but is related so I'm putting it here. 
Given two plots using the same type of geom, I would have wished the keys would align to make a tidy grid in some way. But, I am uncertain of the feasibility of this. 

``` r
(p1 + p2) +
  labs(title = "legends keys are not aligned") +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")
```

![](https://i.imgur.com/iL4z95K.png)

<sup>Created on 2020-06-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
I can't reproduce the bug so it is possible it was fixed by some of the recent fixes I've made. Can I get you to install from master and check if it is fixed on your end?

As for the feature request, I don't see this happening. It would simply assume too much about the gtable object that even the current types of guides doesn't all live up to

**Comment by Athanasiamo** [comment]
ah great. I can confirm that the alignment in the first example is fixed with an update. 

And I totally get that the feature request is not possible. In my mind you do ggplot2 voodoo, but some voodoo is just too much ;) 

Thanks for the quick reply!
