### ISSUE TITLE
Why are my images upside down and flipped?

### ISSUE THREAD

**Issue by sje30** [thomasp85/patchwork#195]
I'd like to use patchwork to compose a figure containing pdfs that have been made by other scripts, i.e. where I don't have a ggplot to render.  

```
require(ggplot2)
require(patchwork)
require(magick)


p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))

## Version 1: put scatter above boxplot, works fine.
png("version1.png")
p1 / p2
dev.off()
```

This produces the correct image:
![version1](https://user-images.githubusercontent.com/1095067/85150455-75173280-b24a-11ea-8634-3d3619e3b704.png)

```
## Now lets save the two plots as PDF, pretending we don't have the ggplot
## images that rendered them.
pdf(file="scatter.pdf"); p1; dev.off()
pdf(file="boxplot.pdf"); p2; dev.off()

######################################################################
## now try composing the same plot.

p1 = image_ggplot(image_read("scatter.pdf"))
p2 = image_ggplot(image_read("boxplot.pdf"))

## Version 2: arrgh, the box plot is now on top, and images are flipped.
png("version2.png")
p1 / p2
dev.off()
```
![version2](https://user-images.githubusercontent.com/1095067/85150569-9aa43c00-b24a-11ea-99b5-44b8da078e15.png)

This is wrong in a few ways: the boxplot is now on top (it should be at the bottom); the images are flipped, and the top and bottom of the images are truncated.

I can fix the flipping of the imags, but the rest is still wrong:

```
p1 = image_ggplot(image_flip(image_read("scatter.pdf")))
p2 = image_ggplot(image_flip(image_read("boxplot.pdf")))

png("version3.png")
p1 / p2
dev.off()
```

![version3](https://user-images.githubusercontent.com/1095067/85150691-c6272680-b24a-11ea-938a-d510d72e949e.png)

What am I missing?

CC: @nuest

**Comment by thomasp85** [comment]
This is a bug in ggplot2 that will get fixed https://github.com/tidyverse/ggplot2/pull/4081
