### ISSUE TITLE
Fixed scale coordinate systems forces aspect ratio for plot but not for axes.

### ISSUE THREAD

**Issue by odeleongt** [thomasp85/patchwork#2]
Adding a fixed scale coordinate system (such as `coord_equal`, `coord_fixed`, `coord_sf`, `coord_quickmap`, etc) will correctly result in a plot with fixed aspect ratio between `x` and `y`, but the axes will preserve the device aspect ratio. 

```r
library(package = "ggplot2")
library(package = "patchwork")

ggplot(mtcars) +
    geom_point(aes(disp, mpg)) +
    coord_equal() +
        # Add plot to get an assemble (assembly?)
        ggplot(mtcars) +
        geom_point(aes(disp, mpg)) +
    patchwork::plot_layout(nrow = 1)
```

![image](https://user-images.githubusercontent.com/1044835/33638240-b6a9c81a-d9ea-11e7-8c49-d3200cc231f3.png)

**Comment by thomasp85** [comment]
Unfortunately fixed coordinates are hard to consolidate with aligned panels between plots, so I’m unsure how to fix this - it does annoy me though... 😕

**Comment by thomasp85** [comment]
This is also the reason why you can’t have fixed coordinates and free scales in `facet_wrap`

**Comment by odeleongt** [comment]
Yeah. Maybe one option would be to have the plots align to one of the four edges of the panel where they are located, but then comes the problem of defining the alignment (sensible default could be to align left axes for plots stacked on top of each other, and bottom axes for plots located side by side).

For the general use cases (free scales) this is unnecessarily complex, but some edge cases could benefit very much. One of these would be arranging several maps (with `coord_sf`) to show context (as an inset map) or several features.

**Comment by thomasp85** [comment]
I think I've found a solution, but it will take some tinkering...

**Comment by bonifazi** [comment]
Hi all,
I run into a similar issue to the one above when using `wrap_plots()`. In short, the aspect ratio of some plots is lost when combining them from a given list of plots.
This is the line of code I am using (with plot.tmp being the list of plots to combine):
`patchwork::wrap_plots(plot.tmp, ncol = 5, tag_level = "keep", guides = "collect")`

However, I'm not sure how to apply the fix mentioned in this thread.
Is the "fixed_asp" or "simplify" a parametrization happening automatically in `patchwork ` or should I call it by using an argument?

Thanks in advance.
