### ISSUE TITLE
Small plots with coord_quickmap()

### ISSUE THREAD

**Issue by eliocamp** [thomasp85/patchwork#20]
This probably applies to other kinds of fixed ratio plots, but it seems like patchwork is leaving too much whitespace, resulting in tiny little plots. 

``` r
library(ggplot2)
library(patchwork)

df <- expand.grid(x = seq(0, 360, by = 3), 
                        y = seq(-90, 0, by = 3))
df$z <- with(df, x*y)

fplot <- ggplot(df, aes(x, y, fill = z)) +
        geom_tile() +
        theme(legend.position = "bottom") +
        coord_quickmap()

fplot +
    fplot +
    plot_layout(ncol = 1)
```

![](https://i.imgur.com/EXJO4El.png)

Cowplot, on the other hand, makes a much better use of space.

``` r
cowplot::plot_grid(fplot, fplot, ncol = 1)
```

![](https://i.imgur.com/dfgHNHV.png)

(Identical to `gridExtra::grid.arrange(fplot(1), fplot(2), ncol = 1)`)

**Comment by thomasp85** [comment]
Thanks for the report. Fixed aspect is finicky when it needs to be mixed with free aspect... I'll look into improving your use case

**Comment by thomasp85** [comment]
This turned out to just be a stupid bug. fixed
