### ISSUE TITLE
Common border for patchwork

### ISSUE THREAD

**Issue by suragnair** [thomasp85/patchwork#201]
Thanks for the lovely tool! I would like to have a single outline border for a patchwork.

using the `& theme(...)` option as suggested in #106 does not seem to work. Instead it applies a border on each individual plot.

`(ggplot() + ggplot()) & theme(panel.border = element_rect(colour = "black", fill=NA))` 
<img width="243" alt="Screenshot 2020-07-03 at 1 37 49 AM" src="https://user-images.githubusercontent.com/10693069/86450059-da006d00-bccd-11ea-8575-a5d82ed81eec.png">

How can obtain this:
<img width="254" alt="Screenshot 2020-07-03 at 1 37 00 AM" src="https://user-images.githubusercontent.com/10693069/86449982-c3f2ac80-bccd-11ea-81c7-081216f65260.png">

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS/LAPACK: /users/surag/anaconda3/envs/r36_cran/lib/libopenblasp-r0.3.9.so

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] patchwork_1.0.1 ggplot2_3.3.2  

loaded via a namespace (and not attached):
 [1] withr_2.2.0      dplyr_1.0.0      crayon_1.3.4     grid_3.6.3      
 [5] R6_2.4.1         lifecycle_0.2.0  gtable_0.3.0     magrittr_1.5    
 [9] scales_1.1.1     pillar_1.4.4     rlang_0.4.6      generics_0.0.2  
[13] vctrs_0.3.1      ellipsis_0.3.1   glue_1.4.1       purrr_0.3.4     
[17] munsell_0.5.0    compiler_3.6.3   pkgconfig_2.0.3  colorspace_1.4-1
[21] tidyselect_1.1.0 tibble_3.0.1    
```

**Comment by raulfernandezn** [comment]
Please check this possible solution:

```
library(patchwork)
library(ggplot2)
library(grid)
library(gridExtra)

#Plot
p <- (ggplot() + ggplot())

#Add border
p
grid.rect(width = 0.98, height = 0.98, gp = gpar(lwd = 3, col = "black", fill = NA))

```
It will produce this:

![imagen](https://user-images.githubusercontent.com/45948514/88695394-71878e80-d0c7-11ea-9d9f-b2145ce43ed6.png)

**Comment by suragnair** [comment]
The solution works for this particular case. However, would it be possible to compose the output with other plots- say if I wanted a 2x2 grid of each of the above (2 plots inside a shared border)?

**Comment by thomasp85** [comment]
``` r
library(ggplot2)
library(patchwork)
theme_border <- theme_gray() + 
  theme(plot.background = element_rect(fill = NA, colour = 'black', size = 3))
ggplot() + 
  ggplot() + 
  plot_annotation(theme = theme_border)
```

![](https://i.imgur.com/d5ZXaOO.png)

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by suragnair** [comment]
Thanks, unfortunately this can not be composed further.

```
(ggplot() + 
  ggplot() + 
  plot_annotation(theme = theme_border) ) |
(ggplot() + 
  ggplot() + 
  plot_annotation(theme = theme_border) )
``` 

gives
![image](https://user-images.githubusercontent.com/10693069/98364073-1cf49780-2056-11eb-9743-afb1c4f502bf.png)

**Comment by simschul** [comment]
This should do what you want: 
```
wrap_elements(full = ggplot() + ggplot() + plot_annotation(theme = theme_border)) |
  wrap_elements(full = ggplot() + ggplot() + plot_annotation(theme = theme_border))
```
