### ISSUE TITLE
White Border around Patched Plots

### ISSUE THREAD

**Issue by amirmasoudabdol** [thomasp85/patchwork#208]
I'm wondering how to remove the white border around the patched plot.

```
library(tidyvese)
library(patchwork)
library(ggthemes)

p1 <- mtcars %>%
    ggplot(., aes(mpg, wt, color = factor(carb))) +
    geom_point(size = 3, show.legend = F) +
    labs(title = "Blue Plot 1") +
    theme_economist()


p2 <- mtcars %>%
    ggplot(., aes(mpg, wt, color = factor(carb))) +
    geom_point(size = 3, show.legend = F) +
    labs(title = "Blue Plot 2") +
    theme_economist()

p1 + p2
```

This results in a correctly patched work, but it comes with a white border around the plot which is not part of the `p1` or `p2`. I've tired a few things and checked the issues but didn't manage to resolve it. You can see the white border in the screenshot!

<img width="984" alt="Screen Shot 2020-09-27 at 13 43 43" src="https://user-images.githubusercontent.com/1290841/94364137-78328200-00c7-11eb-8882-9c6524838ca4.png">

**Comment by amirmasoudabdol** [comment]
Is this an `ggsave` issue? 🤔

**Comment by thomasp85** [comment]
No, this is the margin of the patchwork, which is using the default theme. You can either set the margin to zero or change the theme of the patchwork as well:

```r
p1 + p2 + plot_annotation(theme = theme_economist())
```
