### ISSUE TITLE
plot_annotation titles are removed when assembling or wrapping plots

### ISSUE THREAD

**Issue by msto** [thomasp85/patchwork#209]
Hi,

I've found that titles added to a plot assembly are removed when trying to combine multiple assemblies into a larger figure. 

I've extended the [example](https://patchwork.data-imaginist.com/articles/guides/annotation.html#titles-subtitles-and-captions-1) in the assembly documentation page to demonstrate the issue. I'm able to add "Row1" and "Row2" to assemblies of the first and second plots and third and fourth plots, but these titles are removed when combining the assemblies with the stack operator (`/`) or `wrap_plots()`.

I think this is a bug and not intended behavior, as using `wrap_plots()` with `ncol=1` has the expected behavior of treating the sub-assemblies as individual plots, but please let me know if this is intended, or if I can add any other info.

Thanks!

```
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp)) + 
  ggtitle('Plot 1')

p2 <- ggplot(mtcars) + 
  geom_boxplot(aes(gear, disp, group = gear)) + 
  ggtitle('Plot 2')

p3 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  ggtitle('Plot 3')

p4 <- ggplot(mtcars) + 
  geom_bar(aes(gear)) + 
  facet_wrap(~cyl) + 
  ggtitle('Plot 4')
```

```
combo1 <- (p1 + p2) + plot_annotation("Row 1")
combo1
```
![combo1](https://user-images.githubusercontent.com/55061/94882868-fc656c00-041d-11eb-9831-ae36577286df.png)

```
combo2 <- (p3 + p4) + plot_annotation("Row 2")
combo2
```
![combo2](https://user-images.githubusercontent.com/55061/94882871-fec7c600-041d-11eb-95e5-a96b2e3e86a2.png)

```
combo1 / combo2
```
![stacked](https://user-images.githubusercontent.com/55061/94882873-fff8f300-041d-11eb-869a-ce7cd7d2f94e.png)

```
wrap_plots(combo1, combo2, ncol=1)
```
![wrapped](https://user-images.githubusercontent.com/55061/94882876-fff8f300-041d-11eb-9e75-6e81c35067e4.png)

**Comment by thomasp85** [comment]
This is a known limitation and is documented. At some point in the future I'll think about how to get around it

**Comment by msto** [comment]
Totally missed that note in the annotation docs, sorry. Thanks

**Comment by psychelzh** [comment]
Is there any workaround for this?

**Comment by abanihas** [comment]
@psychelzh @msto Same problem. Temporary solution in https://github.com/thomasp85/patchwork/issues/145

**Comment by trizniak** [comment]
> Is there any workaround for this?

I wrapped the plots in the list in `patchwork::wrap_elements` before the list goes into `patchwork::wrap_plots`
