### ISSUE TITLE
Align plots by something other than area

### ISSUE THREAD

**Issue by john-s-f** [thomasp85/patchwork#212]
Given the situation where you have a y axis label that is really long and are trying to stack plots, this happens
```
library(tidyverse)
library(patchwork)

df <- data.frame(x = c(letters[1:5]),
                 y = c(1,3,2,5,4))

p1 <- ggplot(df, aes(x, y))+
  geom_col()+
  scale_y_continuous(labels = c("The loooooooooooooonnnnggggeeesssttttttttttt label ever", letters[2:5]), breaks = 1:5)

p2 <- ggplot(df, aes(x, y))+
  geom_col()

p1 / p2
```
![image](https://user-images.githubusercontent.com/37672249/97789553-c986d300-1b97-11eb-84b1-90caf9f64a21.png)

Is it possible to make the lower plot area move to the left, placing it the appropriate distance away from the "y" label? I suppose this would be aligning by axis labels instead of plot areas.

**Comment by thomasp85** [comment]
In general: no... You can turn alignment off completely by wrapping the lower plot in `wrap_elements()`, i.e.

```
p1 / wrap_elements(full = p2)
```

but since no alignment is taking place it is sorta hit or miss whether it looks as expected
