### ISSUE TITLE
Specify tag order

### ISSUE THREAD

**Issue by christianholland** [thomasp85/patchwork#218]
Hi, 

is there a way to specify the tag order?

For the below shown example I would like to achieve that `Plot 2` is assigned tag `B`. Currently its assigned C, because its the last mentioned plot in the code, I guess?

Wouldn't it be good to add an argument such as `tag_list` that allows user to select arbitrary tags in an arbitrary order?

```r
library(ggplot2)
library(patchwork)
p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp)) + 
  ggtitle('Plot 1')

p2 <- ggplot(mtcars) + 
  geom_boxplot(aes(gear, disp, group = gear)) + 
  ggtitle('Plot 2')

p3 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  ggtitle('Plot 3')

((p1 / p3) | p2) + plot_annotation(tag_levels = "A")
```
![image](https://user-images.githubusercontent.com/28303875/100248327-a6073c00-2f3b-11eb-96eb-3093808088f7.png)

Thanks,
Christian

**Comment by steveharoz** [comment]
You can make custom tags. In this case, you could make a set with a custom order `c('A', 'C', 'B')`

```r
library(ggplot2)
library(patchwork)
p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp)) + 
  ggtitle('Plot 1')

p2 <- ggplot(mtcars) + 
  geom_boxplot(aes(gear, disp, group = gear)) + 
  ggtitle('Plot 2')

p3 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  ggtitle('Plot 3')

((p1 / p3) | p2) + plot_annotation(tag_levels = list(c('A', 'C', 'B')))
```
![image](https://user-images.githubusercontent.com/2257540/100261949-c5a66080-2f4b-11eb-9fa2-46822f4e1baa.png)

**Comment by christianholland** [comment]
Thanks, I must have missed this feature in the documentation. My apologies.
