### ISSUE TITLE
Image grobs aren't treated like normal patches in some cases

### ISSUE THREAD

**Issue by mattwarkentin** [thomasp85/patchwork#221]
Hi Thomas,

Not sure if this is a bug or just a feature not yet implemented (or I'm just doing something wrong), but it seems like images cannot be treated just like ggplot objects for composing patchworks. For the two examples that fail below, they work if logo is replaced with `p1`, a ggplot object.
``` r
library(magrittr)
library(ggplot2)
library(patchwork)

p1 <- 
  mtcars %>% 
  ggplot(aes(mpg, hp)) +
  geom_point() + 
  theme_light()

logo <- system.file('help', 'figures', 'logo.png', package = 'patchwork')
logo <- png::readPNG(logo, native = TRUE)

(p1 / p1) / logo
```

![](https://i.imgur.com/qVw4Bfy.png)

``` r
(p1 / p1) | logo
#> Error: Only knows how to fold ggplot objects together

(p1 | p1) / logo
#> Error: Only knows how to fold ggplot objects together
```

**Comment by Evanleen** [comment]
Along these same lines. Using this same example an error is thrown when logo is the first in the list:
` 
library(magrittr)
library(ggplot2)
library(patchwork)

p1 <- 
  mtcars %>% 
  ggplot(aes(mpg, hp)) +
  geom_point() + 
  theme_light()

logo <- system.file('help', 'figures', 'logo.png', package = 'patchwork')
logo <- png::readPNG(logo, native = TRUE)

logo / p1 / p1

Error in e1 + e2 + plot_layout(ncol = 1) : 
  non-numeric argument to binary operator
`
Is there a way to circumvent this?

**Comment by Evanleen** [comment]
> Along these same lines. Using this same example an error is thrown when logo is the first in the list:
> `
> library(magrittr)
> library(ggplot2)
> library(patchwork)
> 
> p1 <-
> mtcars %>%
> ggplot(aes(mpg, hp)) +
> geom_point() +
> theme_light()
> 
> logo <- system.file('help', 'figures', 'logo.png', package = 'patchwork')
> logo <- png::readPNG(logo, native = TRUE)
> 
> logo / p1 / p1
> 
> Error in e1 + e2 + plot_layout(ncol = 1) :
> non-numeric argument to binary operator
> `
> Is there a way to circumvent this?

EDIT: I found the solution

`wrap_elements(logo) | p1 | p1`
