### ISSUE TITLE
Option to put tags inside of plot borders?

### ISSUE THREAD

**Issue by Aariq** [thomasp85/patchwork#222]
Some journals, like Oecologia, require panel tags to be inside of plot boundaries.  Using `theme(plot.tag = element_text(hjust = , vjust = )` is fiddly and doesn't put tags in consistent distance from plot borders.

``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec))


(p1 | p2 | p3) +plot_annotation(tag_levels = "a", tag_prefix = "|", tag_suffix = "|") &
  theme(plot.tag.position = c(0,1),
        plot.tag = element_text(hjust = -2.5, vjust = 1))
#> `geom_smooth()` using method = 'loess' and formula 'y ~ x'
```

![](https://i.imgur.com/MnahoeP.png)

<sup>Created on 2020-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
Tag positioning is done through the tag mechanism in ggplot2 and it is highly unlikely that I'll venture outside of the supported modes. You should open an issue in ggplot2 if you want more tag positioning options
