### ISSUE TITLE
import individual operators or functions from patchwork

### ISSUE THREAD

**Issue by chunyunma** [thomasp85/patchwork#226]
This is a question rather than a bug report. 
I have been using [`import` package](https://import.rticulate.org) which supports commands such as: 

`import::from(broom, tidy)`
`import::from(magrittr, "%>%")`

I tried to import a few operators/functions from `patchwork` using the similar method. 
I got an error message when I tried 

```
import::from(patchwork, `-`)
# Error: '-' is not an exported object from 'namespace:patchwork
```

However, the next one was successful:

```
import::from(patchwork, `plot_layout`)
```

I am wondering if it is possible at all to import operators such as `+`, `-` 
from `patchwork` the same way I could with `%>%`?

Thank you very much!

**Comment by verasls** [comment]
I am experiencing the same issue when trying to import a `patchwork` operator to a package namespace.

When I add the following line to the NAMESPACE file:
```
importFrom(patchwork, `/`)
```
I get this error when running `devtools::check()`:
```
Error: object '/' is not exported by 'namespace: patchwork'
```

Thanks!

**Comment by AlissonRP** [comment]
If anyone else like me still has this question, it was answered in the https://github.com/thomasp85/patchwork/issues/246
Basically, if you are using Roxygen:
`#'@importFrom patchwork plot_layout `
`#'@export`
`patchwork::plot_layout `
