### ISSUE TITLE
Error with ggsave depending on pdf graphics device & font_family

### ISSUE THREAD

**Issue by brentocarrigan** [thomasp85/patchwork#227]
Hi Thomas, fantastic package - thanks so much

Apparent problems when `ggsave` a multiplot layout in pdf format

```
library(ggplot2)
library(patchwork)

theme_set(theme_bw(base_size = 18, base_family = 'Times New Roman'))

p1 <- ggplot(mtcars, aes(mpg, disp)) +
  geom_point(col = 'red')

p2 <- ggplot(iris, aes(Sepal.Length, Sepal.Width, col = Species)) +
  geom_point() +
  theme(legend.position = 'bottom')

p <- p1 + p2 + plot_annotation(tag_levels = 'A')

ggsave('multiplot.png', path = 'Figs/')
````
As png image is fine:
![multiplot](https://user-images.githubusercontent.com/25854676/103279391-93ae7100-49c5-11eb-8a11-822cf2ff81e2.png)

But not as a pdf: inside Rstudio plot compiled & looks fine in viewer, but when ggsave pdf export plot is incompletely exported:
```
> ggsave('multiplot.pdf',path = 'Figs/')
Saving 12.8 x 7.56 in image
Error in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  : 
  invalid font type
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
[multiplot.pdf](https://github.com/thomasp85/patchwork/files/5750444/multiplot.pdf)

But if I remove the `theme`, just using default `theme_grey()` pdf export works fine

And if I use `theme_bw()` but just standard font (not Times New Roman), then the pdf export is also fine.

Any ideas? Would prefer Times font in pdf exports for consistency across documents.

**Comment by thomasp85** [comment]
Does this work with pdf and Times using a single plot? I'm pretty sure this has nothing to do with patchwork

**Comment by brentocarrigan** [comment]
Good question - you're right, not patchwork - fails with a single plot too. I'll raise in a `ggplot2` forum.

**Comment by thomasp85** [comment]
This is not ggplot2 either but deficiencies in the pdf device that R ships with. You may be able to solve it with the extrafonts package

**Comment by brentocarrigan** [comment]
Quite right: Times New Roman was too specific, I just wanted a serif font.

Before trialling any extrafont package, if I just change the font_family to 'serif' (or 'Times') it works fine as single plots, and patchwork layouts.

Thanks!
