### ISSUE TITLE
Is it possible to wrap and overlap plots?

### ISSUE THREAD

**Issue by mingsu** [thomasp85/patchwork#228]
Is it possible to overlapping plots?

 e.g. by manually setting the position (x = 0.8, y = 0.9) of following plots based on the previous plots?

Possible strategy
-----

the area of  1st plot: x: 0 -1; y: 0-1;
the position of 2nd plot: x: 0.8; y: 0.7; indicating the area is x: 0.8-1.8; y: 0.7-1.7;

MWE for further need
----

```
require(patchwork)
p1 <- data.frame(x = 1:10, y = 1:10) %>%
    ggplot(aes(x = x, y = y)) +
    geom_point(size = 3) +
    geom_line() +
    theme_minimal()

p1 + p1
```

**Comment by thomasp85** [comment]
have a look at `inset_plot()`

**Comment by mingsu** [comment]
> have a look at `inset_plot()`



I can't find a explored function called `inset_plot()`, do you mean `inset_element()`?

If so, I have tried all current option for my need, but it seems not worked.

The point of what I expect is, all plots are  on the same level, the plot2 can beyond the area of plot1.


![Picture1](https://user-images.githubusercontent.com/3145794/103356004-bab29300-4aea-11eb-90e7-54ac90439df5.png)

**Comment by thomasp85** [comment]
`inset_element()` yeah -- sorry. If you want partially overlapping plots you can either do so by specifying a layout with overlapping areas (see `area()`) or adding multiple insets to a plot spacer

**Comment by mingsu** [comment]
> `inset_element()` yeah -- sorry. If you want partially overlapping plots you can either do so by specifying a layout with overlapping areas (see `area()`) or adding multiple insets to a plot spacer

After a quick try, it seems `area()` is the one I need, big thanks!

**Comment by mingsu** [comment]
I have write a function for my need, as shown below:

```


get_overlappingareas <- function(np,   # number of plot
                                 l2rp = 1, # left to right move propotion
                                 b2tp = 0, # bottom to top move propotion
                                 nrow = 1, # number of rows 
                                 S = 100, # the number of plot areas in X, or 1 row of  Y 
                                 btspace = S * 0.1, # add 10% S between rows
                                 preview = F) { # preview or not
    ncol <- ceiling(np / nrow)
    if (ncol < 2) {
        stop("number of columns should be > 1!")
    }
    w <- floor(S / (1 + abs(l2rp) * (ncol - 1)))
    h <- floor(S / (1 + abs(b2tp) * (ncol - 1)))
    if (w <= 0 | h <= 0) {
        stop("abs(l2rp) or abs(b2tp) are too big!")
    }
    if (l2rp >= 0) {
        Ls <- 1 + floor(w * l2rp * (0:(ncol-1)))
        Rs <- floor(Ls + w)
    } else {
        Rs <- S - floor(w * abs(l2rp) * (0:(ncol-1)))
        Ls <- floor(Rs - w)
    }
    if (b2tp >= 0) {
        Bs <- floor(S - h * b2tp * (0:(ncol-1)))
        Ts <- floor(Bs - h)
    } else {
        Ts <- 1 + floor(h * abs(b2tp) * (0:(ncol-1)))
        Bs <- floor(Ts + h)
    }
    Tss <- NULL
    Bss <- NULL
    Lss <- NULL
    Rss <- NULL
    for (j in 1:nrow) {
        Tss <- c(Tss, Ts + (j - 1) * (S + btspace))
        Bss <- c(Bss, Bs + (j - 1) * (S + btspace))
        Lss <- c(Lss, Ls)
        Rss <- c(Rss, Rs)
    }
    # cbind(Tss, Lss, Bss, Rss)
    areas <- area(Tss[1], Lss[1], Bss[1], Rss[1])
    for (i in 2:np) {
        areas <- c(areas, area(Tss[i], Lss[i], Bss[i], Rss[i]))
    }
    if (preview) { print(plot(areas)) }
    return(areas)
}

```

## Demo

It could produce nice overlapping areas for `design`.

```
areas <- get_overlappingareas(np = 6, l2rp = -0.2, b2tp = 0.1, nrow = 2, S = 20)
plot(areas)
```

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/3145794/103391417-67752a80-4b54-11eb-8df6-39dc3a9c8423.png">


```
p1 <- data.frame(x = 1:10, y = 10:1) %>%
    ggplot(aes(x = x, y = y)) +
    geom_line() +
    geom_point(aes(fill = y)) +
        theme_void() +
    theme(legend.position = "none",
          legend.key = element_blank(),
          legend.background = element_blank()) 

 p1 + p1 + p1  + p1 + p1  + plot_layout(design = get_overlappingareas(5, 0.1, 0.15))


```

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/3145794/103391485-b753f180-4b54-11eb-9bd1-904d0ed57da0.png">
