### ISSUE TITLE
plot_layout() give error size and location when using area() to create a design layout

### ISSUE THREAD

**Issue by mingsu** [thomasp85/patchwork#229]
MWE:

```
require(patchwork)
p1 <- data.frame(x = 1:10, y = 10:1) %>%
    ggplot(aes(x = x, y = y)) +
    theme_classic() +
    theme(panel.background = element_blank(),
          plot.background = element_blank()
    )

layout  <- c(
area(5,1,10, 6),
area(4,2, 9, 7),
area(3,3, 8, 8),
area(2,4, 7, 9),
area(1,5, 6,10)
)
plot(layout)
```
## `plot(layout)` gives this, showing the 5 plot area are the same size

<img width="796" alt="image" src="https://user-images.githubusercontent.com/3145794/103364694-6c58c080-4af9-11eb-9c0d-a3026ce07e37.png">

## but `plot_layout(design = layout)` give different sizes for each plot

```
p1 + p1 + p1 + p1 + p1  + plot_layout(design = layout)
```

<img width="797" alt="image" src="https://user-images.githubusercontent.com/3145794/103365176-74653000-4afa-11eb-8876-e971fe63fc6e.png">

## By simply check, it seems related with the size of margin?? area, since if we use `theme_void()`, the sizes are the same

```
p1 <- data.frame(x = 1:10, y = 10:1) %>%
    ggplot(aes(x = x, y = y)) +
    geom_point(size = 3) +
    geom_line() +
    theme_void() +
    theme(panel.background = element_blank(),
          plot.background = element_blank()
    )
p1 + p1 + p1 + p1 + p1  + plot_layout(design = layout)
```

<img width="798" alt="image" src="https://user-images.githubusercontent.com/3145794/103365141-5f889c80-4afa-11eb-8790-d9a90b9a1a89.png">

**Comment by thomasp85** [comment]
This is because only the panel area is included in the sizing of the areas. Thus any axes and titles that is put in between areas will expand the size of overlapping areas. This is easy to see if you stack two plots on top of a third (`p1 / (p2 | p3)`). The size of the plotting area in p1 is bigger than the combined size of the plotting areas of p2 and p3

**Comment by mingsu** [comment]
Thanks, understand now.

But is it possible to make it?

**Comment by thomasp85** [comment]
You could turn off alignment completely by putting each plot inside a `wrap_element()` statement, or go back to my other suggestion of putting insets into an empty plot (eg `plot_spacer()`)

**Comment by mingsu** [comment]
Great!
This did the job nicely!

```
wrap_element(p1) + wrap_element(p1) + wrap_element(p1) + wrap_element(p1)  + plot_layout(design = layout)
```
