### ISSUE TITLE
Add legend between patchwork main title and plot titles

### ISSUE THREAD

**Issue by zx8754** [thomasp85/patchwork#232]
Relevant post at SO:

-  https://stackoverflow.com/q/65733641/680068

I [submitted the answer (also posted below)](https://stackoverflow.com/a/65734061/680068) using *cowplot::get_legend*, is there a way of doing this without *cowplot*?

Solution:

```R
# get the legend
l <- cowplot::get_legend(p1 + theme(legend.position = "top"))

(cowplot::plot_grid(l) / (p1 + p2)) + 
  plot_layout(heights = unit(c(1, 5), "cm")) +
  plot_annotation(title = "main title") &
  theme(legend.position = "none")
```
![image](https://user-images.githubusercontent.com/5212915/104716156-6aa91280-571f-11eb-91cd-a8c4a1a4462f.png)

**Comment by thomasp85** [comment]
You can do this directly with patchwork using the `guide_area()` function as below:

``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars, aes(disp, wt, color = factor(gear))) + 
  geom_point() + 
  labs(title = "first plot title")
p2 <- ggplot(mtcars, aes(drat, qsec, color = factor(gear))) + 
  geom_point() + 
  labs(title = "second plot title")

(guide_area() / (p1+p2)) + 
  plot_layout(guides = "collect", heights = unit(c(1, 1), c("cm", "null"))) + 
  plot_annotation(title = "main title") & 
  theme(legend.position = "top")
```

![](https://i.imgur.com/NuTWeyE.png)

<sup>Created on 2023-08-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
