### ISSUE TITLE
Feature Request: Single scale for wrapped plot list

### ISSUE THREAD

**Issue by stephenwilliams22** [thomasp85/patchwork#234]
I work in the biomedical sciences and many times we'd like to view the same output across multiple condition so viewing everything on the same scale is important to make comparisons. The `patchwork::wrap_plots` function is awesome for working with multiple plots but only gets me part of the way to my desired outcome.

For example 

```
library(tidyverse)
library(patchwork)
a <- iris %>% 
  filter(Species == "setosa") %>% 
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color =Petal.Length )) +
  geom_point() +
  ggtitle("setosa")
b <- iris %>% 
  filter(Species == "versicolor") %>% 
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color =Petal.Length )) +
  geom_point()+
  ggtitle("versicolor")
c <- list(a,b)
patchwork::wrap_plots(c, ncol = 2) + plot_layout(guides = "collect")
```

Results in 

<img width="692" alt="Screen Shot 2021-01-24 at 9 59 40 AM" src="https://user-images.githubusercontent.com/24922527/105634206-ee06ea00-5e2a-11eb-813e-166a0e74513f.png">

However my desired output uses only one combined color bar. 

The only way that i've found to do this is by digging pretty deep into the list of plots and pulling the min/max values of my desired output like
 
```
library(tidyverse)
library(patchwork)
a <- iris %>% 
  filter(Species == "setosa") %>% 
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color =Petal.Length )) +
  geom_point() +
  ggtitle("setosa")
b <- iris %>% 
  filter(Species == "versicolor") %>% 
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color =Petal.Length )) +
  geom_point()+
  ggtitle("versicolor")
c <- list(a,b)
patchwork::wrap_plots(c, ncol = 2) + plot_layout(guides = "collect") & 
    scale_color_continuous(limits = c(0, bind_rows(lapply(c, `[[`, "data")) %>% 
                                        .[,"Petal.Length"] %>% 
                                        max(.)))
```
<img width="690" alt="Screen Shot 2021-01-24 at 10 02 34 AM" src="https://user-images.githubusercontent.com/24922527/105634295-4ccc6380-5e2b-11eb-80ec-d593e4f29039.png">

I've searched far and wide for a better solution than what I have come up with but can't seem to find one.

Having a single color scale as a feature in `wrap_plots` would be really great. 

Thanks for all your work!

**Comment by jsavinc** [comment]
I also came here looking for this feature and instead I just have a suggestion for how to simplify your workaround. If you assign the data for each plot to a separate variable, you can then simply use `range` on their concatenation to find the min and max values:

```
data_a <- iris %>% filter(Species == "setosa")
data_b <- iris %>% filter(Species == "versicolor")

patchwork::wrap_plots(c, ncol = 2) + plot_layout(guides = "collect") & 
    scale_color_continuous(limits = range(c(data_a$Petal.Length, data_b$Petal.Length)))
```

**Comment by thomasp85** [comment]
yes, I believe that @jsavinc's suggestion is the right way

I won't rule out that in the future you'll be able to compound the scale ranges automatically somehow but it is unlikely
