### ISSUE TITLE
theme_void seems to overwrite guides = "collect"

### ISSUE THREAD

**Issue by tjebo** [thomasp85/patchwork#237]
When using theme_void, guides = "collect" seems to stop working. Maybe theme_void is overwriting themes set by guides = "collect"? Also, global setting such as `& theme(legend.justification = "...")` seems to fail in this case. 

I stumbled upon this on [answering a question on stackoverflow](https://stackoverflow.com/questions/66307022/how-to-plot-outside-of-plotting-area-using-ggplot-in-r/66307631#66307631). Interestingly, guides between theme_void plots are being collected. (see last plot in this issue, and the SO example plot)
``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) +
  geom_point(aes(mpg, disp, colour = mpg)) +
  scale_color_continuous(limits = c(0,30)) 

p2 <- ggplot(mtcars) +
  geom_point(aes(hp, wt, colour = mpg)) +
  scale_color_continuous(limits = c(0,30)) 


p1 + p2 + 
  plot_layout(guides = "collect")
```

![](https://i.imgur.com/NoZASqj.png)

``` r

p1 + p2 + theme_void() + 
  plot_layout(guides = "collect")
```

![](https://i.imgur.com/l8qfNqq.png)

It works with other themes
``` r

p1 + p2 + theme_classic() + 
  plot_layout(guides = "collect")
```

![](https://i.imgur.com/GrkvpnH.png)

When both plots are `theme_void`, it works. 

``` r
p1 + theme_void() + p2 + theme_void()+
  plot_layout(guides = "collect")
```

![](https://i.imgur.com/Zco3J5o.png)

<sup>Created on 2021-02-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by thomasp85** [comment]
This is because `theme_void()` modifies the legend whereas the other examples uses themes with the same guide look.

patchwork is comparing the similarity of the generated grobs to determine whether to merge guides and this means that theming weighs in
