### ISSUE TITLE
Unexpected plot size with design formula

### ISSUE THREAD

**Issue by AmelZulji** [thomasp85/patchwork#238]
Hi folks, 

Following code:

```
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))

p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p21 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))

p3 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec))
p31 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec))
p32 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec))

design <- "
ABD
ABD
ABE
ACE
ACF
ACF
"

p1 + p2 + p21 + p3 + p31 + p32 + plot_layout(design = design) + plot_annotation(tag_levels = "A")
```

produces figure in which plot E is bigger than plots D & F.
![Rplot](https://user-images.githubusercontent.com/49162517/110488980-46e6c500-80ef-11eb-9478-6c0f3c5da99f.png)

I would expect plots in 3rd column to be of the same size. Is there a way to achieve that using design formula? 

Thank you in advance for help,
Amel

**Comment by thomasp85** [comment]
You are running your head into something that trips a lot of people up but is integral to patchworks layout mechanism. Only the panel area is part of the sizing - any axes, titles, etc will stretch the area in between by a fixed amount. The way to ensure that the third column will have all plots at equal size is to nest it into its own sub-patchwork
