### ISSUE TITLE
Feature request: add tableGrob() objects

### ISSUE THREAD

**Issue by LineStaunstrup** [thomasp85/patchwork#24]
Hi Thomas,

Thank you for a nice package that is build up in a very intuitive way. A feature I am missing though is the possibility to add tables as well as plots. I know you can do this with grid.arrange(), and I really miss that feature. 

/Line

**Comment by thomasp85** [comment]
Duplicate of #13 

I'm planning to add a `wrap_grob()` function that would allow adding arbitrary grob objects
