### ISSUE TITLE
Small gap between plots when specifying plot heights

### ISSUE THREAD

**Issue by tjebo** [thomasp85/patchwork#241]
[This Stackoverflow post](https://stackoverflow.com/questions/66939718/unwanted-separation-marks-lines-between-assembled-ggplots-using-patchwork/66944881#66944881) pointed towards the following behaviour: When specifying plot heights, there is a small gap visible between the plots. This disappears when passing theme globally. 

It seems also a device issue. It's not really an issue (especially not to me), just wanted to add it here in case it might point to other problems. 

No line
``` r
library(patchwork)
library(ggplot2)
p <-
  replicate(2, list(
    plot_spacer() + 
      theme(plot.background = element_rect(fill = "grey20",color = "grey20"))))

wrap_plots(p, nrow = 2)
```

![](https://i.imgur.com/qHiWIrz.png)

Line
``` r
wrap_plots(p, nrow = 2, heights = c(1,.1)) 
```

![](https://i.imgur.com/ijiBSrP.png)

Line disappears
``` r
wrap_plots(p, nrow = 2, heights = c(1,.1)) &
  theme(plot.background = element_rect(fill = "grey20",color = "grey20"))
```

![](https://i.imgur.com/GTqPI6G.png)

<sup>Created on 2021-04-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by thomasp85** [comment]
yeah, this is standard anti aliasing artefacts and device dependent. Nothing patchwork can do.

Thanks for the report
