### ISSUE TITLE
Unserialization of wrap_plots loses plots

### ISSUE THREAD

**Issue by Enchufa2** [thomasp85/patchwork#242]
Steps to reproduce:

1. Create a patchwork object and serialize it:

```r
library(ggplot2)
library(patchwork)

p1 <- ggplot(iris) + aes(Sepal.Length) + geom_histogram()
p2 <- ggplot(iris) + aes(Sepal.Length, Sepal.Width) + geom_point()
wrap_plots(p1, p2)
# shows a composition of p1 and p2

saveRDS(last_plot(), "test.rds")
```

2. In a clean R session:

```r
readRDS("test.rds")
# shows only p2
```

Is this expected behaviour?

**Comment by Enchufa2** [comment]
Actually, the following shows both plots:

```r
library(patchwork)
readRDS("test.rds")
```

which shouldn't be necessary.

**Comment by thomasp85** [comment]
why shouldn't it be necessary to have patchwork attached when displaying a patchwork plot?

**Comment by Enchufa2** [comment]
Attaching ggplot2 is not needed, so I would expect the same for patchwork.

**Comment by thomasp85** [comment]
The reason why it works in ggplot2 is a weird side effect of ggplot objects including a reference to the ggplot2 namespace deep inside the scales list. It was quite surprising as method dispatch in R in general doesn't work without the package loaded

I can probably try to emulate it in patchwork to cheat the classic R mechanics
