### ISSUE TITLE
The effect of area specification changes dependent on the areas included in a plot

### ISSUE THREAD

**Issue by gbiele** [thomasp85/patchwork#243]
I am not sure if this is intended behavior, but it was surprising to me.

I had thought that the position of `p1` and `p2` should be the same in `plot_A` and `plot_B` generated below.
But `p1` is wider in `plot_B`. 
Is it possible to specify a plot such that `p1` and `p2` use the same amount of space in `plot_B`?

```
p1 = ggplot(data.frame(x = rnorm(100)), aes(x = x)) + geom_histogram()
p2 = ggplot(data.frame(x = rnorm(100)), aes(x = x)) + geom_histogram()
p3 = ggplot(data.frame(x = rnorm(100)), aes(x = x)) + geom_histogram()

layout_A =  c(
  area(t = 1, l = 1, b = 100, r = 50),
  area(t = 1, l = 51, b = 100, r = 100)
)

layout_B =  c(
  area(t = 1, l = 1, b = 100, r = 50),
  area(t = 1, l = 51, b = 100, r = 100),
  area(t = 1, l = 30, b = 50, r = 70)
)

plot_A = p1 + p2 + plot_layout(design = layout_A)
plot_B = p1 + p3 + p3 + plot_layout(design = layout_B)
```

**Comment by thomasp85** [comment]
See https://patchwork.data-imaginist.com/articles/guides/layout.html#designs-dont-keep-an-even-width

This is intended though understandably surprising
