### ISSUE TITLE
insets, and base graphics with layout/mfrow

### ISSUE THREAD

**Issue by r2evans** [thomasp85/patchwork#244]
Thanks for `patchwork`!

I'm looking at a SO question (https://stackoverflow.com/q/67389256/3358272) that is suggesting the merge of a ggplot object and a base graphics `pairs` plot. While the premise of `inset_element` generally works, it appears that the panels within the base plot are being mis-ordered.

(It might not be necessary to use `ggblank`, but I didn't find a way to *start* with a base plot.)

```r
ggblank <- ggplot()
gg <- ggplot(mtcars, aes(mpg, disp)) + geom_point()
ggblank +
  inset_element(~pairs(mtcars[,2:4], lower.panel = NULL), left=0, bottom=0, right=1, top=1) +
  inset_element(gg, left=0, bottom=0, right=0.4, top=0.4)
```

![image](https://user-images.githubusercontent.com/5815808/117046902-3dd53700-acdf-11eb-9de1-ec62fee8d50d.png)

The `pairs` plot looks fine on its own, but it seems that things get a bit screwy internally. I'm inferring that this is similar to base graphic's problem with combining different multiplot methods (`layout`, `mfrow`, etc) at one time, is there a way to work around this?

**Comment by thomasp85** [comment]
To start with a base graphics you can use `wrap_elements()`

```
gg <- ggplot(mtcars, aes(mpg, disp)) + geom_point()
wrap_elements(full = ~pairs(mtcars[,2:4], lower.panel = NULL)) +
  inset_element(gg, left=0, bottom=0, right=0.4, top=0.4)
```

However, the issue remains that the insetted ggplot will require a lot of fiddling to match the location in the pairs plot. I'm afraid there is no way around that
