### ISSUE TITLE
Using `patchwork` in a package

### ISSUE THREAD

**Issue by baslat** [thomasp85/patchwork#246]
First of all, this is a great package and thank you for developing it.

I want to use `patchwork` in a custom package to automate the production of a compound plot. As part of building the plot I need to use `patchwork`'s methods for the `+`, `/` etc operators. However, I think these methods only become available once `patchwork` is libraried. 

As such, if I call `my_package::my_plot()` without `library(patchwork)`, it fails (even if `patchwork` is a `Imports` depdency in `my_package`). It gives the error ` Can't add chart_2 to a ggplot object`.

Is there an `@importFrom` command I can call to pull in `patchwork`'s `+`, `\` etc operator functions and methods?

Thanks

**Comment by thomasp85** [comment]
You just need to make sure that patchwork is imported by your package by e.g. having `@importFrom plot_layout` somewhere. This makes sure that all the overloaded operators are registered
