### ISSUE TITLE
Legend becomes very large in combined plot?

### ISSUE THREAD

**Issue by bbimber** [thomasp85/patchwork#249]
I've been using patchwork and overall it is a great package. I have two issues I dont understand when combining plots with legends. I have three ggplot objects, two of which have unique legends. First, when I try to combine then into rows, the legend from the bottom-right plot seems to be treated like it gets its own column in the layout (see how it sticks out beyond the top plot). Second, and this might be related, the legends always seem to become huge relative to the plot when combined. Are there ways to configure this?

At least as far as the top plot not extending full-width, based on your examples here (https://patchwork.data-imaginist.com/articles/guides/layout.html#controlling-guides-1), it seems like maybe this is simply how patchwork handles this?

```
Fig6 <- P1 + P7v + P6 + plot_annotation(tag_levels = 'A') + plot_layout(design = 'AA\nBC')
```

![image](https://user-images.githubusercontent.com/7724863/122394204-8f055700-cf2a-11eb-9d6f-6aad951ab3d2.png)

Thanks for any help

**Comment by thomasp85** [comment]
Legends are a fixed size in ggplot2, so this is more a question of the plots getting smaller while legends keeping their size. There is really no way around this besides using the theming functionality in ggplot2
