### ISSUE TITLE
Graphics issue when creating vignettes with high dpi setting

### ISSUE THREAD

**Issue by RS-eco** [thomasp85/patchwork#250]
Adding a dpi setting to the knitr::chunk_options()
```{r}
knitr::opts_chunk$set(
  dpi=300,
  collapse = TRUE,
  comment = "#>"
)
```
of any vignette, for example: annotation.Rmd of the patchwork package,
results in weird formatted multipanel figures, when using patchwork.
I am not sure if this is a bug or a result from changes in RStudio and R with R version 4.1.0 and RStudio version 1.4.17.17.

**Comment by thomasp85** [comment]
this does not seem to be specific to patchwork but any graphics produced in the vignette
