### ISSUE TITLE
guides inside layout rather than outside

### ISSUE THREAD

**Issue by bwiernik** [thomasp85/patchwork#251]
I have 3 plots, one with a legend guide (top row) and 2 with no legend (bottom row). I would like to have the bottom row span the full width of the top row, including the legend. However, with this syntax:

```r
p1 / (p2 | p3) + patchwork::plot_layout(nrow = 2)`
```

the guide is placed outside of the plot layout margins.

``` r
library(see)
model <<- lme4::lmer(Reaction ~ Days + (Days | Subject), lme4::sleepstudy)
plot(performance::check_distribution(model))
#> Warning: Removed 3 rows containing missing values (geom_segment).
#> Warning: Removed 3 rows containing missing values (geom_point).
```

![](https://i.imgur.com/Xy2RlFC.png)

<sup>Created on 2021-06-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

If I use `gridExtra::grid.arrange()`, I can achieve this instead:
![image](https://user-images.githubusercontent.com/4773225/123843963-727cfd80-d8e0-11eb-9e66-85553d8a1ffa.png)

Is there any way to get the lower two plots to span the width of the top row, including its guide? If not, could such an option be added?

**Comment by sven9r** [comment]
still struggeling with the same*

**Comment by thomasp85** [comment]
wrapping the top plot in `wrap_elements()` will get you there - see https://patchwork.data-imaginist.com/articles/guides/layout.html#huge-axis-text-causing-white-space-
