### ISSUE TITLE
Problem different plot widths and y-axis labeling while recreating facet~ with patchwork

### ISSUE THREAD

**Issue by sven9r** [thomasp85/patchwork#253]
I'm currently working on paper where I want to create some panel figures with patchwork.
Therefore I created all possible plots my self, which were placed on a grid.

In case need the structure of the individual plots + the patchwork code below

```
library(openxlsx)
library(tidyverse)
library(ggtext)
library(ggpubr)
library(patchwork)

SR_5101 <- alphalong %>%
  filter(Site_ID != "1200") %>% 
  filter(Site_ID != "3920") %>% 
  filter(Site_ID != "3902") %>%
  filter(Site_ID != "18101") %>%
  filter(Site_ID != "11200" | Tree != "Spruce") %>%
  filter(Site_ID != "1201" | Tree != "Spruce") %>%
  filter(SR_Type == "All") %>% 
  filter(Site_ID == "5101") %>% 
  mutate(Sitetype = str_replace(Sitetype,
                                "Forst","Forest"),
         Sitetype = str_replace(Sitetype,
                                "NP","Nature Reserve"),
         Sitetype = str_replace(Sitetype,
                                "Agrar","Agricultural")) %>%
  mutate(fctre = case_when(
    Sitetype == "Nature reserve" ~ "1",
    Sitetype == "Forest" ~ "2",
    Sitetype == "Urban" ~ "3",
    Sitetype == "Argricultural" ~ "4")) %>%
  mutate(title = paste0(Sitetype," - ", Site_ID)) %>% 
  mutate(fctre = as.numeric(fctre)) %>% 
  ggplot() +
  geom_line(aes(x = Year, y = SR_Obs, color = Tree), size = 1.2) +
  geom_smooth(method = 'lm', se = T, formula = y ~ x, size = 0.8, color = "black",
              aes(x = Year, y = SR_Obs)) +
  stat_regline_equation(aes(x = Year, y = SR_Obs, label = ..rr.label..), label.y = 115, label.x = 1987) + #ggpubr line
  facet_grid(~title) +                                                 
  scale_x_continuous(limits = c(1987, 2020)) +
  scale_y_continuous(limits = c(10,120),
                     breaks = c(20,40,60,80,100,120)) +
  scale_color_manual(values = c("#7CAE00")) +
  labs(y = "Observed Species Richness",
       color = "Tree Species") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_markdown(size = 12, color = "black"),
        axis.text.x = element_blank(),
        axis.text.y = element_markdown(size = 11, color = "black"),
        legend.text = element_markdown(size = 12, color = "black"),
        legend.title = element_markdown(size = 12, color = "black"),
        legend.position = "top")

((SR_5101 | SR_1201 | SR_2201 | SR_11200) /
    (log_5101 | log_1201 | log_2201 | log_11200) /
    (SR_2100 | SR_11111 | SR_3102 | SR_16102) /
    (log_2100 | log_11111 | log_3102 | log_16102)) +
  plot_layout(widths = 1, guides = 'collect') & theme(legend.position = 'top')
```
This is the output, 

![plot](https://user-images.githubusercontent.com/76955158/124102232-76d02480-da60-11eb-9ea6-ebd6f25a8435.png)

As you can see, although I used the plot_layout( widths =1), the figures have a little offset. With the lines from 1 and 2 I try to illustrate what I mean. Is there a way to fix this?
Secondly, I was not able to create one single y-axis (black/yellow box), because the y-axis will be cut of by the "/" command.
I looked for hours for a solution, but I can't find a solution myself. Any suggestions?

**Comment by thomasp85** [comment]
Your code creates four rows and places them on top of each other. Since the width of the y-axis differs it leads to a slight offsetting. For such a layout it would be better to simply use a matrix layout (i.e. avoid `|` and `/`, and just use `+`)

**Comment by sven9r** [comment]
`test`

> Your code creates four rows and places them on top of each other. Since the width of the y-axis differs it leads to a slight offsetting. For such a layout it would be better to simply use a matrix layout (i.e. avoid `|` and `/`, and just use `+`)

Thank you very much! This worked perfectly for the widths - thank you very much. at one point i tried + but somehow it looked different.

Do you have a suggestion for one  general y-axis for this kind of plot?

**Comment by thomasp85** [comment]
You could suppress the y-axis on all but the leftmost plots using `theme()`, but it is a bit fiddly... I do want to add something akin to guide collecting that solves this down the line

**Comment by sven9r** [comment]
Thank you again Thomas, now I have lead - will try my best. Will probably post my idea, in case people use the search function.
