### ISSUE TITLE
Failing to install patchwork

### ISSUE THREAD

**Issue by jrrizzari** [thomasp85/patchwork#26]
Hi Thomas,

Great thing you are doing here, but I am having a bit of trouble when I run the code to install patchwork. It says that it requires installation of additional build tools and then it is giving me an error saying that it could not find build tools necessary to build scales after I have clicked yes to install the tools. Any insight would be greatly appreciated.

Cheers,
Justin

**Comment by thomasp85** [comment]
I guess you're on a windows system? Try to install RTools (if not done already) and then install 'rlang' manually with `devtools` before installing `patchwork`

**Comment by jrrizzari** [comment]
Thanks for getting back to me so quickly.

I am using a Mac systems. I could not install RTools but did install rlang but still having the same problem trying to load patchwork.

**Comment by thomasp85** [comment]
Ah, ok. Rtools is not required on Mac.

My best guess is that this is due to some instability in the development versions of ggplot2 and its dependencies, but if you could paste the error message you get it would help me to either confirm or reject that idea

**Comment by jrrizzari** [comment]
Thanks heaps for the help.

Part way through the installation a window pops up with the below message:

Building R package from source requires installation of additional build tools.

Do you want to install the additional tools now?

I then click yes and it brings me to this webpage: https://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/ <https://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/>

The error is pasted below:

> devtools::install_github("thomasp85/patchwork")
Downloading GitHub repo thomasp85/patchwork@master
from URL https://api.github.com/repos/thomasp85/patchwork/zipball/master
Installing patchwork
Downloading GitHub repo tidyverse/ggplot2@master
from URL https://api.github.com/repos/tidyverse/ggplot2/zipball/master
Installing ggplot2
Downloading GitHub repo hadley/scales@master
from URL https://api.github.com/repos/hadley/scales/zipball/master
Installation failed: Could not find build tools necessary to build scales
Downloading GitHub repo tidyverse/rlang@master
from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
Installation failed: Could not find build tools necessary to build rlang
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/private/var/folders/fj/gnrflm894bl0813x51p17x6nt5yq1t/T/RtmpPnX73C/devtools118917fd68113/tidyverse-ggplot2-401511e'  \
  --library='/Users/jrizzari/Library/R/3.4/library' --install-tests 

* installing *source* package ‘ggplot2’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error : 'enexprs' is not an exported object from 'namespace:rlang'
Error : unable to load R code in package ‘ggplot2’
ERROR: lazy loading failed for package ‘ggplot2’
* removing ‘/Users/jrizzari/Library/R/3.4/library/ggplot2’
Installation failed: Command failed (1)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/private/var/folders/fj/gnrflm894bl0813x51p17x6nt5yq1t/T/RtmpPnX73C/devtools11891117d274d/thomasp85-patchwork-44a3962'  \
  --library='/Users/jrizzari/Library/R/3.4/library' --install-tests 

* installing *source* package ‘patchwork’ ...
** R
** preparing package for lazy loading
Error : object ‘ggplot_add’ is not exported by 'namespace:ggplot2'
ERROR: lazy loading failed for package ‘patchwork’
* removing ‘/Users/jrizzari/Library/R/3.4/library/patchwork’
Installation failed: Command failed (1)

**Comment by thomasp85** [comment]
Ah, those build tools🙂 - this is nothing related to R but the tools required to compile C/C++ code in source packages. Have a look at this guide and see if that sorts it out: http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

**Comment by jrrizzari** [comment]
That worked! Awesome. Thanks for that. Finally something that is a bit more straightforward to create multi panel figures.

**Comment by thomasp85** [comment]
Great🙂
