### ISSUE TITLE
Feature request: Switch active plot

### ISSUE THREAD

**Issue by DavisVaughan** [thomasp85/patchwork#27]
Loving patchwork! I would really love a way to switch the "active" plot. I can see in [arithmetic.R](https://github.com/thomasp85/patchwork/blob/master/R/arithmetic.R#L10) that the last plot added is the active one, but could we have a function to switch that? 

I feel like generally you'd like users to adjust things ahead of time at the ggplot2 individual plot level, but from a developer's standpoint, imagine that I wanted to make it really easy to create a multi-plot chart using `patchwork`. I'd return to the user a multi-plot like the one below, but then they could only adjust the bottom plot (added last) after the fact. If they could have a "switch active plot" feature then they could adjust any feature of the resulting chart. I think this could be pretty neat for maximum flexibility.

![screen shot 2018-01-23 at 11 28 43 am](https://user-images.githubusercontent.com/19150088/35288805-ac931bfa-0033-11e8-8f99-732daa20607f.png)

<details>
<summary>A reprex of what I mean</summary>

The basic idea is:

``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars, aes(x = cyl, y = mpg)) +
  geom_point()

p2 <- ggplot(mtcars, aes(x = as.factor(vs))) +
  geom_bar()
  
my_grouped_plot <- p1 + p2 + plot_layout(ncol = 1)

# Can access the second plot ("active")
my_grouped_plot +
  labs(title = "hello world")
```

![](https://i.imgur.com/iOgHzGz.png)

``` r

# But not the first...
```

Created on 2018-01-23 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

</details>

**Comment by DavisVaughan** [comment]
I would imagine being able to do:

```r
my_grouped_plot +
  labs(x = "an x axis label on one chart") %>%
  switch_active_plot(which = 2) +
  labs(x = "an x axis label on the other one")
```

**Comment by thomasp85** [comment]
I've contemplated on this, but haven't found a setup I like. For your example it seems simple but when returning nested layouts it gets more hairy...

So, for now, you can either target the last plot, all plots (using `&`), or all plots on the current nesting level (using `*`)

I'll keep it open as a reminder of a possible future feature

**Comment by thomasp85** [comment]
I'm closing this in lieu of #62 - I don't think I can come up with a compelling implementation
