### ISSUE TITLE
Suggestion: `wrap_plots()`: Replace NAs in a list of ggplots with blank plot

### ISSUE THREAD

**Issue by phargarten2** [thomasp85/patchwork#270]
Thank you for creating patchworks to allow users an intuitive graphical interface. I ran into an error when attempting to use `wrap_plots()` on a list of **ggplots**, but unfortunately, a few had NA's. Someone else had this question, and an answer was well documented here:

https://stackoverflow.com/questions/67098268/replace-nas-in-a-list-of-ggplots-with-a-dummy-plot

```{r}
dummy_plot <- ggplot() + theme_void()
```
To make it easier for users to use this in the future,  is it possible to edit `wrap_plots()` to include a dummy_plot() for any NA values in the list, as suggested?

Thanks

**Comment by phargarten2** [comment]
Pull request:
https://github.com/phargarten2/patchwork/pull/1

**Comment by thomasp85** [comment]
I think this is best done by the user prior to using patchwork. There is no obvious correct "dummy plot" and I'd rather not impose one
