### ISSUE TITLE
Nested graph and tag alignment

### ISSUE THREAD

**Issue by hliebert** [thomasp85/patchwork#279]
In the following case, how can I get the second tag/panel title correctly centered (i.e. like the first one)? I tried using titles and that didn't work (lower title was getting cut off). `plot.tag = element_text(hjust = 0.5)` doesn't seem to have any effect here.

```
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp)) + 
  ggtitle('Plot 1')

p2 <- ggplot(mtcars) + 
  geom_boxplot(aes(gear, disp, group = gear)) + 
  ggtitle('Plot 2')

p3 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  ggtitle('Plot 3')

p4 <- ggplot(mtcars) + 
  geom_bar(aes(gear)) + 
  facet_wrap(~cyl) + 
  ggtitle('Plot 4')

ptop <- p1
pbot <- p1 + p2 + p3 + p4
combined <- ptop + pbot +
  plot_layout(ncol = 1, guides = "collect") +
  plot_annotation(tag_levels = list(c("(a) Panel a", "(b) Panel b "))) &
  theme(plot.tag = element_text(hjust = 0.5, size = 30),
        plot.tag.position = "top",
        legend.position = "bottom") 
combined
```
![Screenshot from 2021-10-20 12-36-46](https://user-images.githubusercontent.com/20834265/138462725-c8819f2a-c353-4eea-8a0f-bda564d6deba.png)

**Comment by thomasp85** [comment]
This is a bug in how tags are placed in nested patchworks - thanks for reporting

**Comment by thomasp85** [comment]
moderating myself a bit. This is more of a limitation in the annotations of nested plots. In the same way as a nested patchwork can't have it's own title etc it also can't have it's own tag. I'm aware this is an annoying limitation but while seemingly easy to fix it breaks a lot of the things that makes patchwork "just work" in most cases.

You can treat the nested patchwork as a single plot using `wrap_elements(panel = pbot)` and then get the expected tagging behaviour but you then loose the panel alignment

``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp)) + 
  ggtitle('Plot 1')

p2 <- ggplot(mtcars) + 
  geom_boxplot(aes(gear, disp, group = gear)) + 
  ggtitle('Plot 2')

p3 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  ggtitle('Plot 3')

p4 <- ggplot(mtcars) + 
  geom_bar(aes(gear)) + 
  facet_wrap(~cyl) + 
  ggtitle('Plot 4')

ptop <- p1
pbot <- p1 + p2 + p3 + p4
combined <- ptop + wrap_elements(panel = pbot) +
  plot_layout(ncol = 1, guides = "collect") +
  plot_annotation(tag_levels = list(c("(a) Panel a", "(b) Panel b "))) &
  theme(plot.tag = element_text(hjust = 0.5, size = 30),
        plot.tag.position = "top",
        legend.position = "bottom") 
combined
```

![](https://i.imgur.com/BtAxAGS.png)

<sup>Created on 2023-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

(sorry, reprex doesn't handle large figures that well)

**Comment by hliebert** [comment]
Thanks for responding. I’m not using T very often nowadays and it’s been a while, so I don’t remember what I did to work around this limitation.
