### ISSUE TITLE
Patchwork doesn't seem to print to graphics devices

### ISSUE THREAD

**Issue by ConorIA** [thomasp85/patchwork#28]
Hi, I was hoping to save some figures with patchwork today by: 

```
p1 <- blahblah
p2 <- blahblah
png(filename = "foo.png", width = "7", height = "5", units = "in", res = "300")
p1 + p2
dev.off()
```

However no image is saved. The image is saved if using:

```
p1 <- blahblah
p2 <- blahblah
png(filename = "foo.png", width = "7", height = "5", units = "in", res = "300")
gridExtra::grid.arrange(p1, p2)
dev.off()
```

**Comment by thomasp85** [comment]
I cannot reproduce this - can I get you to install the latest version from GitHub and try again - It may have been solved in recent commits...

**Comment by ConorIA** [comment]
Hmm. It seems you are right. It must I must have had a typo somewhere in my code. Sorry to waste your time.
