### ISSUE TITLE
[Feature request] Method to collect other captions, axis labels, (titles, subtitles, ...?)...

### ISSUE THREAD

**Issue by aghaynes** [thomasp85/patchwork#282]
It would be great to have a method to collect other information besides the guides. Captions, x and y labels... and these things might be collected.

I have a case for example where I use a function to construct a pair of ggplots and then use patchwork to put them beside each other in some cases. The guides are collected, which is ideal, but the captions are duplicated. 

Obviously it would be possible to do the caption through patchwork instead of in the function. 

Oddly, while doing a reprex, I notice that the guide collection doesnt always seem to work for sizes:

``` r
library(ggplot2)
library(patchwork)
library(magrittr)

fn <- function(dat){
  ggplot(dat, 
         aes(x = x, y = y, size = size)) + 
    geom_point() +
    labs(caption = "something")
}

p1 <- data.frame(x = rnorm(10), y = 1, size = rnorm(10)) %>% 
  fn()

p2 <- data.frame(x = rnorm(10), y = 1, size = rnorm(10)) %>% 
  fn()

p1 + p2 + plot_layout(guides = "collect")
```

![](https://i.imgur.com/dSlAzkf.png)

<sup>Created on 2021-10-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by thomasp85** [comment]
I don't think we will see collection of various titles, but if I ever get to have collection of axis guides then the axis labels would follow along.

The reason why the guide is not merged is because they are not equal (they have different input ranges due to the `rnorm()` call)
