### ISSUE TITLE
Is it possible to incorporate externally generated figures?

### ISSUE THREAD

**Issue by shahmj** [thomasp85/patchwork#283]
Hi,

Is there a way to incorporate externally generated figures while composing layouts with this package?

Thanks,
Minita

**Comment by mhovd** [comment]
You can draw pictures to a ggplot with e.g. `cowplot::draw_image()`.
This is more a question of how to draw pictures to a `ggplot`, but here is an example:

```R
library(ggplot2)
library(patchwork)

p = ggplot(data = mtcars, aes(x = hp, y = disp)) +
  geom_point()

img = ggplot() +
  cowplot::draw_image("https://cran.r-project.org/Rlogo.svg")

p + img
```

**Comment by rbutleriii** [comment]
Hi @mhovd , thanks for the solution. Do you know if there is a way to reduce or eliminate the gray padding around the `svg` object?

**Comment by DanChaltiel** [comment]
For future travelers like myself, note that `logo + p1` will not work though.
(Not sure if this is worth a new issue)

**Comment by thomasp85** [comment]
This is already documented in the vignettes
