### ISSUE TITLE
Combine figures without alignment

### ISSUE THREAD

**Issue by RS-eco** [thomasp85/patchwork#284]
I want to combine two plots. One has a colour legend (located at the bottom) and one does not have a legend at all.
If I combine the plots, I get the following output:

``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  theme(legend.position = "bottom")
p2 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp))

p1 + p2
```

![](https://i.imgur.com/wcu458L.png)

However, I would like that the two figures actually do not align, but that Figure 2 uses up all of the available space, so fills up the bottom part, where for Figure 1 the colour legend is located.
Is there a simple way to turn of the automatic alignment for the 2nd plot?

**Comment by mhovd** [comment]
This does not readily answer your question, but have you considered creating a layout that would give you the desired output?
Here is an example:

``` r
library(ggplot2)
library(patchwork)
#> Warning: package 'patchwork' was built under R version 4.0.3

p1 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  theme(legend.position = "bottom")
p2 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp))


layout <- "
AABB
AABB
AABB
AABB
AABB
AABB
AABB
AABB
##BB
"

p1 + p2 + plot_layout(design = layout)
```

![](https://i.imgur.com/D3ov8IF.png)

**Comment by RS-eco** [comment]
Yes, this solves the issue partly, as does this:

``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + 
  geom_point(aes(hp, wt, colour = mpg)) + 
  theme(legend.position = "bottom")
p2 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp))

((p1 / plot_spacer()) + plot_layout(heights=c(50,1))) | p2
```

![](https://i.imgur.com/1XinH9H.png)

But it just adds white space to the left-side plot, so this is not really solving the issue for me. Any further solutions on how to trim the white space down to almost 0?

**Comment by RS-eco** [comment]
I just found a very simple solution:

``` r
((p1 + plot_spacer()) + inset_element(p2, 0,0,1,1, align_to = "full")) 
```

![](https://i.imgur.com/ORIsdo7.png)
