### ISSUE TITLE
Issue with plot _layout()

### ISSUE THREAD

**Issue by dkaplan1955** [thomasp85/patchwork#289]
Dear Dr. Pedersen

I hope this email finds you well.  I am using patchwork to align some plots and I am running into a problem.  Attached is a .pdf of the plot, and you will see that the plots in the second column are narrower than the plots in the left first column.  The last plot in the third row is the same size as the plots in the first column.  I am using the following code to create the plots (apologies that I can't seem to attach the plot, but if you run this program you'll see the problem).
 
library(tidyverse)
library(LaplacesDemon)
library(VGAM)  # For laplace distribution
library(patchwork) # For plot layouts
 
 
ridge=ggplot(data.frame(x = c(-10, 10)), aes(x = x)) + theme_bw()+
  theme(panel.grid.major=element_blank())+theme(panel.grid.minor=element_blank()) +
  labs(x=expression(theta),y=expression(p(theta)))+
  stat_function(fun=dnorm, args=list(mean=0, sd=1))
 
laplace= ggplot(data.frame(x = c(-20, 20)), aes(x = x)) +theme_bw()+
  theme(panel.grid.major=element_blank())+theme(panel.grid.minor=element_blank()) +
  labs(x=expression(theta),y=expression(p(theta)))+
  stat_function(fun=dlaplace, args=list(location=0, scale=4))
 
horseshoe <- ggplot(data.frame(x = c(-8, 8)), aes(x = x))+theme_bw()+
  theme(panel.grid.major=element_blank())+theme(panel.grid.minor=element_blank()) +
labs(x=expression(theta),y=expression(p(theta)))+stat_function(fun=dhs, args=list(lambda=dhalfcauchy(0,1), tau=dhalfcauchy(0,1)))
 
 
###### Finish Horseshoe
 
c2 = dinvgamma(.5,.5)
lambda = dhalfcauchy(0,1)
lambda2 = lambda^2
tau=dhalfcauchy(0,1)
tau2 = tau^2
lambda2_tilda = lambda_tilda2 = c2*lambda2/(c2+tau2*lambda2)
 
FinnHorseshoe <- ggplot(data.frame(x = c(-8, 8)), aes(x = x))+theme_bw()+
  theme(panel.grid.major=element_blank())+theme(panel.grid.minor=element_blank()) +
  labs(x=expression(theta),y=expression(p(theta)))+
  stat_function(fun=dhs, args=list(lambda=lambda2_tilda, tau=tau))
 
########
 
spikeSlab <- ggplot(data.frame(x = c(-1.5, 1.5)), aes(x = x))+theme_bw()+ylim(0,1)+
theme(panel.grid.major=element_blank())+theme(panel.grid.minor=element_blank()) +
geom_vline(xintercept=0,color = 'black',linetype = 'solid',size = 1) +
labs(x=expression(theta),y=expression(p(theta)))+stat_function(fun = dnorm,args=list(mean=0,sd=3))
 
layout <-
  "
AABB
CCDD
#EE#
"
ridge + laplace + horseshoe + FinnHorseshoe + spikeSlab + plot_layout(design = layout)
 
I am not sure why the plots are of different widths, but please let me know how I can fix this.
 
Thanks
 
David

**Comment by DavoOZ** [comment]
Simpler example of the same (minor) problem (i.e. plot on bottom right-hand-side is slightly squashed compared to the other five):

`suppressPackageStartupMessages(library(tidyverse))
library(patchwork)

p1 <- ggplot(mtcars, aes(mpg,wt)) + geom_point()

layout <- "
##AA##
#BBCC#
DDEEFF
"

p1 + p1 + p1 + p1 + p1 + p1 + plot_layout(design = layout)`

*** Thanks Thomas for producing a brilliant package ***

**Comment by thomasp85** [comment]
See #319 for a description of why this occur and how to circumvent it
