### ISSUE TITLE
plot_spacer does not work

### ISSUE THREAD

**Issue by RS-eco** [thomasp85/patchwork#29]
Running your example code:

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))

p1 + plot_spacer() + p2

I get the following error message:

Error: nrow(x) == nrow(y) ist nicht TRUE

I have ggplot2 Version 2.2.1.9000 and patchwork Version 0.01 installed.

**Comment by thomasp85** [comment]
There is currently some mismatch between patchwork and the development version of ggplot2 until the tag PR is merged.

Sorry for the inconvenience
