### ISSUE TITLE
custom tag for each plot; tried tag_suffix

### ISSUE THREAD

**Issue by jpmckeown** [thomasp85/patchwork#294]
Hi Thomas,
With plots in 1 column, I would like a text tag to left of each plot. 
I tried using tag_suffix as below but it shows only first tag for all four plots:
(substituted generic plots below)
library(patchwork)
var_titles <- c('Study Design', 
                'Type of data', 
                'Source of data', 
                'Internal validity rating')
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p4 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p1 + p2 + p3 + p4 +
  plot_layout(nrow = 4) +
  plot_annotation(tag_levels = '1', tag_suffix = var_titles)  

The actual plots are single horizontally stacked bars, each for a different variable showing proportions of categories (which are a different set of categories for each var - that's why I am plotting them separately, rather than just a set of stacked bars).

Screenshots are (1) quick-fake version to show what the combined plot is aiming for, tags would be in blank space on left side; (2) what I get with patchwork so far.

![4_stacks_example](https://user-images.githubusercontent.com/10098780/155316750-644549da-3844-4e23-9e63-1aad93ff2021.png)

![patchwork1](https://user-images.githubusercontent.com/10098780/155317515-09a5f426-185c-4c2b-aed6-703bc7e0f80c.png)

I don't need a tag_level (but is OK) -  added it so that tag_suffix appears. 
Please is there a way to add a different text tag beside each bar?

P.S. I turned to patchwork because though ggarrange did 4 side-titles they overlapped the bars and strayed from left side in ways I couldn't control in ggarrange - so patchwork is nicely robust, if I can just find how to make these 4 tags.)

**Comment by jpmckeown** [comment]
It's OK I got help/advice to do this using empty plots theme_void()
for side labels, as follows:

vars <- c('Type\nof data', 'Study\ndesign', 
          'Internal\nvalidity\nrating', 'Source\nof data')

label_plot <- function(label) {
  ggplot() + 
    geom_text(aes(x = 0, y = 0, label = label), 
              size=5, lineheight=1, hjust=0.5, fontface = 'plain') + 
    theme_void() + 
    theme(plot.margin = margin(0,0,0,0,'pt'))
}

figure_hbars <- label_plot(vars[1]) + typeOfDataHorizontalPlot3 +
  plot_spacer() + plot_spacer() +
  label_plot(vars[2]) + table1_studyDesignHorizontalPlot3 + 
  plot_spacer() + plot_spacer() +
  label_plot(vars[3]) + validityHorizontalPlot3 +
  plot_spacer() + plot_spacer() +
  label_plot(vars[4]) + dataSourceHorizontal3 +
  plot_layout(nrow = 7, widths = c(323, 3220), 
              heights = c(700, 30, 700, 30, 700, 30, 840))

**Comment by thomasp85** [comment]
If you don't need enumeration but a separate text for each plot you should add the tags directly to each ggplot, rather than rely on the auto-tagging functionality:

``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp)) + labs(tag = 'Study Design')
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear)) + labs(tag = 'Type of data')
p3 <- ggplot(mtcars) + geom_point(aes(mpg, disp)) + labs(tag = 'Source of data')
p4 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear)) + labs(tag = 'Internal validity rating')
p1 + p2 + p3 + p4 +
  plot_layout(nrow = 4)
```

![](https://i.imgur.com/4T2EHdi.png)

<sup>Created on 2023-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
