### ISSUE TITLE
bquote support in plot_annotation?

### ISSUE THREAD

**Issue by almenal** [thomasp85/patchwork#295]
I can use `bquote` to write plot titles with a mix of math symbols and variable values in them

```R
p1 <- ggplot(mtcars, aes(cyl, mpg)) + geom_point()
avg_disp <- mean(mtcars$disp)
p1+labs(title = bquote(AVG[disp]==.(avg_disp)))
```
![image](https://user-images.githubusercontent.com/49941206/157884066-3198d377-f6e1-4854-a7bc-062af79bbeaf.png)

However the same is not possible when arranging plots and putting a figure title with `plot_annotation()`

```R
p1 <- ggplot(mtcars, aes(cyl, mpg)) + geom_point()
p2 <- ggplot(mtcars, aes(gear, mpg)) + geom_boxplot()
avg_disp <- mean(mtcars$disp)
p1 + p2 + plot_annotation(title = bquote(AVG[disp]==.(avg_disp)))
```
which produces the following error message:
```
Error in dots_list(..., title = title, subtitle = subtitle, caption = caption,  : 
  object 'AVG' not found
In addition: Warning message:
Continuous x aesthetic -- did you forget aes(group=...)? 
```

The documentation of `plot_annotation` does say that title, subtitle and caption should be text strings, so I wouldn't say this is a bug. I'm just curious about what would be a workaround?

Thanks in advance

**Comment by EvoLandEco** [comment]
Same issue here, when I was trying to use bquote with plot_annotation, it just gave me an error

**Comment by WilliamCipolli** [comment]
Not technically a bug, as mentioned above, but this would be a great feature to add. @almenal I've gotten around this (painstakingly) by using Unicode characters.
