### ISSUE TITLE
Control order of legends inside plot_layout(guides = "collect")

### ISSUE THREAD

**Issue by DominiqueMakowski** [thomasp85/patchwork#297]
I am trying to adjust the order of the guides in the legend. For instance, having the size guide below the color guide:

``` r
library(ggplot2)
library(patchwork)

p6 <- ggplot(mtcars) + geom_point(aes(mpg, disp, color=cyl, size = qsec))
p7 <- ggplot(mtcars) + geom_point(aes(mpg, hp, color=cyl, size = qsec))

(p6 + p7) + 
  plot_layout(guides='collect')
```

![](https://i.imgur.com/iRgOus3.png)

<sup>Created on 2022-03-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I tried something like this but to no avail:

``` r
(p6 + p7) + 
  plot_layout(guides='collect') +
  guides(size = guide_legend(order = 1),
         color = guide_legend(color = 2))
```

![](https://i.imgur.com/XLbChDk.png)

<sup>Created on 2022-03-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thanks for any pointers!

**Comment by twest820** [comment]
Happened to notice this while searching for issues related to another issue I'm having. While this issue's been open for a while, I believe the syntax here just needs to be
```
  plot_layout(guides='collect') &
  guides(size = guide_legend(order = 1),
         color = guide_legend(color = 2))
```
rather than `plot_layout(...) +`.

**Comment by thomasp85** [comment]
You have a typo in the code, using the argument name "color" rather than "order" - further, as @twest820 points out, using `&` makes sure that the settings are applied to both plots

This seems to work

``` r
library(ggplot2)
library(patchwork)

p6 <- ggplot(mtcars) + geom_point(aes(mpg, disp, color=cyl, size = qsec))
p7 <- ggplot(mtcars) + geom_point(aes(mpg, hp, color=cyl, size = qsec))

(p6 + p7) + 
  plot_layout(guides='collect') &
  guides(size = guide_legend(order = 1),
         color = guide_legend(order = 2))
```

![](https://i.imgur.com/yYBZN5E.png)

<sup>Created on 2023-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
