### ISSUE TITLE
Using ggsave with patchwork

### ISSUE THREAD

**Issue by RS-eco** [thomasp85/patchwork#30]
I love the functionality of your package, but seem to run into trouble when trying to save the created multi-plot with ggsave(). A file is created, but the figure has just a grey background.

library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))

p1 + p2
ggsave("figures/test.png")

I am not sure this is a permanent issue, as I have already been able to save some multi-plot figures, which were created with patchwork.

**Comment by thomasp85** [comment]
This is due to the default use of `last_plot()` inside ggsave - If it has ever worked it has been accidental. I've opened an issue in ggplot2 to allow me to register the created plots, but until then just pass the created plot object in directly:

```r
p <- p1 + p2
ggsave('figures/test.png', p)
```

**Comment by thomasp85** [comment]
There is now a PR to ggplot2 that will help adding this feature: <https://github.com/tidyverse/ggplot2/pull/2433>
