### ISSUE TITLE
`patchwork` with `geom_label` ::::: Not supported? 

### ISSUE THREAD

**Issue by g-pacheco** [thomasp85/patchwork#307]
Hello all, 

This is much more a question than an issue. I have been trying to add `geom_label` to my `patchwork` object to no avail. Thus, I have been wondering if this move is even possible at all. If not directly, would it be possible to convert the `patchwork` object into a `ggplot` object and then apply the `geom_label` function to it? I acknowledge the `plot_annotation` function but I was really hoping I would be able to stick to the `geom_label` one. 

Thanks in advance, George. 

```
Map1 / (Map2 | Map3 | Map4) + plot_layout(widths = c(1)) +
  geom_label(aes(label = "Faroe Islands"), x = .1219, y = .93, size = 7.5, fontface = "bold", fill = "#c6dbef", color = "black") +
  geom_label(aes(label = "British Isles"), x = .3, y = .93, size = 7.5, fontface = "bold", fill = "#c6dbef", color = "black") +
  geom_label(aes(label = "Sri Lanka"), x = .57, y = .93, size = 7.5, fontface = "bold", fill = "#c6dbef", color = "black")
```

**Comment by thomasp85** [comment]
Hi - can you please provide a minimal reproducible example that shows the issue. There is no intended lack of support for `geom_label()` but I'm also not quite sure what you expect
