### ISSUE TITLE
Problems installing patchwork on R3.4.3 Mac (RStudio  1.0.153)

### ISSUE THREAD

**Issue by Tjebo** [thomasp85/patchwork#31]
I have problems to install this fabulous looking package.... But I don't understand why! 
Any idea?
This is copied from my console:  

> devtools::install_github("thomasp85/patchwork")
Downloading GitHub repo thomasp85/patchwork@master
from URL https://api.github.com/repos/thomasp85/patchwork/zipball/master
Installing patchwork
Downloading GitHub repo thomasp85/ggplot2@label-tag
from URL https://api.github.com/repos/thomasp85/ggplot2/zipball/label-tag
Installing ggplot2
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/digest_0.6.15.tgz'
Content type 'application/x-gzip' length 161517 bytes (157 KB)
==================================================
downloaded 157 KB

Installing digest
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/vh/9q9pdfhs1cbdshpq7zgzmxyc0000gn/T/RtmpOiOaGE/devtools2ca63656a78e/digest'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *binary* package ‘digest’ ...
* DONE (digest)
Downloading GitHub repo hadley/scales@master
from URL https://api.github.com/repos/hadley/scales/zipball/master
Installation failed: Could not find build tools necessary to build scales
Downloading GitHub repo tidyverse/rlang@master
from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
Installation failed: Could not find build tools necessary to build rlang
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/vh/9q9pdfhs1cbdshpq7zgzmxyc0000gn/T/RtmpOiOaGE/devtools2ca6555bb68c/thomasp85-ggplot2-f53b99f'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘ggplot2’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error : 'enexprs' is not an exported object from 'namespace:rlang'
Error : unable to load R code in package ‘ggplot2’
ERROR: lazy loading failed for package ‘ggplot2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ggplot2’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ggplot2’
Installation failed: Command failed (1)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/vh/9q9pdfhs1cbdshpq7zgzmxyc0000gn/T/RtmpOiOaGE/devtools2ca66e33b40e/thomasp85-patchwork-31b2b8e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘patchwork’ ...
** R
** preparing package for lazy loading
Error : object ‘ggplot_add’ is not exported by 'namespace:ggplot2'
ERROR: lazy loading failed for package ‘patchwork’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/patchwork’
Installation failed: Command failed (1)

**Comment by thomasp85** [comment]
Try to manually install rlang from GitHub (r-lib/rlang) and then rerun your installation code.

**Comment by Tjebo** [comment]
Hi. Thanks for the idea. I had rlang already installed. But did it as you said and tried manually installing it from the GitHub site. Without success. Tried using RStudio and 'R' (Mac). This is the error output: 

Downloading GitHub repo r-lib/rlang@master
from URL https://api.github.com/repos/r-lib/rlang/zipball/master
Installing rlang
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/vh/9q9pdfhs1cbdshpq7zgzmxyc0000gn/T/RtmpRfHULy/devtools2e1b1133739d/r-lib-rlang-c6747f9'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘rlang’ ...
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘rlang’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rlang’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rlang’
Installation failed: Command failed (1)


Please don't worry too much about me, I am probably making a stupid mistake and missing something obvious. I am sure the package installation will work like a charm for probably everyone else. Cheers

**Comment by tungmilan** [comment]
@Tjebo : maybe try the solution here? https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path

**Comment by zhouzhen1** [comment]
I also get this issue. It's not related to Mac as I am on Linux.

**Comment by jacotton** [comment]
I have what looks like the same problem: 
Error : object ‘ggplot_add’ is not exported by 'namespace:ggplot2'

 with ggplot2 2.2.1, R 3.4.1 running on linux

**Comment by thomasp85** [comment]
Try again - there has been some mismatches between clang and ggplot2 that should have been resolved with the CRAN release of the new rlang version
