### ISSUE TITLE
title in blank plot_spacer?

### ISSUE THREAD

**Issue by rhart604** [thomasp85/patchwork#313]
Is there any way to add a title to a blank spacer created with plot_spacer()?  I'd like to indicate which plots in a large list had no data to plot.

(Otherwise, I LOVE the package--thank you!)

**Comment by thomasp85** [comment]
Instead of a plot spacer you could instead add a textGrob()

``` r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp)) + 
  ggtitle('Plot 1')

p2 <- ggplot(mtcars) + 
  geom_boxplot(aes(gear, disp, group = gear)) + 
  ggtitle('Plot 2')

p1 + grid::textGrob("No data") + p2
```

![](https://i.imgur.com/HaACA8U.png)

<sup>Created on 2023-08-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
