### ISSUE TITLE
Feature suggestion: allowing expressions for plot_annotation strings

### ISSUE THREAD

**Issue by dbarneche** [thomasp85/patchwork#315]
Hello, I am wondering if it would be possible to allow `expression` and `substitute` statements for the `title` and `subtitle` arguments of `plot_annotation`?

**Comment by dylbaker** [comment]
I would also find this very useful. I am trying to italicize a specific portion of the title and expression nor substitute will work right now.

**Comment by thomasp85** [comment]
The labelling used in patchwork is based on the same code as that in ggplot2 so this should be raised there. It is unlikely that patchwork will branch away from that...

However, with marquee or ggtext it is quite easy to change various font settings if that is what is needed
