### ISSUE TITLE
Using patchwork to layout plots created with facet_wrap()

### ISSUE THREAD

**Issue by gorkang** [thomasp85/patchwork#32]
It would be awesome if there was a way to use patchwork to layout subplots of a facet_wrap() ggplot.

For example, I have a set of 8 subplots that I need to show in three rows (2, 3, 3), I guess something like:

`(A | B ) / (C | D | E) / (F | G | H)`

But as I created the plots by `ggplot(...) + facet_wrap( ~ Type)`, I am not sure if there is a way to use patchwork to rearrange the subplots.

Thanks!

**Comment by thomasp85** [comment]
There is not, and it is outside the scope of `patchwork`
