### ISSUE TITLE
plot_annotation doesn't work when combining nested levels

### ISSUE THREAD

**Issue by mattansb** [thomasp85/patchwork#33]
I was just trying to push `patchwork` to its limits (oh so very cool), and found that `plot_annotation` does not work with multiple nested levels doesn't work.

For example, using `plot_annotation` in the following code has no effect.

```
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_line(aes(mpg, disp))
p4 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec))
p5 <- ggplot(mtcars) + geom_bar(aes(carb))


{
  {
    p1 | p2
  } / p3 + plot_layout(heights = c(1,3), tag_level = "new")
} | {
  p4 / p5 + plot_layout(heights = c(3,1))
} + plot_annotation(title = "Hello. World.", tag_levels = c("A","1"))
```
Not sure that this would be considered a bug per se, as I cannot think of a situation in which someone would actually want to do what I was trying to do.

**Comment by thomasp85** [comment]
No, this is definitely a bug - thanks for reporting!

**Comment by thomasp85** [comment]
Ah... this is an unfortunate result of operator precedence. The `|` has lower precedence than `+` so the `plot_annotation` is added to the nested plot (and thus ignored), rather than the full plot.

Simply enclose the plot composition in parenthesis (keeping `plot_annotation` out of it)

**Comment by mattansb** [comment]
That seems to do it! Thanks!
Maybe add "order of operations" to the documentation?

**Comment by thomasp85** [comment]
Yeah, the documentation will see an improvement before CRAN release

**Comment by mattansb** [comment]
Looking forward to it. Thanks again - this package is as awesome as it is stupidly easy to use!

**Comment by thomasp85** [comment]
🙂
