### ISSUE TITLE
Cannot turn off printing of TLBR table in R Markdown or Quarto documents when composing plots with `wrap_plots` or `+`

### ISSUE THREAD

**Issue by caparks2** [thomasp85/patchwork#331]
When composing plots using `wrap_plots()` or plot arithmetic operators in an R Markdown or Quarto document, and assigning the resulting patchwork to an object using `<-`, a table with columns "t", "l", "b", and "r" is printed in line as an output of the chunk. This cannot be avoided using `invisible()`. In an R Markdown document using `knitr` chunk options `{r, results='hide'}` fails to prevent the table from being printed while `{r, include=FALSE}` succeeds. In a Quarto document the execution option `#| output: false` fails while `#| include: false` succeeds.

### R Markdown
![image](https://github.com/thomasp85/patchwork/assets/60522768/111e00b4-cf60-43ec-acbd-18f750e623a4)

### Quarto
![image](https://github.com/thomasp85/patchwork/assets/60522768/b2840338-cf40-4cae-b549-2cb635520561)

**Comment by thomasp85** [comment]
This is an issue in knitr - I'm in talk with the devs

**Comment by thomasp85** [comment]
@cderv looping you in so you have an eye on it
