### ISSUE TITLE
Disregard axis labels when positioning legend boxes

### ISSUE THREAD

**Issue by stitam** [thomasp85/patchwork#333]
Hi,

Maybe not an issue, but I couldn't get this to work: FigA has very long y axis labels at the right side of the plot. FigB has a legend box also  in the right side of the plot. When I compose FigA/FigB, the legend box for FigB is placed very far from the plot because it only starts where the y axis labels for FigA end. What I want is to keep the plot areas aligned but disregard the space required for y axis labels when calculation the position of the legend box. Any way to do this? Many thanks.

**Comment by stitam** [comment]
I have another question related to this. Is it possible to tell `patchwork` which plot goes where using `plot_layout(design = c(area(),area(), etc.))`, but then do not do any other aligning? I would like to replicate a programmable version of creating a number of plots and just putting them next to each other on a canvas. The only extra I want is `guide_area()` for the combined legend, but I do not want `patchwork` to align the plot areas or the text labels. Thanks.

**Comment by thomasp85** [comment]
For the first question the answer is no, you can't both get aligned plot regions and disregarding all other alignment.

For the second question I'm afraid I don't really understand what you are asking - can you provide some code and visual for it?

**Comment by stitam** [comment]
Thanks @thomasp85 here is an example, for both really:

```
library(ggplot2)
library(patchwork)
rm(list = ls())

# import mtcars
data(mtcars)

# prep a long column
mtcars <- tibble::rownames_to_column(mtcars, "model") |>
  dplyr::mutate(model = paste(model, model, model, sep = "_"))

mtcars$cyl <- as.character(mtcars$cyl)
mtcars$gear <- as.character(mtcars$gear)

g1 <- ggplot(mtcars, aes(model, mpg)) + geom_col(aes(fill = cyl)) + coord_flip()
g2 <- ggplot(mtcars, aes(wt, mpg)) + geom_point(aes(col = gear)) + coord_flip()

g <- g2 + g1 + guide_area() + plot_layout(
  design = c(
    area(1, 1, 45, 100),
    area(46, 1, 90, 100),
    area(91, 1, 100, 100)
  ),
  guides = "collect"
) &  theme(
  legend.position = "bottom",
)
```

![mtcars](https://github.com/thomasp85/patchwork/assets/49147718/5c2330b0-50ec-49c4-a6f8-3acb481d5184)

I made the model names super long to illustrate my problem: patchwork aligns the plot panels i.e. the grey plot areas and also the axis labels which is generally nice, but in this particular case the y axis label on the top plot will be very far from the plot panel!

I would like to be able to tell patchwork that "here is `area(1,1,45,100)` dedicated for the top figure, put the figure in that area but do not align the panel with any of the adjacent plots". Ideally this would create a composite plot where the y axis labels are aligned as before but the panel for the top plot is much wider than the panel for the bottom plot.

I hope this clarifies my issue? Many thanks.

**Comment by thomasp85** [comment]
I just added a `free()` function I think might help you. Please let me know if this is what you are after

``` r
free(g2) + free(g1) + guide_area() + plot_layout(
    design = c(
        area(1, 1, 45, 100),
        area(46, 1, 90, 100),
        area(91, 1, 100, 100)
    ),
    guides = "collect"
) &  theme(
    legend.position = "bottom",
)
```

![](https://i.imgur.com/g6pKVpO.png)

**Comment by stitam** [comment]
This is perfect, thanks @thomasp85
