### ISSUE TITLE
empty `patchwork` object

### ISSUE THREAD

**Issue by rerickson-usgs** [thomasp85/patchwork#334]
I'm using a loop to go over data. How do I create an empty `patchwork` object

Let's say my loop looks like this:

```r
df_save <- tibble()
for (idx in my_names){

    ## Do stuff ....
   out <- my_cool_function()

    df_save  <- df_save |> bind_rows(out)
} 
```

How would I do this with `patchwork`? I didn't find a way to create a `patchwork` object that I could add to in the documentation.

**Comment by thomasp85** [comment]
I would generally store the plots you create in a list and use `wrap_plots()` to turn them into a patchwork
