### ISSUE TITLE
How to remove borders between plots?

### ISSUE THREAD

**Issue by SeriyBg** [thomasp85/patchwork#341]
When I'm using the `theme_solarized(light=F)` from the `ggthemes` package, the plot's background color becomes dark. And with the patchwork, I have the white borders between them. Is it possible to get rid of it?

Example:
```
p1 <- ggplot() + theme_solarized(light=F)
p2 <- ggplot() + theme_solarized(light=F)
p1 | p2
```

![Rplot](https://github.com/thomasp85/patchwork/assets/3988842/6b780ab0-efa5-47fd-8168-bf22240b5770)

**Comment by thomasp85** [comment]
I don't know where `theme_solarized()` comes from so it is hard to say, but perhaps setting the background color to the same as the fill?

**Comment by trekonom** [comment]
The issue is that the theme used for the patch as a whole defaults to `theme_grey` (??). But you can set that via the `theme=` argument of `plot_annotation()`:

``` r
library(ggplot2)
library(ggthemes)
library(patchwork)

p1 <- ggplot() +
  theme_solarized(light = FALSE)
p2 <- ggplot() +
  theme_solarized(light = FALSE)

(p1 | p2) &
  ## Just for the reprex
  theme(
    plot.background = element_rect(color = "red", linetype = 1)
  ) &
  ##
  plot_annotation(
    theme = theme_solarized(light = FALSE)
  )
```

![](https://i.imgur.com/LkDC7rX.png)

<sup>Created on 2024-01-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
