### ISSUE TITLE
Feature request: allow `inset_element()` to handle facet merging

### ISSUE THREAD

**Issue by matiasandina** [thomasp85/patchwork#344]
I am trying to plot a facet plot. My idea is to display inset plots according to the facet. Here's a reproducible example using `mtcars`. The idea would be to get density plots for `am=0` on the proper (`am=0`) facet at (0.5, 0.5, 1, 1). Same idea for `am=1`.

``` r
library(tidyverse)
library(patchwork)
p1 <- ggplot(mtcars, aes(cyl, mpg)) + 
  geom_point(color = "red") +
  facet_wrap(~am)
p2 <- ggplot(mtcars, aes(hp)) + 
  geom_density(aes(fill=factor(cyl), color=factor(cyl))) +
  facet_wrap(~am)
p1
```

![](https://i.imgur.com/0BgAnnH.png)

``` r
p2
```

![](https://i.imgur.com/aeW23lJ.png)

I understand why this is not functioning the way I want it. I am not sure if this should be an acceptable feature request to the library. Ideally, `patchwork` would automagically realize that the inset has to go on proper panels. 

``` r
p1 + inset_element(p2, 0.5, 0.5, 1, 1)
```

![](https://i.imgur.com/zvrv8Kx.png)

<sup>Created on 2023-12-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The expected output would be:

![image](https://github.com/thomasp85/patchwork/assets/7494967/e08ef9c2-1185-4811-b305-1bba71c4e5a9)

I came up with a solution to individually subset data and return the inset plot to be later used in a layout. I have also asked this question and there is a proposed answer that is a bit more elegant than my method [here](https://stackoverflow.com/questions/77641100/patchwork-inset-element-with-facets).  I feel that this use case is a somewhat complex functionality that people end up having to customize like [here](https://www.blopig.com/blog/2019/08/combining-inset-plots-with-facets-using-ggplot2/). It would be great if `patchwork` could handle this internally.

**Comment by thomasp85** [comment]
I understand the wish for something like this but it will not happen for multitudes of technical reasons :-)

The way forward is to subset the data manually as you've already arrived at
