### ISSUE TITLE
collecting axis titles does not work when using more complex designs

### ISSUE THREAD

**Issue by n-kall** [thomasp85/patchwork#349]
The following works:

```r
library(ggplot2)
library(patchwork)

p1 <- ggplot(mtcars) +
  geom_point(aes(mpg, disp)) +
  labs(y = "mpg", x = "collected axis title")

p2 <- ggplot(mtcars) +
  geom_boxplot(aes(gear, disp, group = gear)) +
  labs(y = "gear", x = "collected axis title")

p1 + p2 + plot_layout(axis_titles = "collect", design = "AB")
```
![pwork1](https://github.com/thomasp85/patchwork/assets/33577035/284b6517-898c-491c-8781-8c07e61d6e20)

but changing the design leads to the axis collection no longer happening
```r
p1 + p2 + plot_layout(axis_titles = "collect", design = "AAB")
```
![pwrk](https://github.com/thomasp85/patchwork/assets/33577035/6c76a312-ff57-421a-ba79-25e0057185da)
```r
p1 + p2 + plot_layout(axis_titles = "collect", design = "AABB")
```
![pwork2](https://github.com/thomasp85/patchwork/assets/33577035/db8c2c1f-f77a-4c1a-bcd7-34cda78a1228)

**Comment by wagnnerms97** [comment]
axes = "collect" and axis_titles = "collect" it also doesn't work when using coord_equal


![image](https://github.com/thomasp85/patchwork/assets/143911682/b95ad337-0652-49e1-ba7f-720b4dc27486)


![image](https://github.com/thomasp85/patchwork/assets/143911682/4fc7340a-a782-4cc0-ba87-a3c86d1714ad)

**Comment by teunbrand** [comment]
With regards to the `coord_equal()` thingy, the axis/title merging does not seem to work there because the axes appear to be nested alongside panels and don't have the usual grob names.
