### ISSUE TITLE
Using plot arithmetic functions with `::` syntax?

### ISSUE THREAD

**Issue by petzi53** [thomasp85/patchwork#351]
Thank you for the wonderful package! 

My question: Is there a way to work with the plot arithmetic functions without loading and attaching the package via `library()`? I am referring to the `<package name>::<function>` syntax.

**Comment by mschilli87** [comment]
Can you give an example? Like code that works with calling `library` first so we could try to provide the alternative without it?

**Comment by Fan-iX** [comment]
I think use `patchwork:::"-.ggplot"(p1, p2)`.

For example:

```
patchwork:::"-.ggplot"(
  ggplot(iris)+geom_point(aes(Petal.Length,Petal.Width)),
  ggplot(iris)+geom_point(aes(Sepal.Length,Sepal.Width))
)
```

Available functions:

| operator | function |
|-|-|
| `+` | `ggplot2:::"+.gg"()` |
| `-` | `patchwork:::"-.ggplot"()` |
| `\|` | `patchwork:::"\|.ggplot"()` |
| `/` | `patchwork:::"/.ggplot"()` |
| `*` | `patchwork:::"*.gg"()` |
| `&` | `patchwork:::"&.gg"()` |

**Comment by petzi53** [comment]
@Fan-iX Thank you, that answers my question in all details! (I didn't anticipate that there would be different function calls for the different operators.)
