### ISSUE TITLE
`plot_layout(axes = "collect_y")` does not collect y axes correctly

### ISSUE THREAD

**Issue by psychelzh** [thomasp85/patchwork#354]
A simple example. The y axes for these two plots are indeed the same but collecting is not done. Tried corresponding `"collect_x"`, which works as expect.

``` r
library(ggplot2)
library(patchwork)
d <- data.frame(x = rnorm(5), y = factor(LETTERS[1:5]))
p1 <- d |> ggplot(aes(x, y)) + geom_point()
p2 <- d |> ggplot(aes(x, y)) + geom_point()
p1 | p2 + plot_layout(axes = "collect_y")
```

![](https://i.imgur.com/rc3mFH3.png)

``` r
p1 | p2 + plot_layout(axes = "collect")
```

![](https://i.imgur.com/DOHqxsq.png)

<sup>Created on 2024-03-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
You are running into operator precedence issues, which are super annoying but not something patchwork can control as it works at the language level

```
(p1 | p2) + plot_layout(axes = "collect_y")
```

gives you the correct plot

**Comment by psychelzh** [comment]
Ah, I am sorry for such disturbance. I did not realize this.

**Comment by psychelzh** [comment]
Given this is not really related to patchwork, I am closing this. Thank you very much for explanation.
