### ISSUE TITLE
Doesn't work with ggplot2 v3.5.0

### ISSUE THREAD

**Issue by mariadelmarq** [thomasp85/patchwork#355]
I've updated to ggplot2 v3.5.0, which has a few breaking changes. Patchwork no longer seems to work, anything I do results in the error:

```
Error in Ops.data.frame(guide_loc, panel_loc) : 
  ‘==’ only defined for equally-sized data frames
```

**Comment by thomasp85** [comment]
You need to update patchwork as well

**Comment by mariadelmarq** [comment]
Duh! I'm SO sorry about that, I assumed the breaking changes had been made after the latest update to patchwork (2 months ago). Thanks heaps!

**Comment by thomasp85** [comment]
no problem :-)
