### ISSUE TITLE
ggplot2 is corrupt

### ISSUE THREAD

**Issue by chamafelipe** [thomasp85/patchwork#36]
Hi @thomasp85 ,

Thanks for this awesome package. I'm running into a bit of trouble while trying to install it though. I get the following error message when I try to load patchwork:

```
> library(patchwork)
Error: package or namespace load failed for ‘patchwork’ in get(Info[i, 1], envir = env):
 lazy-load database '/usr/local/lib/R/3.4/site-library/ggplot2/R/ggplot2.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
```
After that, my ggplot2 becomes corrupt.

**Comment by thiagosfsilva** [comment]
Happened today with me too. Although the package did get installed, an attempt to use cowplot::plot_grid() immediately after patchwork was installed returned the "ggplot is corrupted error". Restarting the R session fixed the corrupting influences of patchwork, which then loaded and functioned correctly (as did plot_grid).

**Comment by mattmills49** [comment]
From Hadley himself, "Whenever you see "lazy-load database corrupted", the first thing to try is restarting R." https://github.com/r-lib/devtools/issues/942#issuecomment-144390231

I think it may have something to do with trying to install `patchwork` when `ggplot2` is already loaded in your environment but I'm not sure of that.

**Comment by dnlmc** [comment]
Had the same issue today. Per @mattmills49 comment, opened a new Rstudio window, successfully installed patchwork, then loaded the library into my previous R session with no trouble.

**Comment by ThomasPepperz** [comment]
> From Hadley himself, "Whenever you see "lazy-load database corrupted", the first thing to try is restarting R." [r-lib/devtools#942 (comment)](https://github.com/r-lib/devtools/issues/942#issuecomment-144390231)

@mattmills49

Hadley Hath Spoken!

**Comment by hafez-ahmad** [comment]
I insttaled tidyverse I again , I update ggplot separately then I am gettting this message 
Error: package or namespace load failed for ‘ggplot2’ in get(method, envir = home):
 lazy-load database 'C:/Users/hafez/Documents/R/win-library/3.6/ggplot2/R/ggplot2.rdb' is corrupt
In addition: Warning messages:
1: package ‘ggplot2’ was built under R version 3.6.3 
2: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
3: In get(method, envir = home) :
  restarting interrupted promise evaluation
4: In get(method, envir = home) : internal error -3 in R_decompress1
> mtcars %>%

**Comment by harshithasv16** [comment]
If you try to re-install the package which is already installed, you will get this error.
try to restart R, it worked for me
