### ISSUE TITLE
potential bug?

### ISSUE THREAD

**Issue by Yunuuuu** [thomasp85/patchwork#376]
I'm learning the patchwork project, since my work need lots modification of the `patchwork` package.
https://github.com/thomasp85/patchwork/blob/e4b0839e5448611ab69dd71811753357c87477c3/R/plot_patchwork.R#L865

I don't quite understand some codes here, so I'm unsure if I should make a pull request for this. Should this be a typos? the second `all_fixed_rows` maybe the `all_fixed_cols` variable?
`all(all_fixed_rows[as.character(a$rows)] == 1) || all(all_fixed_cols[as.character(a$cols)] == 1) `

**Comment by thomasp85** [comment]
Thank you!
