### ISSUE TITLE
Enhance patchwork

### ISSUE THREAD

**Issue by Yunuuuu** [thomasp85/patchwork#379]
I have created some features for patchwork, which will modifying the core codes of patchwork. I hope these features can be merged into patchwork. These functions are now deposited in https://github.com/Yunuuuu/ggalign (See scripts begin with `alignpatch-`)

1. `free_align`: if we want to compose plots without alignment of some panel axes (panel won't be aligned). we can wrap the plot with `free_align`. Note: this is different from `free` function (the current `free` function is much like the `wrap_elements()` function), it only free the selected axes.

```r
p1 <- ggplot(mtcars) +
    geom_point(aes(mpg, disp)) +
    ggtitle("Plot 1")

p3 <- ggplot(mtcars) +
    geom_point(aes(hp, wt, colour = mpg)) +
    ggtitle("Plot 3")

p5 <- ggplot(mpg, aes(class)) +
    geom_bar() +
    ylim(0, 65) +
    coord_flip()
```

```r
plot_grid(free_align(p3, "l"), p5, ncol = 1L)
```
![image](https://github.com/user-attachments/assets/4fab7af8-b56c-44ab-8e26-afeea26fc6ff)

2. `free_border`: If we want to compose plots without alignment of the panel borders (but still align the panels themselves), we can wrap the plot with `free_border`. This does the same work with cowplot::plot_grid by setting `axis` argument, we only align the panel, but border like axis titles won't be aligned. Note title, subtitle, and caption won't be aligned too. If you want to free axes and axes title, try to use `free_lab`

```r
plot_grid(free_border(p3, "l"), p5, ncol = 1L)
```
![image](https://github.com/user-attachments/assets/4c044310-25a7-4bd3-afe1-622dfefa6b48)

3. `free_lab`: Similar with `free_border`, but it will only operate the axis and axis title (labs). If we want to compose plots without alignment of the axis title, we can wrap the plot with `free_lab`. This should fix https://github.com/thomasp85/patchwork/issues/285, https://github.com/thomasp85/patchwork/issues/348 and https://github.com/thomasp85/patchwork/issues/110#issuecomment-615000426.

```r
plot_grid(free_lab(p3, "l"), p5, ncol = 1L)
```
![image](https://github.com/user-attachments/assets/25f73411-a4d7-45ab-9206-0a7e08248d9b)

4. `free_size`: Removing the ggplot element sizes when aligning, we ususally want to combine this with `free_border` to suspend the empty sized ggplot elements. Note the the second plot (on right-top), the left side of the panel won't count space when aligned. This help make more compact layout
```r
plot_grid(
  patchwork::plot_spacer(), 
  free_size(free_border(p5, "l"), "l"),
  p1, p3, nrow = 2L
)
```
![image](https://github.com/user-attachments/assets/6cd76937-05d6-40f5-b06f-a9e8310caedd)

**Comment by Yunuuuu** [comment]
5. collect guides for every position separately. 
```r
plot_grid(
  p3 + theme(legend.position = "top"), 
  p3 + theme(legend.position = "left"), 
  p3 + theme(legend.position = "bottom"), 
  p3 + theme(legend.position = "right"),
  nrow = 2L,
  guides = TRUE
)
```
![image](https://github.com/user-attachments/assets/dc6e4376-ab7f-400d-9dff-12aad75b499b)

**Comment by Yunuuuu** [comment]
If it's okay to merge these features (or some), I wound happy to make a commit in the patchwork project.

**Comment by thomasp85** [comment]
Thanks - I'm not sure I understand the distinction between `free_lab()` and `free_border()` - can you provide an example that shows where it differs?

**Comment by Yunuuuu** [comment]
Sorry for the missing example. The functions `free_lab()` and `free_border()` have a distinction in terms of placement on either the top or bottom side of the panel. Specifically, the top side contains the `title` and `subtitle`, while the bottom side contains the `caption`. `free_lab()` does not attach these elements in the panel area.

```r
p1_top <- ggplot(mtcars) +
    geom_point(aes(mpg, disp)) +
    ggtitle("Plot 1") +
    ggplot2::scale_x_continuous(position = "top")
plot_grid(p1_top, free_lab(p3))
```
![image](https://github.com/user-attachments/assets/ae55d470-4dd8-4e40-aa85-c941d3dc8555)

```r
plot_grid(p1_top, free_border(p3))
```
![image](https://github.com/user-attachments/assets/32be0fff-e52a-463e-a1cb-70fb1f920d12)

**Comment by thomasp85** [comment]
Ah, I see... thanks for the examples. 

I see at least a place for the functionality of `free_align()`, `free_lab()` and `free_size()` in patchwork. However, I think there is a minimally intrusive way of doing this on top of the `free()` functionality already provided which I'll try to pursue, so hold off a bit before you spend time porting your approach to patchwork

**Comment by Yunuuuu** [comment]
Thanks
