### ISSUE TITLE
API semantics

### ISSUE THREAD

**Issue by egnha** [thomasp85/patchwork#38]
Being more direct, patchwork's API is certainly a nice improvement over `gridExtra::grid.arrange()`. However, its use of `+` is somewhat awkward, semantically:

- It's used to juxtapose plots, but juxtaposition is not commutative.

- In an expression like `(ggplot(...) + ...) + (ggplot(...) + ...)`, the `+` inside the parentheses and the `+` between the parentheses are altogether different operators. Likewise, the two `+`'s in the expression `p1 + p2 + plot_layout(...)` are completely different (the first describes the topology of the layout, whereas the second describes a rigid geometric mapping onto a plane; `plot_layout()` and the like might be better off applied using `%>%`, say).

`*` might be a semantically more suitable as an operator for juxtaposition, since it is conventionally noncommutative and unused in ggplot2.

On the other hand, an advantage of using `+` is its familiarity from ggplot2. Maybe that's a good enough reason for patchwork ... (But unless I'm mistaken, I believe the author of ggplot2 considers its use of `+` as a less-than-optimal design.)

**Comment by thomasp85** [comment]
Short answer is that patchwork is an extension of the ggplot2 API, so all these considerations doesn’t matter - decisions have been made a long time ago...

Further, the argument concerning commutativety is a bit moot as using + in a non-algebraic sense has a rich history in programming, eg for concatenating strings...

**Comment by egnha** [comment]
Thanks for clarifying your stance. I understand. Sometimes a conceptual compromise helps in achieving a practical goal.
