### ISSUE TITLE
plot_layout axes = collect

### ISSUE THREAD

**Issue by ericKuo722** [thomasp85/patchwork#382]
Hi Thomas,

Thanks for your great work creating this package. I'm wondering if this package can be improved when collecting common axes for multiple plots. 

When I am doing plot_layout(axes = 'collect'). It collected all axes related stuff perfectly. However, I'm wondering if any new command that can collect axes title and axes value while keeping axes line since I want to keep axes lines (both x and y lines) for all the plots I have in this layout.

Thank you very much and looking forward to hearing from you.

Thanks,
Eric

**Comment by teunbrand** [comment]
One should be able to just do `& annotate("segment", x = I(0), y = I(0), yend = I(1))` to put a line in every panel. If this should be controlled from patchwork, I can imagine both the graphics wrangling and user-facing components becoming gnarly.

**Comment by thomasp85** [comment]
I read it as wanting to keep the ticks _and_ line, but maybe I'm mistaken

**Comment by teunbrand** [comment]
The foremost issue I see is that you need access to the full axis to do collection comparisons, but you'd need unlabeled axes for rendering the interior parts. You can dig around into the grobs to make unlabeled axes out of full axes, but I wouldn't recommend this.

**Comment by thomasp85** [comment]
I agree. Closing this

**Comment by ericKuo722** [comment]
Thank you guys. You are right, facet_wrap is another way to do it.

**Comment by gremms1** [comment]
I came across this post looking for a solution to a similar problem. The solution I came up with is grouping the plots where I want the axis text removed in the patch I make, and then use theme(axis.text.x = element_blank()) on those. For example:

`p4 <- (p1/p2 & theme(axis.text.x = element_blank()))/p3   # Remove x-axis text for the top two plots`
