### ISSUE TITLE
mix `free` type gave wrong result

### ISSUE THREAD

**Issue by Yunuuuu** [thomasp85/patchwork#385]
``` r
library(patchwork)
library(ggplot2)
p1 <- ggplot(mtcars) +
    geom_point(aes(mpg, disp)) +
    ggtitle("Plot 1")

p2 <- ggplot(mtcars) +
    geom_boxplot(aes(gear, disp, group = gear)) +
    ggtitle("Plot 2")

p3 <- ggplot(mtcars) +
    geom_point(aes(hp, wt, colour = mpg)) +
    ggtitle("Plot 3")


p4 <- ggplot(mtcars) +
    geom_bar(aes(gear)) +
    facet_wrap(~cyl) +
    ggtitle("Plot 4")

p5 <- ggplot(mpg, aes(class)) +
    geom_bar() +
    ylim(0, 65) +
    coord_flip()
wrap_plots(
    free(
        free(wrap_plots(p1, p2, p3, p4, heights = 1L), "label", side = "l"),
        "panel",
        side = "t"
    ),
    p4, p5, plot_spacer(),
    ncol = 2L
)
```

![image](https://github.com/user-attachments/assets/a718a3e1-fa0b-41a7-b55e-51f67402fd91)

<sup>Created on 2024-09-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
~                                

What I expect is something like this:
![image](https://github.com/user-attachments/assets/da672eb7-0a32-4e57-92ea-dc78a543c41b)

The left panel of the nested patchwork should be aligned

**Comment by thomasp85** [comment]
Thanks - there are potentially some edge cases I've yet to test so please report them if you find it

**Comment by thomasp85** [comment]
Ah, I see what's going on - you can't mix free versions on various sides right now. Should throw a warning

**Comment by thomasp85** [comment]
or, maybe I can actually allow it... I'll have a look
