### ISSUE TITLE
`free` with fixed aspect ratio plot failed

### ISSUE THREAD

**Issue by Yunuuuu** [thomasp85/patchwork#387]
``` r
knitr::opts_knit$set(upload.fun = identity)
library(patchwork)
library(ggplot2)
p4 <- ggplot(mtcars) +
  geom_bar(aes(gear)) +
  facet_wrap(~cyl) +
  ggtitle("Plot 4")

p_f <- ggplot(mtcars) +
  geom_point(aes(hp, disp)) +
  coord_fixed() +
  ggtitle("Fixed Aspect")
wrap_plots(free(p_f, "panel", "b"), p4)
```

![](fast-perch_reprex_files/figure-gfm/unnamed-chunk-2-1.png)

<sup>Created on 2024-09-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
~                                                         
~                                                         
~                                                         
~                                    
![image](https://github.com/user-attachments/assets/e429868b-5a03-4abc-bb79-3e55a836fb5d)

What I expect is something like this:
![image](https://github.com/user-attachments/assets/7a5f47b8-b775-4b83-a1e0-584993e5ac5c)

**Comment by thomasp85** [comment]
Thanks for all these tests and reports
