### ISSUE TITLE
Cannot arrange plots in the right order

### ISSUE THREAD

**Issue by tungmilan** [thomasp85/patchwork#4]
The following example is taken from the [`egg` package](https://github.com/baptiste/egg)  

**Desired output plus labels:**

![image](https://user-images.githubusercontent.com/6590141/33703137-a99c13b6-dadb-11e7-95a1-83a42c25f374.png)

**Code:**

```
p1 <- ggplot(mtcars, aes(mpg, wt, colour = factor(cyl))) +
  geom_point() + ggtitle("a)")

p2 <- ggplot(mtcars, aes(mpg, wt, colour = factor(cyl))) +
  geom_point() + facet_wrap(~ cyl, ncol = 2, scales = "free") +
  guides(colour = "none") +
  theme() + ggtitle("b)")

p3 <- ggplot(mtcars, aes(mpg, wt, colour = factor(cyl))) +
  geom_point() + facet_grid(. ~ am, scales = "free") + 
  guides(colour="none") +
  ggtitle("c)")

{p1 + {p2} + patchwork::plot_layout(ncol = 1)} +
  p3 + patchwork::plot_layout(ncol = 2)

```
![rplot](https://user-images.githubusercontent.com/6590141/33703271-4b4fe91c-dadc-11e7-8a18-45f9ad3e8aad.png)

**This worked but wrong order**

```
p3 + {
  p1 + {p2} + patchwork::plot_layout(ncol = 1)
} +
  patchwork::plot_layout(ncol = 2)
```

![rplot01](https://user-images.githubusercontent.com/6590141/33703284-59279292-dadc-11e7-8721-25802d5e9ff0.png)

How can I fix it? Thanks!

**Comment by thomasp85** [comment]
Try:

```r
{
  p1 + {p2} + patchwork::plot_layout(ncol = 1)
} / p3 +
  patchwork::plot_layout(ncol = 2)
```

**Comment by thomasp85** [comment]
The division operator was added for exactly this use case...

**Comment by mjsmith037** [comment]
This solution does not appear to work any longer (produces output identical to op's first example figure). Specifically:
`p1 + {p2 + p3 + plot_layout(ncol=1)}` produces one plot spanning two rows on left, but `{p2 + p3 + plot_layout(ncol=1)} / p1 + plot_layout(ncol=2)` produces a plot only spanning one row on the right.
