### ISSUE TITLE
patchwork uses non-standard versions of rlang and ggplot2?

### ISSUE THREAD

**Issue by apsteinmetz** [thomasp85/patchwork#40]
Patchwork seems to download and compile from sources a custom version of rlang and download a custom version of ggplot2.  That seems unorthodox, or maybe it's just me.   A good-2-go binary of patchwork that works with the CRAN versions of the dependencies would obviously be ideal.

**Comment by thomasp85** [comment]
This is simply because patchwork is still in development and uses an unmarked PR from ggplot2 until it gets merged in... CRAN release will happen once ggplot2 gets updated
