### ISSUE TITLE
Add option to add a title to the combined plot

### ISSUE THREAD

**Issue by adrfantini** [thomasp85/patchwork#41]
It'd be nice if one could add a plot title for the whole complete plot. Currently `+` and `*` add the title to the last plot only, while `&` adds one title per plot.

Reprex:

```
library(ggplot2)
library(patchwork)
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p1 + p2 * ggtitle("test")
p1 + p2 & ggtitle("test")
p1 + p2 + ggtitle("test")
```

**Comment by thomasp85** [comment]
Use `plot_annotation()` to add title etc to the full plot

**Comment by adrfantini** [comment]
Whoopsie doopsie. Thanks. Would be nice to have this added to the vignette in the front page.

**Comment by Z3tt** [comment]
Hi Thomas, seems to me that the title font gets cut when using `plot_annoation()` with a custom font:

``` r
library(ggplot2)
#> Warning: Paket 'ggplot2' wurde unter R Version 3.5.2 erstellt
library(patchwork)

theme_custom <- theme_bw() %+replace% 
  theme(plot.title = element_text(size = 20, face = "bold", family = "Poppins"))

theme_set(theme_custom)

(ggplot(mtcars, aes(wt, mpg)) + geom_point()) +
  (ggplot(mtcars, aes(disp, qsec)) + geom_point()) +
  plot_annotation(title = glue::glue('For example: i, "", S and g'))
#> Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
#> Zeichensatzfamilie in der Windows Zeichensatzdatenbank nicht gefunden
#> Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
#> Zeichensatzfamilie in der Windows Zeichensatzdatenbank nicht gefunden
```

![](https://i.imgur.com/cCeB3g8.png)

<sup>Created on 2019-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It is not due to the font size, the problem remains in case of smaller font sizes as well. Glad for any feedback on this.

Cheers, Cédric
