### ISSUE TITLE
Error: Don't know how to add o to a plot

### ISSUE THREAD

**Issue by peterch405** [thomasp85/patchwork#42]
When `ggtern` is loaded
```
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p1 + p2
```

Produces: Error: Don't know how to add o to a plot

**Comment by thomasp85** [comment]
`ggtern` overwrites key aspects of ggplot2 and cannot be expected to play nice with other extensions. While I will not rule it out, I have no plans on supporting it for these reasons

**Comment by KarenSchleeweis** [comment]
I don't have ggtern and I get the same error...

**Comment by thomasp85** [comment]
Can you provide a reproducible example?

**Comment by jinqiangyan** [comment]
hi your code 'ggplot(mtcars)' is duplicated.  In other ways, p1 and p2  are two graphs as your code. You should code like this:
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- p1+ geom_boxplot(aes(gear, disp, group = gear))
p1 + p2

It works!

**Comment by knowah** [comment]
For others coming across this issue, it was a conflict with the `ggbio` package which I had previously loaded. Running `unloadNamespace("ggbio")` eliminated this error.

**Comment by jayoung** [comment]
thanks, @knowah - just had the same problem with ggbio: glad to find this.

**Comment by rcorty** [comment]
> `ggtern` overwrites key aspects of ggplot2 and cannot be expected to play nice with other extensions. While I will not rule it out, I have no plans on supporting it for these reasons

Could/should`ggtern` be changed so as not to overwrite these things?  Or is that fundamental/necessary to its function?

**Comment by claireatati** [comment]
thank you so much @knowah . I ran into this problem in the middle of a test so much appreciated.
