### ISSUE TITLE
Integration with ggiraph

### ISSUE THREAD

**Issue by instantkaffee** [thomasp85/patchwork#44]
I like the tandem of ggplot2 and ggiraph to easily create interactive plots, i.e. with tooltip features.
Is there a way to extend patchwork to allow same integration?

**Comment by thomasp85** [comment]
I don’t think so - in any case it would be out of scope for patchwork. Maybe you could hear the developer of ggiraph whether he will/can support patchwork plots once patchwork has been properly released
