### ISSUE TITLE
GH PR of ggplot 2405 doesnt exist

### ISSUE THREAD

**Issue by yonicd** [thomasp85/patchwork#45]
```
remotes::install_github("tidyverse/ggplot2#2405")
Error in github_resolve_ref.github_pull(meta$ref %||% ref, meta) : 
  Cannot find GitHub pull request tidyverse/ggplot2#2405`
```

**Comment by thomasp85** [comment]
Is this a consistent issue? I don't have any problems at my end...

**Comment by mvkorpel** [comment]
I also get this error when trying to install `patchwork` with `remotes::install_github()`, but using `devtools::install_github()` as instructed in `README.md` does work.

**Comment by thomasp85** [comment]
Thanks - must be an issue with `remotes` then

**Comment by thomasp85** [comment]
Closed as PR branch is merged
