### ISSUE TITLE
Adjust space between plots?

### ISSUE THREAD

**Issue by tvedebrink** [thomasp85/patchwork#46]
Is it possible to adjust the amount of spacing between plots? In some applications you would like `wrap_plots()` to act as an ordinary facet in ggplot - is it possible to collapse the white space to nothing?

Tak/Thanks!

**Comment by thomasp85** [comment]
There is no space between the added plots in patchwork - any space is due to the plots own margin. One fix would be to change the margins in all plots using `& theme(plot.margin = ...)` after assembly

**Comment by tvedebrink** [comment]
Ahh.. Thanks!

**Comment by tjebo** [comment]
Another option is to make another row with an empty plot (e.g. ggplot() + theme_void()) and adjust its height in plot_layout

**Comment by epruesse** [comment]
> Of course, I mainly read the part on "Is it possible to **adjust** the amount of spacing between plots?', and since I was looking to **increase**- which is also adjusting - the space, and google suggested this page, and finally found my solution, I thought it was nice to add for future searchers.

Correct. Now consider `p1 + plot_spacer() + p2 + plot_layout(widths = c(4, -1, 4))`. The magic of adding negative numbers. (Not sure what weirdness this may produce with the grid underneath, but it does seem to work.)

**Comment by LafontRapnouilTristan** [comment]
Hi - Thanks for the amazing package!

Just to add to this discussion with my own experience on the matter.
`plot_spacer()` as some margins that can be removed like that:
```
custom_spacer <- plot_spacer()+
                  theme(plot.margin = unit(c(0, 0, 0, 0),"lines"))
```
