### ISSUE TITLE
save as .eps does not work

### ISSUE THREAD

**Issue by marcosci** [thomasp85/patchwork#47]
Hey Thomas,

first of all - i really like patchwork, makes me spend much less time in inkscape :stuck_out_tongue: 

Anyways, can you imagine why it doesn't work to save a patchwork plot as .eps?

Minimal example:

``` r
# install.packages("ggplot2")
# load package and data
options(scipen=999)  # turn-off scientific notation like 1e+48
library(ggplot2)
library(patchwork)
data("midwest", package = "ggplot2")
# midwest <- read.csv("http://goo.gl/G1K41K")  # bkup data source

# Scatterplot
gg <- ggplot(midwest, aes(x=area, y=poptotal)) + 
    geom_point(aes(col=state, size=popdensity)) + 
    geom_smooth(method="loess", se=F) + 
    xlim(c(0, 0.1)) + 
    ylim(c(0, 500000)) + 
    labs(subtitle="Area Vs Population", 
         y="Population", 
         x="Area", 
         title="Scatterplot", 
         caption = "Source: midwest")

p <- gg + gg

ggsave("test.eps")
```

... everything I get is a grey box after opening the file?

**Comment by ConorIA** [comment]
I could save [the image](https://cloud.conr.ca/s/MrGZyrk2xpEwdyr) using the code you provided above.

**Comment by emiltb** [comment]
I tested your code both on Windows 10 and Ubuntu 16.04.3 (RStudio Cloud) and it seems to run just fine. Does it make a difference if you specifiy the plot in ggsave, e.g. `ggsave("test.eps", plot = p)`?

**Comment by marcosci** [comment]
that's it.
Got my hands on a windows machine where last_plot() does its job, but not on my linux machines.

did it work for you without the `plot = p`?

**Comment by emiltb** [comment]
> did it work for you without the `plot = p`?

Yes, it worked for me without `plot = p` on Windows and Linux

**Comment by marcosci** [comment]
Weird. Both ggplot2 and patchwork are on all three machines installed with the development version, so this can't be a source for the error, or?

As I don't know how to reproduce it, you can also close it here ... will came back with something if I find out what it was.

**Comment by thomasp85** [comment]
The “issue” is that patchwork has yet to be updated to take advance of the exported set_last_plot function. But I’ll close - feel free to reopen if something comes up
