### ISSUE TITLE
Error handling when assembling plots

### ISSUE THREAD

**Issue by mschubert** [thomasp85/patchwork#48]
I'm using patchwork to generate a multi-page PDF of assembled plots using different underlying data. Think of it as your `README` example

```r
library(ggplot2)
library(patchwork)
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p1 + p2
```

but instead of this one plot I am plotting it for `n` different cars.

However, not all cars have got the exact same underlying data, and some may be missing a field in their `data.frame` that causes `ggplot` to produce an error when building the subplot. An example for this is when I use `facet_wrap` on a variable that has no observations.

So far, I check each of these errors manually using the code:

```r
if (class(try(ggplot_build(p1))) == "error")
    p1 = element_blank()
if (class(try(ggplot_build(p2))) == "error")
    p2 = element_blank()
# ... same for every element
```

This way, however, I have the build the plot twice: once for checking if it can be built, and once to actually assemble it via `patchwork`.

It would be nice if `patchwork` could handle failed plots automatically, by either leaving them empty or plot the error message instead of the panel.

One option could be to include an error handling function in `plot_layout`:

```r
p1 + p2 + plot_layout(error = function(e) element_blank())
p1 + p2 + plot_layout(error = function(e)
    ggplot(data.frame(error=e), aes(x=1, y=1)) + annotate(label=e))
```

**Comment by thomasp85** [comment]
I'll consider it but we're venturing very close to the edge of this packages responsibility...

**Comment by mschubert** [comment]
All I'm asking is that you consider it :+1: 

However, if it is not the responsibility of *patchwork*, the responsibility of which package should it be?

**Comment by thomasp85** [comment]
I think it is up to the user to not make plots that throws errors

**Comment by mschubert** [comment]
I see your point, and this easily applies to making a single plot.

For assembling many plots, I could also see the user to define their own function to weed out bad plots before they are to be assembled:

```r
replace_plot_errors_with_blank = function(..., envir=parent.frame()) {
    plot_list = list(...)
    for (pn in names(plot_list)) {
        if (class(try(ggplot_build(plot_list[[pn]]))) == "error")
            assign(pn, element_blank(), envir=envir)
    }
}
```

This could very well be preferable to making the *patchwork* API more complex.
