### ISSUE TITLE
subplot title margins change when coordinates are fixed

### ISSUE THREAD

**Issue by tclavelle** [thomasp85/patchwork#51]
Hi Thomas,

When making a multi-panel map plot, I discovered that the margins between the subplots and their titles changed compared to when just viewing the subplots by themselves. 

Reproducible example below:

```
library(tidyverse)
library(broom)
library(rworldmap)
library(patchwork)

# Use country polygons for example
cntrys <- tidy(countriesCoarse)

# Plot A
pA <- ggplot(cntrys, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "#375166") +
  coord_fixed(xlim =c(-85.5,-57.4),ylim = c(9.95,30)) + # bug appears to be related to using fixed coordinates
  labs(title = "Blue map",
       subtitle = "The world is very blue") +
  theme_minimal()

# Print individual plot - title margin looks fine
pA

# Plot B
pB <- ggplot(cntrys, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "#BE2A28") +
  coord_fixed(xlim =c(-85.5,-57.4),ylim = c(9.95,30)) +
  labs(title = "Red map",
       subtitle = "The world is very red") +
  theme_minimal()

# Print multipanel plot
pA + pB + plot_layout(ncol = 1)
```

I believe the issue is related to using `coord_fixed()` - the problem goes away when this is not used and only effects the subplots that use `coord_fixed()`

**Comment by thomasp85** [comment]
Just to understand you correctly - Are you referring to the fact that the titles are now no longer aligned with the plot, but with the "page"?

If so, this is intended as it makes the titles align with non-fixed plots...

In general, assembling fixed-aspect plots is a mess :-)

**Comment by tclavelle** [comment]
My concern is actually about the amount of whitespace introduced between the titles and the plots. For a two panel plot there is a lot of whitespace and that may be problematic for some people given the figure formatting guidelines of many journals.

**Comment by tclavelle** [comment]
I just made sure R and all packages were updated to the latest versions and the issue has gone away... Sorry for the hassle/erroneous issue! 

In case you're interested, the above code was giving the following outputs prior to updating:

![patchwork_issue_mapa](https://user-images.githubusercontent.com/8162599/40079431-c9857d46-583c-11e8-9f5e-83d53d97cd3d.png)

![patchwork_issue_mapb](https://user-images.githubusercontent.com/8162599/40079439-cd665796-583c-11e8-9ce1-19f2e6870639.png)

**Comment by thomasp85** [comment]
Happy it got fixed
