### ISSUE TITLE
Using patchwork with ggpairs

### ISSUE THREAD

**Issue by mgargiulo** [thomasp85/patchwork#52]
Are there plans to get `patchwork` integration with `ggpairs`? I'm getting an error that says "Error: Don't know how to add e2 to a plot"

**Comment by thomasp85** [comment]
No - I will not add support for any package that does not return valid ggplot objects, simply because it would result in a maintenance hell. Package developers are free to add infrastructure to their packages that makes their graphics work well with patchwork
