### ISSUE TITLE
Plots using `coord_fixed()` are not using available space

### ISSUE THREAD

**Issue by mschubert** [thomasp85/patchwork#53]
First off, great work and I started using the package almost daily!

I was wondering what are your thoughts on arranging the canvas space plots take if one of two is adjustable and the other is not.

Considering the following example:

```r
cars = tibble::rownames_to_column(mtcars, "name")
p1 = ggplot(cars, aes(x=vs, y=name)) + geom_tile() + coord_fixed()
p2 = ggplot(cars, aes(x=disp, y=name)) + geom_point()
p1 + p2
```

Here, the width of `p1` is defined given its height because of `coord_fixed()`, and the width of `p2` adapts to the canvas size if plotted in isolation. (Resize plot in x and y direction to make this more obvious.)

The way *patchwork* currently handles this is to assume `p1` and `p2` will occupy half of the canvas, unless otherwise specified by `plot_layout()` (which I do not always know in advance).

It would be nice if there was a way to tell `p2` to fill up the available space (or it would do so automatically when `p1` is of fixed size).

**Comment by thomasp85** [comment]
The reason for the current implementation is that it scales better. It is true that if one only consider a single row or column of plots, then space could be distributed more efficiently, but once the layout begins to consist of multiple rows and columns it is much more difficult to derive the best distribution of space

**Comment by mschubert** [comment]
Maybe there is no reason to automatically derive the best layout, but make it user responsibility to decide which plots to group (using parentheses or `plot_layout`) to arrive at an unambiguous layout?

For instance, the example above could be part of a larger plot but `p1` and `p2` are grouped so the canvas extension only applies between them (explicitly using e.g. `widths=NA` or implicitly).
