### ISSUE TITLE
Adding labels 

### ISSUE THREAD

**Issue by biorelated** [thomasp85/patchwork#6]
Maybe I am missing it but, 
Is it possible to add labels to the plots?
For example
`myplot <- (p1 + p2, labels=c("A","B"))`

Labelling the plots is really useful for publications and orientating the audience.

**Comment by llrs** [comment]
I posted the same in  #1, the solution proposed is using `p1+ labs(subtitle:"A") + p2 +labs(subtitle = "B")`

**Comment by biorelated** [comment]
Thanks! I follow the logic in #1 but what about when you have reserved the subtitle for a specific description of the plot? Maybe ggplot2 needs to define a plot label macro but maybe it is not of priority. The cowplot package does enable this feature though I am not sure how it is implemented under the hood.

**Comment by thomasp85** [comment]
I will not decisively rule out that some functionality might not be added, but I do believe the vast majority of use cases can be handled by #1. Having both title and subtitle for all subplots will in most cases lead to a very cluttered visual, so often one of them can be used for labels

**Comment by m-macaskill** [comment]
If `title` and `subtitle` are in use, you could try the `tag` option, which is displayed a bit further to the side and so might be of more use in the general case anyway, e.g. 
`p1 + labs(tag = 'A') + p2 + labs(tag = 'B')`
