### ISSUE TITLE
Factor out core table merging code?

### ISSUE THREAD

**Issue by clauswilke** [thomasp85/patchwork#60]
I'm wondering whether it's possible to factor out the core table merging code and make it more general. The reason why I'm asking is because if we ever want better legend formatting options with multiple legends in ggplot2, we'll need similar code to what patchwork does with entire plots. And if we could share code between plot arranging and legend arranging that would be great.

I have looked over the patchwork code and I can't say I understand how it works, but it doesn't seem to contain a lot of ggplot2-specific logic.

**Comment by thomasp85** [comment]
The general logic is basically what constitutes `gtable`. While it doesn't appear ggplot2-specific it is on a very fundamental level. Every plot is converted to a 18x15 table using information from the ggplot2 gtable representation to figure out which cells are part of the plotting area etc.

So, at least at this point in time I'm not sure to what degree anything can be factored out ( I can probably use some experience from this on the ggplot2-legend rewrite though)
