### ISSUE TITLE
Plot assembly fails on minimal plots

### ISSUE THREAD

**Issue by clauswilke** [thomasp85/patchwork#61]
Just ran into this:
``` r
library(ggplot2)
library(patchwork)
p1 <- ggplot() + ggtitle("plot1")
p2 <- ggplot() + ggtitle("plot2")
p1 + p2
#> Error: $ operator is invalid for atomic vectors
```

Created on 2018-06-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
huh - weird... must be some changes in ggplot2...

Thanks

**Comment by thomasp85** [comment]
Ah - I know... the reason is that an empty plot is considered a placeholder for something to come. If a plot contains no data and no layers it will get replaced by the next plot in line... Here you are effectively adding two nothings

error message could be better though...

Do you have a valid use case for doing the above? if so I'll need to rethink the placeholder strategy...

**Comment by clauswilke** [comment]
I'm not sure what I wanted to do with this particular example. Possibly make a reprex for plot titles with different descenders. In any case, I can see how in interactive use one might sometimes want to throw in an empty `ggplot()` as a placeholder for things to come. The current behavior of dropping empty plots is unexpected and confusing (see example below).

This seems similar to me to how `ggplot()` itself has developed. In early versions, not adding any layers was not allowed and it would throw an error. Later, it was decided that empty plots are valid. I think that, for consistency, this is the correct behavior.

``` r
library(ggplot2)
library(patchwork)

df <- data.frame(x = 1)

p1 <- ggplot(df, aes(x, x)) + geom_point()
p2 <- ggplot()

p1 + p2 + p1
```

![](https://i.imgur.com/XI3p6pW.png)

``` r
(p1 + p2)/p1
```

![](https://i.imgur.com/UpmFBs6.png)

``` r
(p1 + p1)/p1
```

![](https://i.imgur.com/wlVJqX2.png)

Created on 2018-06-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
