### ISSUE TITLE
Start plot_annotation() labels from input value

### ISSUE THREAD

**Issue by snystrom** [thomasp85/patchwork#63]
Some of my use-cases require making a plot that includes panels that are not ggplot objects. It would be great if `plot_annotation()` could be told which letter/number/numeral to start from in its labeling.

Alternately, is it currently possible (or easier to implement) to pass a vector of custom annotations?

**Comment by thomasp85** [comment]
It is not currently possible but I might consider adding it

**Comment by pforny** [comment]
Is this option available now? I would very much like to label the blanks created by plot_spacer(). Thanks! :)

**Comment by ahdee** [comment]
@snystrom you could just add your customize ( for example say u want to start with E) like this: 

```
d=ggplot()

d + d + plot_annotation(tag_levels = list(c('E', 'F'), '1'))
```
