### ISSUE TITLE
Which theme element controls the appearance of tag_levels in plot_annotation?

### ISSUE THREAD

**Issue by MikkoVihtakari** [thomasp85/patchwork#67]
Great package you have written! I am trying to change the font size and face of subplot letters generated using `plot_annotation`. I assume from the documentation that this could be done using the theme argument, but don't seem to find which theme element controls `tag_levels`. Any suggestions?

None of the attempts under seem to work:

```
p1 <- ggplot(data.frame(x = 1, y = 1), aes(x = x, y = y)) + geom_point()

p1 + p1 + plot_annotation(tag_levels = "A", theme = theme(title = element_text(size = 20, face = 2)))
p1 + p1 + plot_annotation(tag_levels = "A", theme = theme(text = element_text(size = 20, face = 2)))
p1 + p1 + plot_annotation(tag_levels = "A", theme = theme(plot.title = element_text(size = 20, face = 2)))
p1 + p1 + plot_annotation(tag_levels = "A", theme = theme(plot.subtitle = element_text(size = 20, face = 2)))

```

**Comment by thomasp85** [comment]
Tags are part of each separate plot and are thus modified with the theme settings for each individual plot using the plot.tag theme element. To modify all plot themes simultaneously use the `&` as shown in the readme
