### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by ningyawei** [thomasp85/patchwork#7]
I tried to intall the patchwork package, but failed, The problem is as follows，can you help me？
（ the R version in my computer is 3.4.3, and the ggplot2 version is 2.2.1）

* installing *source* package 'patchwork' ...
** R
** preparing package for lazy loading
Error : object 'ggplot_add' is not exported by 'namespace:ggplot2'
ERROR: lazy loading failed for package 'patchwork'
* removing 'C:/Users/nyw/Documents/R/win-library/3.4/patchwork'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by thomasp85** [comment]
You need the development version of `ggplot2` for patchwork to work.

Try:

```r
devtools::install_github('tidyverse/ggplot2')
```

**Comment by ningyawei** [comment]
My problem is solved，thanks！
