### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by keithhurley** [thomasp85/patchwork#72]
Is it possible to control the "overall" background of the plots.  For example, if I use dark backgrounds or transparent backgrounds on the individual plots, the "empty" space on the canvas between individual plots is always white.  Is there a way to "theme" the overall canvas?

**Comment by tpinck27** [comment]
I have the exact same question.

Here's a reproducible example
```
library(tidyverse)
library(patchwork)

df_1 <- tibble(x = c(1:10), y = rnorm(10))
df_2 <- tibble(x = c(1:10), y = rnorm(10))

pl_1 <- df_1 %>% 
  ggplot(aes(x, y))+
  geom_line()+
  geom_point()+
  theme(plot.background = element_rect(fill = 'lightgrey'),
        panel.background = element_rect(fill = 'lightgrey'))+
  labs(title = 'This individual Plot has a grey background')

pl_1

pl_2 <- df_1 %>% 
  ggplot(aes(x, y))+
  geom_line()+
  geom_point()+
  theme(plot.background = element_rect(fill = 'lightgrey'),
        panel.background = element_rect(fill = 'lightgrey'))+
  labs(title = 'Together, the plot background is white')

pl_2 + pl_2
```

**Comment by krassowski** [comment]
Or event better, allow for watermarks as does [cowplot](https://cloud.r-project.org/web/packages/cowplot/vignettes/introduction.html)

**Comment by thomasp85** [comment]
`&` a theme will now also set the theme of the patchwork

**Comment by AlinaBW** [comment]
Is is possible to select an entirely transparent background theme for the entire canvas?

**Comment by HijaziHassan** [comment]
> Is is possible to select an entirely transparent background theme for the entire canvas?

Have you tried this? 

```
& theme(plot.background = element_rect(fill='transparent'),
                legend.background = element_rect(fill = 'transparent')
)
```
