### ISSUE TITLE
Documentation for plot_spacer()

### ISSUE THREAD

**Issue by steveharoz** [thomasp85/patchwork#73]
It took some tinkering to figure out how to control the spacing added by `plot_spacer()`.  Maybe add some examples to the docs:

`plot1 / plot2 #too little space`
`plot1 / plot_spacer() / plot2 #too much space`
`(plot1 / plot_spacer() / plot1) + plot_layout(ncol=1, heights = c(1, 0.1, 1))`

Also, I'm sure there's a way to pad each plot using `theme()`, but the parameters are overwhelming to a lot of people. An example of how to add a margin to the right/bottom of a plot would be very helpful.

**Comment by thomasp85** [comment]
Indeed - documentation is still lacking. PRs are welcome as I currently focus on gganimate
