### ISSUE TITLE
legend.justification not preserved

### ISSUE THREAD

**Issue by melissakey** [thomasp85/patchwork#75]
My end goal is to produce a pair of plots with a shared legend.  I didn't see this implemented in patchwork yet (although I see a few issues reports which suggest it's on the to-do list - count me in as interested!).  In the meantime, I decided my optimal solution was to produce a horizontal legend across the bottom of one plot, and align it to the right-hand side of the right-most plot.  On an individual graph, this would be changed using `legend.position = bottom` and `legend.justification = right` in `theme()`.  When combining the plots using patchwork, the justification option is ignored and the legend is centered in the graph.  (This is made very obvious if the legend is longer than the graph, and part of it is cut-off).  Here's a reproducible example which illustrates the issue:

``` r
data(iris)
library(ggplot2)
library(patchwork)
library(magrittr)

p1 <- iris %>%
  ggplot(aes(x = Sepal.Length, y = Sepal.Width, color = Petal.Length, shape = Species)) + 
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.position = "bottom",
    legend.justification = "left",
    legend.direction = "horizontal",
    legend.box = "horizontal",
    # legend.background = element_blank(),
    # legend.margin = margin(3, .5, .5, .5, "lines"),
    # legend.key.height = unit(1, "lines")
  ) + 
  geom_point()
p1
```

![](https://i.imgur.com/Nf27kCS.png)

``` r

p2 <- p1 +
  theme(legend.position = 'none') + 
  aes(x = Petal.Length)
p2
```

![](https://i.imgur.com/RWjiPKV.png)

``` r

# justification is now centered, not left-aligned (title "Petal.Length" cut off)
p1 + p2
```

![](https://i.imgur.com/sXGyM6E.png)

``` r

p3 <- p1 + theme(
  legend.justification = 'right'
)
p3
```

![](https://i.imgur.com/W3Xjscs.png)

``` r

# same thing on right-hand side
p2 + p3
```

![](https://i.imgur.com/PHfOZbS.png)

Created on 2018-08-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
This is, surprisingly, an issue in ggplot2. The guide alignment only seem to work if there is enough space for all the guides (you can check by making the patchwork plot super wide and see that it resolves itself). I'm closing as there's nothing I can do on the patchwork side (and guide collection is now implemented), but you should open an issue in ggplot2 as it is a bug

**Comment by melissakey** [comment]
Thank you for the update!  I opened an issue for ggplot2 – and I’m now wishing I’d checked things on a single plot before opening the issue in patchwork.  Probably would have saved a lot of time.

Thanks for your work on patchwork – I use it all the time!

Melissa
