### ISSUE TITLE
Add example how to use the "guides" argument of plot_layout

### ISSUE THREAD

**Issue by paljenczy** [thomasp85/patchwork#78]
Neither in wrap_plots, nor in plot_layout there is an example that shows how to use the 'guides' argument. What are the different options?

**Comment by llrs** [comment]
I'm sure Thomas has this in the radar as it is related to the issue he opened in #15

**Comment by thomasp85** [comment]
Yeah - it doesn’t do anything currently. Just a promise of things to come🙂
