### ISSUE TITLE
Allow using wrap_elements on gLists and so on

### ISSUE THREAD

**Issue by flying-sheep** [thomasp85/patchwork#79]
I found that `as.grob.gList <- function(x, ...) grobTree(x)` works, but idk if it’s the best way.

The other grid classes such as `gTree` should also be supported.

**Comment by steveharoz** [comment]
Thank you @flying-sheep. For now, only ggplot objects are supported.

**Comment by flying-sheep** [comment]
Any reason you don’t want to add the tiny line I mentioned to the codebase?

**Comment by steveharoz** [comment]
I see now. Closing this was a mistake on my part. I'll reopen it.

**Comment by flying-sheep** [comment]
Awesome, thank you!
