### ISSUE TITLE
Plans / timline for CRAN release?

### ISSUE THREAD

**Issue by cboettig** [thomasp85/patchwork#82]
Hey @thomasp85 , 

I've been a big fan of this package for a while now, just wanted to check in to see if you had plans for a CRAN release in the not-to-distant future?  

Thanks for considering!

**Comment by daroczig** [comment]
Can we please keep this ticket open until the CRAN release happens so that interested parties can subscribe to this thread and get notified?

**Comment by tvatter** [comment]
Same question :)
