### ISSUE TITLE
Slight axis label misalignment with superscripts

### ISSUE THREAD

**Issue by aosmith16** [thomasp85/patchwork#83]
Using a superscript in one axis label makes the axis labels slightly mis-aligned after combining the plots.  It's all fairly subtle, but I *think* other aspects of the plot align just fine.

I only noticed this because my axis labels were so long that they overlapped.  The label with the superscript is slightly "too high".

``` r
library(ggplot2)
library(patchwork)

dat = data.frame(x = 10, y = 5)

p1 = ggplot(data = dat, aes(x, y)) +
     ylab("Something really long here for a y label")
     
p2 = ggplot(data = dat, aes(x, y)) +
     ylab(expression("Another really really really really long y label here "~cm^3))

p1 + p2 + plot_layout(ncol = 1)
```

![](https://i.imgur.com/UrvA92F.png)

Here's an example of what I think this should look like. :slightly_smiling_face:

``` r
library(cowplot)
plot_grid(p1, p2, ncol = 1, align = "hv")
```

![](https://i.imgur.com/RGAO9YX.png)

Created on 2018-11-29 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by thomasp85** [comment]
This is not really something patchwork can do anything about... A similar discussion appeared in ggplot2 some time ago https://github.com/tidyverse/ggplot2/issues/3216
