### ISSUE TITLE
Is it possible to use patchwork with shiny renderPlot / reactives?

### ISSUE THREAD

**Issue by JasonAizkalns** [thomasp85/patchwork#87]
Is it possible to use patchwork within a shiny context such as an interactive rmarkdown notebook and/or via reactives / renderPlot and the like? For example:

<pre><code>---
title: "R Notebook"
output: html_notebook
runtime: shiny
---

```{r setup, include=FALSE}
library(ggplot2)
library(shiny)
library(patchwork)
```

```{r}
blank1 <- renderPlot({ ggplot() + labs(title = "Plot 1") })
blank2 <- renderPlot({ ggplot() + labs(title = "Plot 2") })
blank3 <- renderPlot({ ggplot() + labs(title = "Plot 3") })

blank1 + blank2 + blank3
```
</pre></code>

However, the above does not work:

 `Error in blank1 + blank2 : non-numeric argument to binary operator`

Note: I have a [similar question listed on SO](https://stackoverflow.com/q/53823503/2572423)

**Comment by llrs** [comment]
I think you would need to first join them and then use the `renderPlot` function. However without data you'll get an error `Error: $ operator is invalid for atomic vectors`, I've used iris to test that `renderPlot({p1 + p2 + p3})` works.
