### ISSUE TITLE
plot_spacer() is too narrow

### ISSUE THREAD

**Issue by lindeloev** [thomasp85/patchwork#88]
`plot_spacer()` is too narrow, making the other plots vertically misaligned. Are there workaround to this? A simple example:

```
# Make a plot
p = ggplot(mtcars, aes(x=cyl, y=mpg)) +
  stat_summary()

# Arrange it
(p | p | p | p) /  # First row
  (p | plot_spacer() | p | p)  # Second row
```
![image](https://user-images.githubusercontent.com/1439417/50906012-7670e880-1424-11e9-8f25-085fafb14270.png)

I checked that this is not simply caused by `plot_spacer()` using a different margin. Adding `& theme(plot.margin = margin(0, 0, 0, 0))` gives the same misalignment:
![image](https://user-images.githubusercontent.com/1439417/50906272-0747c400-1425-11e9-8799-ccdf199875aa.png)

`Patchwork` is a really awesome package, thank you!

**Comment by lindeloev** [comment]
A workaround: use `plot_layout()` like this:

```
p + p + p + p + # First row
  p + plot_spacer() + p + p +  # Second row
  plot_layout(nrow=2)  # Layout
```
![image](https://user-images.githubusercontent.com/1439417/50906817-39a5f100-1426-11e9-9b0d-efe21420f44e.png)

**Comment by kuriwaki** [comment]
documentation on how `plot_spacer()` determines the spacing could be very helpful.

**Comment by thomasp85** [comment]
plot_spacer adds the equivalent of a plot panel. As ticks and axis labels also factor into the size of real plots a plot_spacer may not be exactly as large as other plots. In any way, when nesting plots, separate nested areas will not be internally aligned. @lindeloev's solution is the correct approach
