### ISSUE TITLE
geom_sf() and patchwork

### ISSUE THREAD

**Issue by modche** [thomasp85/patchwork#89]
Hello,

I love the patchwork package! Great work!

I have two graphs `g1` and `g2` both containing a map with `ggplot() + geom_sf(data=map)`. If I plot the single objects everything is fine, but `g1 + g2`gives an error `Error: Don't know how to add o to a plot`. Any ideas?

```{r}
library(gridExtra)
grid.arrange(g1,g2, ncol=2)
```
works also.

Thanks.
Michael

**Comment by thomasp85** [comment]
Can I get you to provide a reproducible example?

**Comment by modche** [comment]
I am very sorry, was an issue of the running R session.
