### ISSUE TITLE
Error with instalation

### ISSUE THREAD

**Issue by sarelag** [thomasp85/patchwork#90]
Hi,

I get the following error with the installation:
Error: package or namespace load failed for 'patchwork' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): namespace 'rlang' 0.2.2 is already loaded, but >= 0.3.1 is required

The problem is also that I know get the same error when I use other libraries

**Comment by thomasp85** [comment]
You probably just need to restart R

**Comment by komwomak** [comment]
install.packages("patchwork") yields the following error message both before and after an R restart:

Warning in install.packages :
  package ‘patchwork’ is not available (for R version 3.5.2)
>

**Comment by thomasp85** [comment]
That is because patchwork is not yet available on CRAN. please follow the installation instructions in the readme

**Comment by sarelag** [comment]
Thanks!

O 16:58, xov., 31/01/2019, Thomas Lin Pedersen <notifications@github.com>
escribiu:
