### ISSUE TITLE
Error: package or namespace load failed for ‘forecast’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):  namespace ‘rlang’ 0.2.1 is already loaded, but >= 0.3.0.1 is required

### ISSUE THREAD

**Issue by guangmeiye** [thomasp85/patchwork#91]
after trying 
devtools::install_github("ricardo-bion/ggradar") and failed in install rlang
my forecast packages and many other packaged cannot be used.
![error screenshot](https://user-images.githubusercontent.com/47375532/53164653-b5a36500-359e-11e9-9a1a-3eacec2957fa.jpg)
after I tried to delete all history data and unstall R and R studio, this problem still exist.
what should I do ?

**Comment by llrs** [comment]
I think this is not the right place for this issue. But you should install the right rlang version before trying to load libraries that depend on later versions of rlang. Try `install.packages("rlang")`  but you might need to update more packages with `update.packages()`.

**Comment by steveharoz** [comment]
I'm going to close the issue, but feel free to reopen it if you have more info.

**Comment by 5Graamus** [comment]
I need help
When i use this this command: library("rlang") i Rstudio i get this error:
Error: package or namespace load failed for ‘rlang’:
 .onLoad fejlede i loadNamespace() for 'rlang', detaljer:
  kald: fun(libname, pkgname)
  fejl: object 'r_init_library' not found

**Comment by steveharoz** [comment]
Hello @5Graamus. Is does this issue relate specifically to the patchwork library? If not, stackoverflow.com would be a better place to get an answer.
