### ISSUE TITLE
Empty plot takes up much more space

### ISSUE THREAD

**Issue by adrfantini** [thomasp85/patchwork#95]
I setup a quick and dirty script to produce some plots. It uses `patchwork` to assemble them. You can find it [here](https://github.com/adrfantini/lastmonth-weather), together with the results.

`patchwork` here assembles 10 different 7x7 plots in a larger, 14x35 one. It works great if all the plots are similar, or identical, such when sourcing the config file `config_bandiera.R`:
![](https://raw.githubusercontent.com/adrfantini/lastmonth-weather/master/plots/201904/bandiera/patchwork.png)

However, in one case (uncomment `source('config_borgogrotta.R')` in `produce_plots.R`) a variable is missing, and my script thus creates an empty plot with the same size for that variable:
![](https://raw.githubusercontent.com/adrfantini/lastmonth-weather/master/plots/201904/borgogrotta/WindMaxDir.png)

This works well.
However, when I assemble the plots together...
![](https://raw.githubusercontent.com/adrfantini/lastmonth-weather/master/plots/201904/borgogrotta/patchwork.png)

Something breaks. Any idea what it is?

**Comment by steveharoz** [comment]
Hi @adrfantini. Thanks for posting the issue. I'm having trouble reproducing this issue with a minimal example:

```
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p_blank <- ggplot(mtcars)

p1 + p2 + p1 + p_blank + p1 + p2
```

![image](https://user-images.githubusercontent.com/2257540/64435906-9942c200-d0c3-11e9-8195-1d4e5c9c651a.png)

If you could reproduce the issue using a simple dataset like mtcars, it'd be simpler to debug. I'm going to close the issue, but you can reopen it if you have a simple reprex.
