### ISSUE TITLE
patchwork to arrange gTree

### ISSUE THREAD

**Issue by efratushava** [thomasp85/patchwork#96]
Hello,

I downloaded this package in order to organize "gTree"-s, instead of using grid.arrange.
My gTree are orgenized in a list of gTree, called data.

When running "data[1][[1]]+data[2][[1]]" I get:

Error in data[1][[1]] + data[2][[1]] : 
  non-numeric argument to binary operator

What can I do?

**Comment by llrs** [comment]
Welcome @efratushava. If you could provide a reproducible example, for instance using [reprex](https://cran.r-project.org/package=reprex), it will help Thomas to see what can be done to work with gTrees (Are they from the ggtree package?)

**Comment by efratushava** [comment]
no. It is grobTree()

patchwork works only for ggplot?

**Comment by llrs** [comment]
Yes, it only works for [ggplot2](https://cran.r-project.org/package=ggplot2) derived objects. But I don't understand what type of objects do you have here, if you could post an example I could run on my computer I could try to help you more.

**Comment by steveharoz** [comment]
I'm going to close this issue. @efratushava, feel free to make a new issue with a simple reproducible example.
